program main
  implicit none
  integer(kind=8) :: bench_start, bench_end
  integer(kind=8) :: bench_mem0, bench_mem1
  bench_mem0 = mem_()
  bench_start = now_()
  print '(A)', trim("Door 1 Open")
  print '(A)', trim("Door 2 Closed")
  print '(A)', trim("Door 3 Closed")
  print '(A)', trim("Door 4 Open")
  print '(A)', trim("Door 5 Closed")
  print '(A)', trim("Door 6 Closed")
  print '(A)', trim("Door 7 Closed")
  print '(A)', trim("Door 8 Closed")
  print '(A)', trim("Door 9 Open")
  print '(A)', trim("Door 10 Closed")
  print '(A)', trim("Door 11 Closed")
  print '(A)', trim("Door 12 Closed")
  print '(A)', trim("Door 13 Closed")
  print '(A)', trim("Door 14 Closed")
  print '(A)', trim("Door 15 Closed")
  print '(A)', trim("Door 16 Open")
  print '(A)', trim("Door 17 Closed")
  print '(A)', trim("Door 18 Closed")
  print '(A)', trim("Door 19 Closed")
  print '(A)', trim("Door 20 Closed")
  print '(A)', trim("Door 21 Closed")
  print '(A)', trim("Door 22 Closed")
  print '(A)', trim("Door 23 Closed")
  print '(A)', trim("Door 24 Closed")
  print '(A)', trim("Door 25 Open")
  print '(A)', trim("Door 26 Closed")
  print '(A)', trim("Door 27 Closed")
  print '(A)', trim("Door 28 Closed")
  print '(A)', trim("Door 29 Closed")
  print '(A)', trim("Door 30 Closed")
  print '(A)', trim("Door 31 Closed")
  print '(A)', trim("Door 32 Closed")
  print '(A)', trim("Door 33 Closed")
  print '(A)', trim("Door 34 Closed")
  print '(A)', trim("Door 35 Closed")
  print '(A)', trim("Door 36 Open")
  print '(A)', trim("Door 37 Closed")
  print '(A)', trim("Door 38 Closed")
  print '(A)', trim("Door 39 Closed")
  print '(A)', trim("Door 40 Closed")
  print '(A)', trim("Door 41 Closed")
  print '(A)', trim("Door 42 Closed")
  print '(A)', trim("Door 43 Closed")
  print '(A)', trim("Door 44 Closed")
  print '(A)', trim("Door 45 Closed")
  print '(A)', trim("Door 46 Closed")
  print '(A)', trim("Door 47 Closed")
  print '(A)', trim("Door 48 Closed")
  print '(A)', trim("Door 49 Open")
  print '(A)', trim("Door 50 Closed")
  print '(A)', trim("Door 51 Closed")
  print '(A)', trim("Door 52 Closed")
  print '(A)', trim("Door 53 Closed")
  print '(A)', trim("Door 54 Closed")
  print '(A)', trim("Door 55 Closed")
  print '(A)', trim("Door 56 Closed")
  print '(A)', trim("Door 57 Closed")
  print '(A)', trim("Door 58 Closed")
  print '(A)', trim("Door 59 Closed")
  print '(A)', trim("Door 60 Closed")
  print '(A)', trim("Door 61 Closed")
  print '(A)', trim("Door 62 Closed")
  print '(A)', trim("Door 63 Closed")
  print '(A)', trim("Door 64 Open")
  print '(A)', trim("Door 65 Closed")
  print '(A)', trim("Door 66 Closed")
  print '(A)', trim("Door 67 Closed")
  print '(A)', trim("Door 68 Closed")
  print '(A)', trim("Door 69 Closed")
  print '(A)', trim("Door 70 Closed")
  print '(A)', trim("Door 71 Closed")
  print '(A)', trim("Door 72 Closed")
  print '(A)', trim("Door 73 Closed")
  print '(A)', trim("Door 74 Closed")
  print '(A)', trim("Door 75 Closed")
  print '(A)', trim("Door 76 Closed")
  print '(A)', trim("Door 77 Closed")
  print '(A)', trim("Door 78 Closed")
  print '(A)', trim("Door 79 Closed")
  print '(A)', trim("Door 80 Closed")
  print '(A)', trim("Door 81 Open")
  print '(A)', trim("Door 82 Closed")
  print '(A)', trim("Door 83 Closed")
  print '(A)', trim("Door 84 Closed")
  print '(A)', trim("Door 85 Closed")
  print '(A)', trim("Door 86 Closed")
  print '(A)', trim("Door 87 Closed")
  print '(A)', trim("Door 88 Closed")
  print '(A)', trim("Door 89 Closed")
  print '(A)', trim("Door 90 Closed")
  print '(A)', trim("Door 91 Closed")
  print '(A)', trim("Door 92 Closed")
  print '(A)', trim("Door 93 Closed")
  print '(A)', trim("Door 94 Closed")
  print '(A)', trim("Door 95 Closed")
  print '(A)', trim("Door 96 Closed")
  print '(A)', trim("Door 97 Closed")
  print '(A)', trim("Door 98 Closed")
  print '(A)', trim("Door 99 Closed")
  print '(A)', trim("Door 100 Open")
  bench_end = now_()
  bench_mem1 = mem_()
  print '(A)', '{'
  print '(A,I0,A)', '  "duration_us": ', bench_end - bench_start, ','
  print '(A,I0,A)', '  "memory_bytes": ', bench_mem1 - bench_mem0, ','
  print '(A)', '  "name": "main"'
  print '(A)', '}'
contains
function now_() result(res)
  implicit none
  integer(kind=8) :: res
  integer(kind=8) :: count, rate
  call system_clock(count, rate)
  res = count * 1000000 / rate
end function now_
function mem_() result(res)
  implicit none
  integer(kind=8) :: res
  integer :: unit, ios
  integer(kind=8) :: a,b
  res = 0
  open(newunit=unit, file='/proc/self/statm', action='read', status='old', iostat=ios)
  if (ios == 0) then
    read(unit, *, iostat=ios) a, b
    if (ios == 0) res = b * 4096
    close(unit)
  end if
end function mem_
end program main
