;; Generated by Mochi 0.10.72 on 2025-08-24 23:17 +0700
#lang racket/base
(require racket/list racket/string racket/math racket/match racket/format racket/system racket/port racket/vector net/url net/http-client json openssl/sha1 openssl/md5)
(define nowSeed (let ([s (getenv "MOCHI_NOW_SEED")]) (and s (string->number s))))
(define _data_dir "tests/github/TheAlgorithms/Mochi/data_structures/queues")
(define (now)
  (if nowSeed
      (begin (set! nowSeed (modulo (+ (* nowSeed 1664525) 1013904223) 2147483647)) nowSeed)
      (inexact->exact (floor (* (current-inexact-monotonic-milliseconds) 1000)))))
(define (int x)
  (cond
    [(number? x) (inexact->exact (truncate x))]
    [(string? x) (let ([n (string->number x)]) (if n (inexact->exact (truncate n)) 0))]
    [else 0]))
(define (float x)
  (cond
    [(number? x) (exact->inexact x)]
    [(string? x) (let ([n (string->number x)]) (if n (exact->inexact n) 0.0))]
    [else 0.0]))
(define (to-string x)
  (cond
    [(number? x)
     (cond
       [(and (inexact? x) (integer? x)) (format "~a.0" (inexact->exact x))]
       [else (number->string x)])]
    [(vector? x) (format "~a" (map (lambda (v) (cond [(hash? v) (read (open-input-string (to-string v)))] [(vector? v) (vector->list v)] [else v])) (vector->list x)))]
    [(hash? x)
     (format "~a"
             (for/hash ([k (in-hash-keys x)])
               (values k (let ([v (hash-ref x k)]) (if (vector? v) (vector->list v) v)))))]
    [else (format "~a" x)]))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (sublist lst start end)
  (cond
    [(string? lst) (substring lst start end)]
    [(vector? lst) (vector->list (vector-copy lst start end))]
    [else (take (drop lst start) (- end start))]))

(define (slice seq start end)
  (define len (cond [(string? seq) (string-length seq)] [(vector? seq) (vector-length seq)] [else (length seq)]))
  (define s (int start))
  (define e (int end))
  (when (< s 0) (set! s (+ len s)))
  (when (< e 0) (set! e (+ len e)))
  (set! s (max 0 (min len s)))
  (set! e (max 0 (min len e)))
  (when (< e s) (set! e s))
  (cond
    [(string? seq) (substring seq s e)]
    [(vector? seq) (vector-copy seq s e)]
    [else (sublist seq s e)]))
(define (pad-start s width ch)
  (let ([s (to-string s)])
    (if (< (string-length s) width)
        (string-append (make-string (- width (string-length s)) (string-ref ch 0)) s)
        s)))
(define (index-of s ch)
  (cond
    [(string? s)
     (let loop ([i 0])
       (cond [(>= i (string-length s)) -1]
             [(string=? (substring s i (add1 i)) ch) i]
             [else (loop (add1 i))]))]
    [else
     (let loop ([i 0] [lst s])
       (cond [(null? lst) -1]
             [(equal? (car lst) ch) i]
             [else (loop (add1 i) (cdr lst))]))]))
(define (appendv a b)
  (cond
    [(vector? a) (vector-append a (cond [(vector? b) b] [(list? b) (list->vector b)] [else (vector b)]))]
    [(list? a) (append a (cond [(list? b) b] [(vector? b) (vector->list b)] [else (list b)]))]
    [else (append a b)]))
(define (safe-index lst idx) (let ([i (int idx)]) (cond [(list? lst) (if (and (>= i 0) (< i (length lst))) (list-ref lst i) '())] [(vector? lst) (if (and (>= i 0) (< i (vector-length lst))) (vector-ref lst i) '())] [(string? lst) (if (and (>= i 0) (< i (string-length lst))) (substring lst i (add1 i)) "")] [else 0])))
(define (_repeat s n)
  (cond
    [(string? s) (apply string-append (make-list (int n) s))]
    [(list? s) (apply append (make-list (int n) s))]
    [else '()]))
(define (_ord s) (char->integer (string-ref s 0)))
(define (read_file path)
  (define p path)
  (let ([root (getenv "MOCHI_ROOT")])
    (when (and root (not (file-exists? p)))
      (set! p (path->string (build-path root _data_dir path)))))
  (with-input-from-file p port->string))
(define (list-set lst idx val)
  (define i (int idx))
  (cond
    [(vector? lst) (when (< i (vector-length lst)) (vector-set! lst i val)) lst]
    [else
     (define len (length lst))
     (cond
       [(>= i len) (append lst (make-list (- i len) '()) (list val))]
       [(zero? i) (cons val (cdr lst))]
       [else (cons (car lst) (list-set (cdr lst) (sub1 i) val))])]))
(define (_parse-int-str s base) (int (string->number s base)))
(define (_sha256 bs) (bytes->list (sha256-bytes (if (string? bs) (string->bytes/utf-8 bs) (list->bytes bs)))))
(define (_fetch url [opts #f]) (let ([p (get-pure-port (string->url url))]) (define txt (port->string p)) (close-input-port p) (string->jsexpr txt)))
(define (num r) (numerator r))
(define (denom r) (denominator r))
(define (panic msg) (error msg))
(define (json-encode x)
  (define (sanitize v)
    (cond
      [(hash? v) (for/hash ([k (in-hash-keys v)]) (values (string->symbol k) (sanitize (hash-ref v k))))]
      [(list? v) (map sanitize v)]
      [else v]))
  (jsexpr->string (sanitize x)))
(define Object (hash "keys" (lambda (self m) (let ([lst (hash-keys m)]) (hash "join" (lambda (s sep) (string-join lst sep)))))))
(define stdout (hash "write" (lambda (s) (display s))))
(define __name__ "__main__")
(define (input) (let ([ln (read-line)]) (if (eof-object? ln) "" ln)))

(define (empty_deque)
  (let/ec _return (begin
(_return (let ([h (make-hash)]) (hash-set! h "data" (vector)) h))
))
)
(define (push_back dq value)
  (let/ec _return (begin
(_return (let ([h (make-hash)]) (hash-set! h "data" (appendv (or (if dq (hash-ref dq "data" #f) #f) (vector)) (vector value))) h))
))
)
(define (push_front dq value)
  (let/ec _return (begin
(define res (vector value))
(define i 0)
(let/ec _break (let loop ()
  (if (let ([__l i] [__r (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))])]) (cond [(and (number? __l) (number? __r)) (< __l __r)] [else (< (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! res (appendv (or res (vector)) (vector (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) i #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int i))) #f))))
      (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    )
    (loop)) (void))))
(_return (let ([h (make-hash)]) (hash-set! h "data" res) h))
))
)
(define (extend_back dq values)
  (let/ec _return (begin
(define res (if dq (hash-ref dq "data" #f) #f))
(define i 0)
(let/ec _break (let loop ()
  (if (let ([__l i] [__r (cond [(not values) 0] [(string? values) (string-length values)] [(vector? values) (vector-length values)] [(hash? values) (hash-count values)] [else (length values)])]) (cond [(and (number? __l) (number? __r)) (< __l __r)] [else (< (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! res (appendv (or res (vector)) (vector (if values (if (hash? values) (hash-ref values i #f) (safe-index values (int i))) #f))))
      (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    )
    (loop)) (void))))
(_return (let ([h (make-hash)]) (hash-set! h "data" res) h))
))
)
(define (extend_front dq values)
  (let/ec _return (begin
(define res (vector))
(define i (- (cond [(not values) 0] [(string? values) (string-length values)] [(vector? values) (vector-length values)] [(hash? values) (hash-count values)] [else (length values)]) 1))
(let/ec _break (let loop ()
  (if (let ([__l i] [__r 0]) (cond [(and (number? __l) (number? __r)) (>= __l __r)] [else (>= (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! res (appendv (or res (vector)) (vector (if values (if (hash? values) (hash-ref values i #f) (safe-index values (int i))) #f))))
      (set! i (- i 1))
    )
    (loop)) (void))))
(define j 0)
(let/ec _break (let loop ()
  (if (let ([__l j] [__r (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))])]) (cond [(and (number? __l) (number? __r)) (< __l __r)] [else (< (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! res (appendv (or res (vector)) (vector (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) j #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int j))) #f))))
      (set! j (let ([__l j] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    )
    (loop)) (void))))
(_return (let ([h (make-hash)]) (hash-set! h "data" res) h))
))
)
(define (pop_back dq)
  (let/ec _return (begin
(if (equal? (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 0) (let ()
(panic "pop from empty deque")
) (void))
(define res (vector))
(define i 0)
(let/ec _break (let loop ()
  (if (let ([__l i] [__r (- (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 1)]) (cond [(and (number? __l) (number? __r)) (< __l __r)] [else (< (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! res (appendv (or res (vector)) (vector (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) i #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int i))) #f))))
      (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    )
    (loop)) (void))))
(_return (let ([h (make-hash)]) (hash-set! h "deque" (let ([h (make-hash)]) (hash-set! h "data" res) h)) (hash-set! h "value" (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) (- (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 1) #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int (- (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 1)))) #f)) h))
))
)
(define (pop_front dq)
  (let/ec _return (begin
(if (equal? (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 0) (let ()
(panic "popleft from empty deque")
) (void))
(define res (vector))
(define i 1)
(let/ec _break (let loop ()
  (if (let ([__l i] [__r (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))])]) (cond [(and (number? __l) (number? __r)) (< __l __r)] [else (< (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! res (appendv (or res (vector)) (vector (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) i #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int i))) #f))))
      (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    )
    (loop)) (void))))
(_return (let ([h (make-hash)]) (hash-set! h "deque" (let ([h (make-hash)]) (hash-set! h "data" res) h)) (hash-set! h "value" (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) 0 #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int 0))) #f)) h))
))
)
(define (is_empty dq)
  (let/ec _return (begin
(_return (equal? (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 0))
))
)
(define (length_ dq)
  (let/ec _return (begin
(_return (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]))
))
)
(define (to_string dq)
  (let/ec _return (begin
(if (equal? (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))]) 0) (let ()
(_return "[]")
) (void))
(define s (string-append "[" (to-string (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) 0 #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int 0))) #f))))
(define i 1)
(let/ec _break (let loop ()
  (if (let ([__l i] [__r (cond [(not (if dq (hash-ref dq "data" #f) #f)) 0] [(string? (if dq (hash-ref dq "data" #f) #f)) (string-length (if dq (hash-ref dq "data" #f) #f))] [(vector? (if dq (hash-ref dq "data" #f) #f)) (vector-length (if dq (hash-ref dq "data" #f) #f))] [(hash? (if dq (hash-ref dq "data" #f) #f)) (hash-count (if dq (hash-ref dq "data" #f) #f))] [else (length (if dq (hash-ref dq "data" #f) #f))])]) (cond [(and (number? __l) (number? __r)) (< __l __r)] [else (< (int __l) (int __r))])) (begin
    (let/ec _cont
      (set! s (string-append (string-append s ", ") (to-string (if (if dq (hash-ref dq "data" #f) #f) (if (hash? (if dq (hash-ref dq "data" #f) #f)) (hash-ref (if dq (hash-ref dq "data" #f) #f) i #f) (safe-index (if dq (hash-ref dq "data" #f) #f) (int i))) #f))))
      (set! i (let ([__l i] [__r 1]) (if (and (string? __l) (string? __r)) (string-append __l __r) (+ __l __r))))
    )
    (loop)) (void))))
(_return (string-append s "]"))
))
)
(define (main)
  (let/ec _return (begin
(define dq (empty_deque))
(set! dq (push_back dq 2))
(set! dq (push_front dq 1))
(set! dq (extend_back dq (vector 3 4)))
(set! dq (extend_front dq (vector 0)))
(displayln (to-string (to_string dq)))
(define r (pop_back dq))
(set! dq (if r (hash-ref r "deque" #f) #f))
(displayln (to-string (if r (hash-ref r "value" #f) #f)))
(set! r (pop_front dq))
(set! dq (if r (hash-ref r "deque" #f) #f))
(displayln (to-string (if r (hash-ref r "value" #f) #f)))
(displayln (to-string (to_string dq)))
(displayln (to-string (is_empty (empty_deque))))
))
)
(let* ([_start_mem (current-memory-use)] [_start (current-inexact-monotonic-milliseconds)])
  (let/ec _return (begin
(main)
    (void)
  ))
  (let* ([_end (current-inexact-monotonic-milliseconds)] [_end_mem (current-memory-use)]
         [_dur_us (max 1 (exact-ceiling (* (- _end _start) 1000)))]
         [_mem (max 0 (- _end_mem _start_mem))])
    (displayln "{")
    (displayln (format "  \"duration_us\": ~a," _dur_us))
    (displayln (format "  \"memory_bytes\": ~a," _mem))
    (displayln "  \"name\": \"main\"")
    (displayln "}")
  )
)
