(ns main)
(require 'clojure.set)
(defrecord People [name age city])
(def people [{:name "Alice" :age 30 :city "Paris"} {:name "Bob" :age 15 :city "Hanoi"} {:name "Charlie" :age 65 :city "Paris"} {:name "Diana" :age 45 :city "Hanoi"} {:name "Eve" :age 70 :city "Paris"} {:name "Frank" :age 22 :city "Hanoi"}])
(def stats (for [g (for [[k rows] (group-by :key (for [person people :let [k (:city person)]] {:key k :item person})) :let [g {:key k :items (map :item rows)}]] g)] {:city (:key g) :count (count (:items g)) :avg_age (double (/ (reduce + 0 (for [p (:items g)] (:age p))) (count (for [p (:items g)] (:age p)))))}))
(defn -main [] (println "--- People grouped by city ---") (doseq [s stats] (println (:city s) ": count =" (:count s) ", avg_age =" (:avg_age s))))
(-main)
