(ns main (:refer-clojure :exclude [twoSum]))
(require 'clojure.set)
(defn twoSum [nums target] (def n (count nums)) (dotimes [i n] (doseq [j (range (+ i 1) n)] (when (= (+ (nth nums i) (nth nums j)) target) [i j]))) [(- 1) (- 1)])
(def result (twoSum [2 7 11 15] 9))
(defn -main [] (println (nth result 0)) (println (nth result 1)))
(-main)
