(define prefix "fore")
(define s1 "forest")
(display (if (string=? (substring s1 0 (string-length prefix)) prefix)
            "true" "false"))
(newline)
(define s2 "desert")
(display (if (string=? (substring s2 0 (min (string-length prefix) (string-length s2))) prefix)
            "true" "false"))
(newline)
