(define (two-sum nums target)
  (let loop ((i 0))
    (if (= i (length nums))
        '(-1 -1)
        (let inner ((j (+ i 1)))
          (cond ((= j (length nums)) (loop (+ i 1)))
                ((= (+ (list-ref nums i) (list-ref nums j)) target)
                 (list i j))
                (else (inner (+ j 1))))))))

(define result (two-sum '(2 7 11 15) 9))
(display (list-ref result 0))
(newline)
(display (list-ref result 1))
(newline)
