math = {sqrt = math.sqrt, pow = math.pow, sin = math.sin, log = math.log, pi = math.pi, e = math.exp(1)};
r = 3;
area = (math.pi * math.pow(r, 2));
root = math.sqrt(49);
sin45 = math.sin((math.pi / 4));
log_e = math.log(math.e);
print((string.gsub(string.format("Circle area with r = %s => %s", r, area), "%s+$", "")));
print((string.gsub(string.format("Square root of 49: %s", root), "%s+$", "")));
print((string.gsub(string.format("sin(π/4): %s", sin45), "%s+$", "")));
print((string.gsub(string.format("log(e): %s", log_e), "%s+$", "")));
