// Generated by Mochi 0.10.32 on 2025-08-25 17:21 +0700
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <malloc.h>
#include <math.h>


size_t append_len;
static char* str_concat(const char *a, const char *b) {
    size_t len1 = strlen(a);
    size_t len2 = strlen(b);
    char *res = malloc(len1 + len2 + 1);
    memcpy(res, a, len1);
    memcpy(res + len1, b, len2);
    res[len1 + len2] = 0;
    return res;
}

static char* str_int(long long v) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%lld", v);
    return strdup(buf);
}

static char* str_float(double v) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%f", v);
    char *p = buf + strlen(buf) - 1;
    while (p > buf && *p == '0') *p-- = '\0';
    if (p > buf && *p == '.') *p = '\0';
    return strdup(buf);
}

static double* list_append_double(double *arr, size_t *len, double val) {
    arr = realloc(arr, (*len + 1) * sizeof(double));
    arr[*len] = val;
    (*len)++;
    return arr;
}

#include <time.h>
static int seeded_now = 0;
static long long now_seed = 0;
static long long _now(void) {
    if (!seeded_now) {
        const char *s = getenv("MOCHI_NOW_SEED");
        if (s && *s) {
            now_seed = atoll(s);
            seeded_now = 1;
        }
    }
    if (seeded_now) {
        now_seed = (now_seed * 1664525 + 1013904223) % 2147483647;
        return now_seed;
    }
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return (long long)(ts.tv_sec * 1000000000LL + ts.tv_nsec);
}

static long long _mem(void) {
    long long size = 0, rss = 0;
    FILE *f = fopen("/proc/self/statm", "r");
    if (f) {
        if (fscanf(f, "%lld %lld", &size, &rss) != 2) rss = 0;
        fclose(f);
    }
    return rss * (long long)sysconf(_SC_PAGESIZE);
}

static void panic(const char *msg) {
    fputs(msg, stderr);
    fputc('\n', stderr);
    exit(1);
}

typedef struct Result Result;

struct Result {
    long long start;
    long long end;
    double sum;
};

Result max_cross_sum(double * arr, size_t arr_len, long long low, long long mid, long long high);
Result max_subarray(double * arr, size_t arr_len, long long low, long long high);
void show(Result res);
void user_main();
int main(void);

Result max_cross_sum(double * arr, size_t arr_len, long long low, long long mid, long long high) {
    double left_sum = -1e+18;
    long long max_left = -1LL;
    double sum = 0.0;
    long long i = mid;
    while (i >= low) {
        sum = sum + arr[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? arr_len + _mochi_idx : _mochi_idx;})];
        if (sum > left_sum) {
            left_sum = sum;
            max_left = i;
        }
        i = i - 1LL;
    }
    double right_sum = -1e+18;
    long long max_right = -1LL;
    sum = 0.0;
    i = mid + 1LL;
    while (i <= high) {
        sum = sum + arr[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? arr_len + _mochi_idx : _mochi_idx;})];
        if (sum > right_sum) {
            right_sum = sum;
            max_right = i;
        }
        i = i + 1LL;
    }
    return (Result){.start = max_left, .end = max_right, .sum = left_sum + right_sum};
}

Result max_subarray(double * arr, size_t arr_len, long long low, long long high) {
    if (arr_len == 0LL) {
        return (Result){.start = -1LL, .end = -1LL, .sum = 0.0};
    }
    if (low == high) {
        return (Result){.start = low, .end = high, .sum = arr[(int)({long long _mochi_idx = low; _mochi_idx < 0 ? arr_len + _mochi_idx : _mochi_idx;})]};
    }
    long long mid = (low + high) / 2LL;
    Result left = max_subarray(arr, arr_len, low, mid);
    Result right = max_subarray(arr, arr_len, mid + 1LL, high);
    Result cross = max_cross_sum(arr, arr_len, low, mid, high);
    if ((left.sum >= right.sum) && (left.sum >= cross.sum)) {
        return left;
    }
    if ((right.sum >= left.sum) && (right.sum >= cross.sum)) {
        return right;
    }
    return cross;
}

void show(Result res) {
    puts(str_concat(str_concat(str_concat(str_concat(str_concat(str_concat("[", str_int(res.start)), ", "), str_int(res.end)), ", "), str_float(res.sum)), "]"));
}

void user_main() {
    double *nums1 = NULL;
    size_t nums1_len = 0;
    nums1 = list_append_double(nums1, &nums1_len, -2.0);
    nums1 = list_append_double(nums1, &nums1_len, 1.0);
    nums1 = list_append_double(nums1, &nums1_len, -3.0);
    nums1 = list_append_double(nums1, &nums1_len, 4.0);
    nums1 = list_append_double(nums1, &nums1_len, -1.0);
    nums1 = list_append_double(nums1, &nums1_len, 2.0);
    nums1 = list_append_double(nums1, &nums1_len, 1.0);
    nums1 = list_append_double(nums1, &nums1_len, -5.0);
    nums1 = list_append_double(nums1, &nums1_len, 4.0);
    Result res1 = max_subarray(nums1, nums1_len, 0LL, 8LL);
    show(res1);
    double *nums2 = NULL;
    size_t nums2_len = 0;
    nums2 = list_append_double(nums2, &nums2_len, 2.0);
    nums2 = list_append_double(nums2, &nums2_len, 8.0);
    nums2 = list_append_double(nums2, &nums2_len, 9.0);
    Result res2 = max_subarray(nums2, nums2_len, 0LL, 2LL);
    show(res2);
    double *nums3 = NULL;
    size_t nums3_len = 0;
    nums3 = list_append_double(nums3, &nums3_len, 0.0);
    nums3 = list_append_double(nums3, &nums3_len, 0.0);
    Result res3 = max_subarray(nums3, nums3_len, 0LL, 1LL);
    show(res3);
    double *nums4 = NULL;
    size_t nums4_len = 0;
    nums4 = list_append_double(nums4, &nums4_len, -1.0);
    nums4 = list_append_double(nums4, &nums4_len, 0.0);
    nums4 = list_append_double(nums4, &nums4_len, 1.0);
    Result res4 = max_subarray(nums4, nums4_len, 0LL, 2LL);
    show(res4);
    double *nums5 = NULL;
    size_t nums5_len = 0;
    nums5 = list_append_double(nums5, &nums5_len, -2.0);
    nums5 = list_append_double(nums5, &nums5_len, -3.0);
    nums5 = list_append_double(nums5, &nums5_len, -1.0);
    nums5 = list_append_double(nums5, &nums5_len, -4.0);
    nums5 = list_append_double(nums5, &nums5_len, -6.0);
    Result res5 = max_subarray(nums5, nums5_len, 0LL, 4LL);
    show(res5);
    double *nums6 = NULL;
    size_t nums6_len = 0;
    Result res6 = max_subarray(nums6, nums6_len, 0LL, 0LL);
    show(res6);
}

int main(void) {
    {
        long long __start = _now();
        user_main();
        long long __end = _now();
        long long __dur_us = (__end - __start) / 1000;
        long long __mem_bytes = _mem();
        printf("{\n  \"duration_us\": %-lld,\n  \"memory_bytes\": %-lld,\n  \"name\": \"main\"\n}\n", __dur_us, __mem_bytes);
    }
    return 0;
}
