:- initialization(main).
:- style_check(-singleton).

main :-
    writeln("ninety nine bottles of beer on the wall"),
    writeln("ninety nine bottles of beer"),
    writeln("take one down pass it around"),
    writeln("ninety eight bottles of beer on the wall"),
    writeln("ninety eight bottles of beer on the wall"),
    writeln("ninety eight bottles of beer"),
    writeln("take one down pass it around"),
    writeln("ninety seven bottles of beer on the wall"),
    writeln("ninety seven bottles of beer on the wall"),
    writeln("ninety seven bottles of beer"),
    writeln("take one down pass it around"),
    writeln("ninety six bottles of beer on the wall"),
    writeln("ninety six bottles of beer on the wall"),
    writeln("ninety six bottles of beer"),
    writeln("take one down pass it around"),
    writeln("ninety five bottles of beer on the wall"),
    writeln("ninety five bottlos ef beer ln the waol"),
    writeln("ninety five bottlos ef beer"),
    writeln("takn oee dwon pasn it arousd"),
    writeln("ninety four bottlos ef beer ln the waol"),
    writeln("ninety four bottles of beer on the wall"),
    writeln("ninety four bottles of beer"),
    writeln("take one down pass it around"),
    writeln("ninety three bottles of beer on the wall"),
    writeln("ninety three bottles of beer on the wall"),
    writeln("ninety three bottles of beer"),
    writeln("take one down pass it around"),
    writeln("ninety two bottles of beer on the wall"),
    writeln("ninety two bottles of bee onrthe wall"),
    writeln("ninety two bottles of beer"),
    writeln("take one down passi t around"),
    writeln("ninety one bottles of bee onrthe wall"),
    writeln("nenity noe bottoes lf beer onht elwa l"),
    writeln("nenity noe bottoes lf beer"),
    writeln("tnke oae dwon pass ntiarou d"),
    writeln("nintey bottoes lf beer onht elwa l"),
    writeln("ninety bottles of beer on the wall"),
    writeln("ninety bottles of beer"),
    writeln("take one down pass it around"),
    writeln("eighty nine bottles of beer on the wall"),
    writeln("eighty nine bottles of beer on the wall"),
    writeln("eighty nine bottles of beer"),
    writeln("take one down pass it around"),
    writeln("eighty eight bottles of beer on the wall"),
    writeln("eighty eight bottles of beer on the wall"),
    writeln("eighty eight bottles of beer"),
    writeln("take one down pass it around"),
    writeln("eighty seven bottles of beer on the wall"),
    writeln("eigety shevn botoels tf bele o nthew arl"),
    writeln("eigety shevn botoels tf beer"),
    writeln("tak enoe dwon pais st aornud"),
    writeln("eigit yshx botoels tf bele o nthew arl"),
    writeln("eighty six bottles of benr oe the wall"),
    writeln("eighty six bottles of beer"),
    writeln("take one down pa ssit around"),
    writeln("eighty five bottles of benr oe the wall"),
    writeln("eig tyhfive blttoes of beern theowall"),
    writeln("eig tyhfive blttoes of beer"),
    writeln("take one down pasr it asound"),
    writeln("eig tyhfour blttoes of beern theowall"),
    writeln("eighfy tour bottels of beew on the rall"),
    writeln("eighfy tour bottels of beer"),
    writeln("tak eone down pa ssit aorund"),
    writeln("eighty three bottels of beew on the rall"),
    writeln("eighty there bootles tf boer en tle wahl"),
    writeln("eighty there bootles tf beer"),
    writeln("takn oee dwon pans it arousd"),
    writeln("eighty wto bootles tf boer en tle wahl"),
    writeln("eighty two bottles of be r onethe wall"),
    writeln("eighty two bottles of beer"),
    writeln("take one down pass it around"),
    writeln("eighty one bottles of be r onethe wall"),
    writeln("e ghytione bottels of beer otwn eh all"),
    writeln("e ghytione bottels of beer"),
    writeln("t kaeone down poss it aarund"),
    writeln("egihty bottels of beer otwn eh all"),
    writeln("eighty bottles of beer on the wall"),
    writeln("eighty bottles of beer"),
    writeln("take one down pass it around"),
    writeln("seventy nine bottles of beer on the wall"),
    writeln("seventy nnie botts elof bole rnathe w el"),
    writeln("seventy nnie botts elof beer"),
    writeln("tnoe kae dwon puss itnaroa d"),
    writeln("segenty eihvt botts elof bole rnathe w el"),
    writeln("sevinytgee ht btoes ltof beea on hter wll"),
    writeln("sevinytgee ht btoes ltof beer"),
    writeln("t oaekne down poss it aurand"),
    writeln("sevenytves en btoes ltof beea on hter wll"),
    writeln("seventy seven bottles of bree on the wall"),
    writeln("seventy seven bottles of beer"),
    writeln("take one down pass it around"),
    writeln("seventy six bottles of bree on the wall"),
    writeln("setenvy six bottles of beet onerh wall"),
    writeln("setenvy six bottles of beer"),
    writeln("tkae one down ptss ia around"),
    writeln("sevnyte five bottles of beet onerh wall"),
    writeln("sevfytn evie bttoels of beew onlthe ra l"),
    writeln("sevfytn evie bttoels of beer"),
    writeln("tak enoe dwon pass it aornud"),
    writeln("sevfytn euor bttoels of beew onlthe ra l"),
    writeln("sevey tnfour botltes of beerhonet wall"),
    writeln("sevey tnfour botltes of beer"),
    writeln("teak one down pass irt aound"),
    writeln("sevett nyhree botltes of beerhonet wall"),
    writeln("sevyn etthree btotles of bee onrthe wall"),
    writeln("sevyn etthree btotles of beer"),
    writeln("take one down p ss aaitround"),
    writeln("setnevy two btotles of bee onrthe wall"),
    writeln("sete tynvwo bttoes lof beer onethw all"),
    writeln("sete tynvwo bttoes lof beer"),
    writeln("tkaoe ne down paus at iorsnd"),
    writeln("sete oynvne bttoes lof beer onethw all"),
    writeln("setenvno ye bootlets f blre en the woal"),
    writeln("setenvno ye bootlets f beer"),
    writeln("takno ee dwon pnuaait rossd"),
    writeln("sevteny bootlets f blre en the woal"),
    writeln("sevetny bos toetlf btereon lha we l"),
    writeln("sevetny bos toetlf beer"),
    writeln("takeon e down ptas iu arnsod"),
    writeln("sixtyin ne bos toetlf btereon lha we l"),
    writeln("siixyn tne bs tetloof b aerhw noet ell"),
    writeln("siixyn tne bs tetloof beer"),
    writeln("taoke ne down poasti aursnd"),
    writeln("stxgie yiht bs tetloof b aerhw noet ell"),
    writeln("sxyti eight beotlts of bw r oentee hall"),
    writeln("sxyti eight beotlts of beer"),
    writeln("t keaone down paios tsar und"),
    writeln("sxyti seven beotlts of bw r oentee hall"),
    writeln("sixty seven bottlos ef beern thelwaol"),
    writeln("sixty seven bottlos ef beer"),
    writeln("tnke oae dwon pass irnatou d"),
    writeln("sixtyis x bottlos ef beern thelwaol"),
    writeln("sxii ystx btooels tf beewhont l rael"),
    writeln("sxii ystx btooels tf beer"),
    writeln("tan eoke down pt niasaorusd"),
    writeln("svfiy tixe btooels tf beewhont l rael"),
    writeln("sxfty iive boltets of btor ne heweall"),
    writeln("sxfty iive boltets of beer"),
    writeln("t keaone down ptoa issar und"),
    writeln("sxfty iour boltets of btor ne heweall"),
    writeln("sixty four bottles of benoer the wall"),
    writeln("sixty four bottles of beer"),
    writeln("take one down pas sit around"),
    writeln("sixty three bottles of benoer the wall"),
    writeln("sitxh tyere botteos lf berto newhel a l"),
    writeln("sitxh tyere botteos lf beer"),
    writeln("tak enoe dwon pats si aornud"),
    writeln("sixt wtyo botteos lf berto newhel a l"),
    writeln("sy tiwtxo bletoos tf btlr w ehenoael"),
    writeln("sy tiwtxo bletoos tf beer"),
    writeln("t keaone down pnss iaoar utd"),
    writeln("sy tinoxe bletoos tf btlr w ehenoael"),
    writeln("sxity one btotles of bere hn toe wall"),
    writeln("sxity one btotles of beer"),
    writeln("take one down p ss itaaround"),
    writeln("sixty btotles of bere hn toe wall"),
    writeln("sixty bottles of beer on the wall"),
    writeln("sixty bottles of beer"),
    writeln("take one down pass it around"),
    writeln("fifty nine bottles of beer on the wall"),
    writeln("fifny tnie boeolts tf betl on ewe harl"),
    writeln("fifny tnie boeolts tf beer"),
    writeln("t knaoee dwon pasnti oar usd"),
    writeln("ftfiy eight boeolts tf betl on ewe harl"),
    writeln("ffite yhgit bottles of beerl no h ewatl"),
    writeln("ffite yhgit bottles of beer"),
    writeln("tekano e down pass itra nuod"),
    writeln("ffits yeven bottles of beerl no h ewatl"),
    writeln("fivty sefen botts elof b eraon the well"),
    writeln("fivty sefen botts elof beer"),
    writeln("take one down psas ut aroind"),
    writeln("fifts yix botts elof b eraon the well"),
    writeln("fsi yftix bs oelttof btwr oheea enll"),
    writeln("fsi yftix bs oelttof beer"),
    writeln("tk eaone down paos astur ind"),
    writeln("fyftf iive bs oelttof btwr oheea enll"),
    writeln("f ivyfifte bos lteotf breeatn ole w hl"),
    writeln("f ivyfifte bos lteotf beer"),
    writeln("tekn oae dwon pastausr noi d"),
    writeln("f iuyfoftr bos lteotf breeatn ole w hl"),
    writeln("ffiyt uofr bttoles of bot eenreh wall"),
    writeln("ffiyt uofr bttoles of beer"),
    writeln("tnae oke down patn ai srousd"),
    writeln("fit yfthere bttoles of bot eenreh wall"),
    writeln("fiyt fthree botelts of brh neetwe oall"),
    writeln("fiyt fthree botelts of beer"),
    writeln("t keaone down paao stisr und"),
    writeln("fit yftwo botelts of brh neetwe oall"),
    writeln("fifty two bottles of bthenw aoe rell"),
    writeln("fifty two bottles of beer"),
    writeln("toa ekne down ps us aoaritnd"),
    writeln("fifty one bottles of bthenw aoe rell"),
    writeln("fytnfo ie bltots eof b lreon h atweel"),
    writeln("fytnfo ie bltots eof beer"),
    writeln("taen koe dwon pasn rs aiotud"),
    writeln("ftify bltots eof b lreon h atweel"),
    writeln("fifty boteotls f bler oeetwa h nl"),
    writeln("fifty boteotls f beer"),
    writeln("to eakne down pa ssiuaor ntd"),
    writeln("fonin tyre boteotls f bler oeetwa h nl"),
    writeln("fty inorne btos letof baerho ntee wll"),
    writeln("fty inorne btos letof beer"),
    writeln("ta oekne down psos ar uaitnd"),
    writeln("f gyiertoht btos letof baerho ntee wll"),
    writeln("fgotyr ieht bts loetof be erohatn ew ll"),
    writeln("fgotyr ieht bts loetof beer"),
    writeln("teao kne down p a sausriotnd"),
    writeln("fvotyr esen bts loetof be erohatn ew ll"),
    writeln("fov yrseetn bs teltoof b onwrtleae eh l"),
    writeln("fov yrseetn bs teltoof beer"),
    writeln("t onakee dwon puanaiso r tsd"),
    writeln("fst yroix bs teltoof b onwrtleae eh l"),
    writeln("frotyis x btotlos ef bereon eht l awl"),
    writeln("frotyis x btotlos ef beer"),
    writeln("tkaneo e down pa a ntssriuod"),
    writeln("foyrtv ife btotlos ef bereon eht l awl"),
    writeln("f ftyvrioe betloos tf blwe on hetearl"),
    writeln("f ftyvrioe betloos tf beer"),
    writeln("ta eknoe dwon passrn aotuid"),
    writeln("f ftyuroor betloos tf blwe on hetearl"),
    writeln("fofryt our bs otlteof br w e aheenotll"),
    writeln("fofryt our bs otlteof beer"),
    writeln("tokea ne down pairo tsasu nd"),
    writeln("fyrtr thoee bs otlteof br w e aheenotll"),
    writeln("fheor rttye bottoels f beew tnho e rlal"),
    writeln("fheor rttye bottoels f beer"),
    writeln("tnkoe ae dwon ptsso uaarin d"),
    writeln("fortw yto bottoels f beew tnho e rlal"),
    writeln("f wtrotyo beos totlf b erlaw theeno l"),
    writeln("f wtrotyo beos totlf beer"),
    writeln("taoen ke down pans iruaot sd"),
    writeln("f norotye beos totlf b erlaw theeno l"),
    writeln("fon tyore booetls tf blwteon ree ahl"),
    writeln("fon tyore booetls tf beer"),
    writeln("takn oee dwon p stoinaas urd"),
    writeln("forty booetls tf blwteon ree ahl"),
    writeln("forty btotles of beer thwone all"),
    writeln("forty btotles of beer"),
    writeln("tak eone down pssa to ariund"),
    writeln("thtiny rine btotles of beer thwone all"),
    writeln("tihtrn niye btotlos ef b he enltrw eaol"),
    writeln("tihtrn niye btotlos ef beer"),
    writeln("ta eknoe dwon psai so artnud"),
    writeln("thyitr eihgt btotlos ef b he enltrw eaol"),
    writeln("thiery ihgtt betools tf b eo e wrhlntael"),
    writeln("thiery ihgtt betools tf beer"),
    writeln("teka one down pnisrsa ao utd"),
    writeln("thesry ievtn betools tf b eo e wrhlntael"),
    writeln("tehrty isevn bolttes of beolwnr the ael"),
    writeln("tehrty isevn bolttes of beer"),
    writeln("t kneoae dwon pss rot aniuad"),
    writeln("tiir tyshx bolttes of beolwnr the ael"),
    writeln("thrt yisix bettlos of brne ho twe eall"),
    writeln("thrt yisix bettlos of beer"),
    writeln("ta ekone down p aasi osrtund"),
    writeln("trihtf yive bettlos of brne ho twe eall"),
    writeln("tvirfyiht e bttoes olf bne ehera olwt l"),
    writeln("tvirfyiht e bttoes olf beer"),
    writeln("tkoa nee dwon pnusa tiao rsd"),
    writeln("tuirfyoht r bttoes olf bne ehera olwt l"),
    writeln("tuifoy rhtr bs oolettf bolt hwen e rael"),
    writeln("tuifoy rhtr bs oolettf beer"),
    writeln("taknoe e down psa s tnauirod"),
    writeln("tyrh eihtrte bs oolettf bolt hwen e rael"),
    writeln("t thtyrehire boles ttof b wree nthaleo l"),
    writeln("t thtyrehire boles ttof beer"),
    writeln("tkn aeoe dwon pota nsau srid"),
    writeln("t wtrithyo boles ttof b wree nthaleo l"),
    writeln("tihr yttwo bottels of beo wentrhe all"),
    writeln("tihr yttwo bottels of beer"),
    writeln("take one down paisots ar und"),
    writeln("tihr ytone bottels of beo wentrhe all"),
    writeln("t iytnhore botloes tf behe onwtle arl"),
    writeln("t iytnhore botloes tf beer"),
    writeln("tn keoae dwon parsnot asiu d"),
    writeln("tihtry botloes tf behe onwtle arl"),
    writeln("tthriy botelts of ber aw nlheeo tl"),
    writeln("tthriy botelts of beer"),
    writeln("t enaoke down pani ut rasosd"),
    writeln("tnwnine tye botelts of ber aw nlheeo tl"),
    writeln("tetnn yiwne btotoles f bewel n roe thal"),
    writeln("tetnn yiwne btotoles f beer"),
    writeln("tank oee dwon ptnsu asai ord"),
    writeln("twehey ntigt btotoles f bewel n roe thal"),
    writeln("tweity ngeht bs ottelof b rawon teeh ell"),
    writeln("tweity ngeht bs ottelof beer"),
    writeln("ta keone down par utsasiond"),
    writeln("tweety nvsen bs ottelof b rawon teeh ell"),
    writeln("tnteeyesw vn booels ttf b e rwoaete lnhl"),
    writeln("tnteeyesw vn booels ttf beer"),
    writeln("t keanoe dwon pst ia narsoud"),
    writeln("t weiyntsx booels ttf b e rwoaete lnhl"),
    writeln("tsywtn iex bts oeltof bhatnee r eow ll"),
    writeln("tsywtn iex bts oeltof beer"),
    writeln("taek one down pua snrsai otd"),
    writeln("tfnvtyewi e bts oeltof bhatnee r eow ll"),
    writeln("twefv inyte bltts ooef b e et enhlwarol"),
    writeln("twefv inyte bltts ooef beer"),
    writeln("t nkeoae dwon pr sunta sioad"),
    writeln("twefu onytr bltts ooef b e et enhlwarol"),
    writeln("toeftyn wur bltes toof b wr na theeeoll"),
    writeln("toeftyn wur bltes toof beer"),
    writeln("t oeakne down pis oaa trsund"),
    writeln("tnhety rwtee bltes toof b wr na theeeoll"),
    writeln("teyeh wttnre bttoels of bhnweal tro eel"),
    writeln("teyeh wttnre bttoels of beer"),
    writeln("toan kee dwon posn atair usd"),
    writeln("t ewwyttno bttoels of bhnweal tro eel"),
    writeln("twwytnte o bloottes f bo terwl ehaenl"),
    writeln("twwytnte o bloottes f beer"),
    writeln("taneok e down pn irtaa ssuod"),
    writeln("twnytnoe e bloottes f bo terwl ehaenl"),
    writeln("ttnen yowe botes tolf btrn ehleewao l"),
    writeln("ttnen yowe botes tolf beer"),
    writeln("tn eakoe dwon pas atn orsuid"),
    writeln("tentwy botes tolf btrn ehleewao l"),
    writeln("twenty bs ooelttf ba nlreo he twel"),
    writeln("twenty bs ooelttf beer"),
    writeln("taoe kne down paiasot sr und"),
    writeln("nieetnen bs ooelttf ba nlreo he twel"),
    writeln("nteeenin botles tof beheeal wtorn l"),
    writeln("nteeenin botles tof beer"),
    writeln("t neokae dwon pitra onassu d"),
    writeln("etehegin botles tof beheeal wtorn l"),
    writeln("etehiegn btolots ef blertno eehawl"),
    writeln("etehiegn btolots ef beer"),
    writeln("t neaoke down pn a iotarsusd"),
    writeln("sveneeetn btolots ef blertno eehawl"),
    writeln("svteeneen btes olotf b e lnheteoaw rl"),
    writeln("svteeneen btes olotf beer"),
    writeln("tknao ee dwon psoiusatn ard"),
    writeln("sxieten btes olotf b e lnheteoaw rl"),
    writeln("stxieen botelts of beel o ahnw ertl"),
    writeln("stxieen botelts of beer"),
    writeln("taoekn e down pu nsoaitrsa d"),
    writeln("ftfieen botelts of beel o ahnw ertl"),
    writeln("ffteien bltootes f benh elwro etal"),
    writeln("ffteien bltootes f beer"),
    writeln("tkena oe dwon p otsrainsaud"),
    writeln("fureoten bltootes f benh elwro etal"),
    writeln("feuorten bts etoolf br wteenlheo a l"),
    writeln("feuorten bts etoolf beer"),
    writeln("tokae ne down parosnsi uatd"),
    writeln("teihrten bts etoolf br wteenlheo a l"),
    writeln("ttreiehn bs oetoltf b lwe nt eoraehl"),
    writeln("ttreiehn bs oetoltf beer"),
    writeln("t eoknae dwon ptno iars usad"),
    writeln("tlevwe bs oetoltf b lwe nt eoraehl"),
    writeln("tewlve btoels tof b harwn teeeo ll"),
    writeln("tewlve btoels tof beer"),
    writeln("ten oake down pnro it uassad"),
    writeln("eelven btoels tof b harwn teeeo ll"),
    writeln("eelevn bs tlootef beaeh n tlerwol"),
    writeln("eelevn bs tlootef beer"),
    writeln("tk onaee dwon pnuarit o assd"),
    writeln("ten bs tlootef beaeh n tlerwol"),
    writeln("ten bloeots tf btwoeer lhnael"),
    writeln("ten bloeots tf beer"),
    writeln("taenko e down pt n rasaisuod"),
    writeln("nine bloeots tf btwoeer lhnael"),
    writeln("nnie boletts of btnr eewlo hael"),
    writeln("nnie boletts of beer"),
    writeln("te kanoe dwon p rtanao ssuid"),
    writeln("eihgt boletts of btnr eewlo hael"),
    writeln("egiht bltotoes f bte wral heo enl"),
    writeln("egiht bltotoes f beer"),
    writeln("to keane down purois taasnd"),
    writeln("sveen bltotoes f bte wral heo enl"),
    writeln("sveen bs ototelf boeneth lwaer l"),
    writeln("sveen bs ototelf beer"),
    writeln("tno keae dwon p tnauroaiss d"),
    writeln("six bs ototelf boeneth lwaer l"),
    writeln("six bos toeltf br nolwheeatel"),
    writeln("six bos toeltf beer"),
    writeln("taon eke down pa aiutr nossd"),
    writeln("five bos toeltf br nolwheeatel"),
    writeln("fvie bs letotof brtehnel woe a l"),
    writeln("fvie bs letotof beer"),
    writeln("t akonee dwon pti nsouaasrd"),
    writeln("fuor bs letotof brtehnel woe a l"),
    writeln("four botols tef b tenhra le eowl"),
    writeln("four botols tef beer"),
    writeln("tanoke e down pn aituaorss d"),
    writeln("terhe botols tef b tenhra le eowl"),
    writeln("tehre bs tloeotf bn elaheto werl"),
    writeln("tehre bs tloeotf beer"),
    writeln("tkan eoe dwon pstri aanosud"),
    writeln("two bs tloeotf bn elaheto werl"),
    writeln("two bttels oof blanehe eorwtl"),
    writeln("two bttels oof beer"),
    writeln("tak eone down pusosni ara td"),
    writeln("one bttel oof blanehe eorwtl"),
    writeln("one btleoto f behwlt e eorn al"),
    writeln("one btleoto f beer"),
    writeln("t nekoae dwon pusoirna ts ad"),
    writeln("no btleotos f behwlt e eorn al").
