:- initialization(main).
:- style_check(-singleton).

main :-
    writeln("99 bottles of beer on the wall"),
    writeln("99 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("98 bottles of beer on the wall"),
    writeln("98 bottles of beer on the wall"),
    writeln("98 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("97 bottles of beer on the wall"),
    writeln("97 bottles of beer on the wall"),
    writeln("97 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("96 bottles of beer on the wall"),
    writeln("96 bottles of beer on the wall"),
    writeln("96 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("95 bottles of beer on the wall"),
    writeln("95 bottles of beer on the wall"),
    writeln("95 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("94 bottles of beer on the wall"),
    writeln("94 bottles of beer on the wall"),
    writeln("94 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("93 bottles of beer on the wall"),
    writeln("93 bottles of beer on the wall"),
    writeln("93 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("92 bottles of beer on the wall"),
    writeln("92 bottles of beer on the wall"),
    writeln("92 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("91 bottles of beer on the wall"),
    writeln("91 bottles of beer on the wall"),
    writeln("91 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("90 bottles of beer on the wall"),
    writeln("90 bottles of beer on the wall"),
    writeln("90 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("89 bottles of beer on the wall"),
    writeln("89 bottles of beer on the wall"),
    writeln("89 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("88 bottles of beer on the wall"),
    writeln("88 bottles of beer on the wall"),
    writeln("88 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("87 bottles of beer on the wall"),
    writeln("87 bottles of beer on the wall"),
    writeln("87 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("86 bottles of beer on the wall"),
    writeln("86 bottles of beer on the wall"),
    writeln("86 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("85 bottles of beer on the wall"),
    writeln("85 bottles of beer on the wall"),
    writeln("85 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("84 bottles of beer on the wall"),
    writeln("84 bottles of beer on the wall"),
    writeln("84 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("83 bottles of beer on the wall"),
    writeln("83 bottles of beer on the wall"),
    writeln("83 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("82 bottles of beer on the wall"),
    writeln("82 bottles of beer on the wall"),
    writeln("82 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("81 bottles of beer on the wall"),
    writeln("81 bottles of beer on the wall"),
    writeln("81 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("80 bottles of beer on the wall"),
    writeln("80 bottles of beer on the wall"),
    writeln("80 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("79 bottles of beer on the wall"),
    writeln("79 bottles of beer on the wall"),
    writeln("79 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("78 bottles of beer on the wall"),
    writeln("78 bottles of beer on the wall"),
    writeln("78 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("77 bottles of beer on the wall"),
    writeln("77 bottles of beer on the wall"),
    writeln("77 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("76 bottles of beer on the wall"),
    writeln("76 bottles of beer on the wall"),
    writeln("76 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("75 bottles of beer on the wall"),
    writeln("75 bottles of beer on the wall"),
    writeln("75 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("74 bottles of beer on the wall"),
    writeln("74 bottles of beer on the wall"),
    writeln("74 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("73 bottles of beer on the wall"),
    writeln("73 bottles of beer on the wall"),
    writeln("73 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("72 bottles of beer on the wall"),
    writeln("72 bottles of beer on the wall"),
    writeln("72 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("71 bottles of beer on the wall"),
    writeln("71 bottles of beer on the wall"),
    writeln("71 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("70 bottles of beer on the wall"),
    writeln("70 bottles of beer on the wall"),
    writeln("70 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("69 bottles of beer on the wall"),
    writeln("69 bottles of beer on the wall"),
    writeln("69 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("68 bottles of beer on the wall"),
    writeln("68 bottles of beer on the wall"),
    writeln("68 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("67 bottles of beer on the wall"),
    writeln("67 bottles of beer on the wall"),
    writeln("67 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("66 bottles of beer on the wall"),
    writeln("66 bottles of beer on the wall"),
    writeln("66 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("65 bottles of beer on the wall"),
    writeln("65 bottles of beer on the wall"),
    writeln("65 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("64 bottles of beer on the wall"),
    writeln("64 bottles of beer on the wall"),
    writeln("64 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("63 bottles of beer on the wall"),
    writeln("63 bottles of beer on the wall"),
    writeln("63 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("62 bottles of beer on the wall"),
    writeln("62 bottles of beer on the wall"),
    writeln("62 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("61 bottles of beer on the wall"),
    writeln("61 bottles of beer on the wall"),
    writeln("61 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("60 bottles of beer on the wall"),
    writeln("60 bottles of beer on the wall"),
    writeln("60 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("59 bottles of beer on the wall"),
    writeln("59 bottles of beer on the wall"),
    writeln("59 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("58 bottles of beer on the wall"),
    writeln("58 bottles of beer on the wall"),
    writeln("58 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("57 bottles of beer on the wall"),
    writeln("57 bottles of beer on the wall"),
    writeln("57 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("56 bottles of beer on the wall"),
    writeln("56 bottles of beer on the wall"),
    writeln("56 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("55 bottles of beer on the wall"),
    writeln("55 bottles of beer on the wall"),
    writeln("55 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("54 bottles of beer on the wall"),
    writeln("54 bottles of beer on the wall"),
    writeln("54 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("53 bottles of beer on the wall"),
    writeln("53 bottles of beer on the wall"),
    writeln("53 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("52 bottles of beer on the wall"),
    writeln("52 bottles of beer on the wall"),
    writeln("52 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("51 bottles of beer on the wall"),
    writeln("51 bottles of beer on the wall"),
    writeln("51 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("50 bottles of beer on the wall"),
    writeln("50 bottles of beer on the wall"),
    writeln("50 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("49 bottles of beer on the wall"),
    writeln("49 bottles of beer on the wall"),
    writeln("49 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("48 bottles of beer on the wall"),
    writeln("48 bottles of beer on the wall"),
    writeln("48 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("47 bottles of beer on the wall"),
    writeln("47 bottles of beer on the wall"),
    writeln("47 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("46 bottles of beer on the wall"),
    writeln("46 bottles of beer on the wall"),
    writeln("46 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("45 bottles of beer on the wall"),
    writeln("45 bottles of beer on the wall"),
    writeln("45 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("44 bottles of beer on the wall"),
    writeln("44 bottles of beer on the wall"),
    writeln("44 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("43 bottles of beer on the wall"),
    writeln("43 bottles of beer on the wall"),
    writeln("43 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("42 bottles of beer on the wall"),
    writeln("42 bottles of beer on the wall"),
    writeln("42 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("41 bottles of beer on the wall"),
    writeln("41 bottles of beer on the wall"),
    writeln("41 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("40 bottles of beer on the wall"),
    writeln("40 bottles of beer on the wall"),
    writeln("40 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("39 bottles of beer on the wall"),
    writeln("39 bottles of beer on the wall"),
    writeln("39 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("38 bottles of beer on the wall"),
    writeln("38 bottles of beer on the wall"),
    writeln("38 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("37 bottles of beer on the wall"),
    writeln("37 bottles of beer on the wall"),
    writeln("37 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("36 bottles of beer on the wall"),
    writeln("36 bottles of beer on the wall"),
    writeln("36 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("35 bottles of beer on the wall"),
    writeln("35 bottles of beer on the wall"),
    writeln("35 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("34 bottles of beer on the wall"),
    writeln("34 bottles of beer on the wall"),
    writeln("34 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("33 bottles of beer on the wall"),
    writeln("33 bottles of beer on the wall"),
    writeln("33 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("32 bottles of beer on the wall"),
    writeln("32 bottles of beer on the wall"),
    writeln("32 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("31 bottles of beer on the wall"),
    writeln("31 bottles of beer on the wall"),
    writeln("31 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("30 bottles of beer on the wall"),
    writeln("30 bottles of beer on the wall"),
    writeln("30 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("29 bottles of beer on the wall"),
    writeln("29 bottles of beer on the wall"),
    writeln("29 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("28 bottles of beer on the wall"),
    writeln("28 bottles of beer on the wall"),
    writeln("28 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("27 bottles of beer on the wall"),
    writeln("27 bottles of beer on the wall"),
    writeln("27 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("26 bottles of beer on the wall"),
    writeln("26 bottles of beer on the wall"),
    writeln("26 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("25 bottles of beer on the wall"),
    writeln("25 bottles of beer on the wall"),
    writeln("25 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("24 bottles of beer on the wall"),
    writeln("24 bottles of beer on the wall"),
    writeln("24 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("23 bottles of beer on the wall"),
    writeln("23 bottles of beer on the wall"),
    writeln("23 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("22 bottles of beer on the wall"),
    writeln("22 bottles of beer on the wall"),
    writeln("22 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("21 bottles of beer on the wall"),
    writeln("21 bottles of beer on the wall"),
    writeln("21 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("20 bottles of beer on the wall"),
    writeln("20 bottles of beer on the wall"),
    writeln("20 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("19 bottles of beer on the wall"),
    writeln("19 bottles of beer on the wall"),
    writeln("19 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("18 bottles of beer on the wall"),
    writeln("18 bottles of beer on the wall"),
    writeln("18 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("17 bottles of beer on the wall"),
    writeln("17 bottles of beer on the wall"),
    writeln("17 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("16 bottles of beer on the wall"),
    writeln("16 bottles of beer on the wall"),
    writeln("16 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("15 bottles of beer on the wall"),
    writeln("15 bottles of beer on the wall"),
    writeln("15 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("14 bottles of beer on the wall"),
    writeln("14 bottles of beer on the wall"),
    writeln("14 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("13 bottles of beer on the wall"),
    writeln("13 bottles of beer on the wall"),
    writeln("13 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("12 bottles of beer on the wall"),
    writeln("12 bottles of beer on the wall"),
    writeln("12 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("11 bottles of beer on the wall"),
    writeln("11 bottles of beer on the wall"),
    writeln("11 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("10 bottles of beer on the wall"),
    writeln("10 bottles of beer on the wall"),
    writeln("10 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("9 bottles of beer on the wall"),
    writeln("9 bottles of beer on the wall"),
    writeln("9 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("8 bottles of beer on the wall"),
    writeln("8 bottles of beer on the wall"),
    writeln("8 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("7 bottles of beer on the wall"),
    writeln("7 bottles of beer on the wall"),
    writeln("7 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("6 bottles of beer on the wall"),
    writeln("6 bottles of beer on the wall"),
    writeln("6 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("5 bottles of beer on the wall"),
    writeln("5 bottles of beer on the wall"),
    writeln("5 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("4 bottles of beer on the wall"),
    writeln("4 bottles of beer on the wall"),
    writeln("4 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("3 bottles of beer on the wall"),
    writeln("3 bottles of beer on the wall"),
    writeln("3 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("2 bottles of beer on the wall"),
    writeln("2 bottles of beer on the wall"),
    writeln("2 bottles of beer"),
    writeln("Take one down, pass it around"),
    writeln("1 bottle of beer on the wall"),
    writeln("1 bottle of beer on the wall"),
    writeln("1 bottle of beer"),
    writeln("Take one down, pass it around"),
    writeln("No more bottles of beer on the wall").
