:- initialization(main).
:- style_check(-singleton).

main :-
    writeln("Avalanche of topplings:"),
    writeln(""),
    writeln("4 3 3 "),
    writeln("3 1 2 "),
    writeln("0 2 3 "),
    writeln(""),
    writeln("0 4 3 "),
    writeln("4 1 2 "),
    writeln("0 2 3 "),
    writeln(""),
    writeln("1 0 4 "),
    writeln("4 2 2 "),
    writeln("0 2 3 "),
    writeln(""),
    writeln("1 1 0 "),
    writeln("4 2 3 "),
    writeln("0 2 3 "),
    writeln(""),
    writeln("2 1 0 "),
    writeln("0 3 3 "),
    writeln("1 2 3 "),
    writeln(""),
    writeln("Commutative additions:"),
    writeln(""),
    writeln("1 2 0 "),
    writeln("2 1 1 "),
    writeln("0 1 3 "),
    writeln(""),
    writeln("plus"),
    writeln(""),
    writeln("2 1 3 "),
    writeln("1 0 1 "),
    writeln("0 1 0 "),
    writeln(""),
    writeln("equals"),
    writeln(""),
    writeln("3 3 3 "),
    writeln("3 1 2 "),
    writeln("0 2 3 "),
    writeln(""),
    writeln("and"),
    writeln(""),
    writeln("2 1 3 "),
    writeln("1 0 1 "),
    writeln("0 1 0 "),
    writeln(""),
    writeln("plus"),
    writeln(""),
    writeln("1 2 0 "),
    writeln("2 1 1 "),
    writeln("0 1 3 "),
    writeln(""),
    writeln("also equals"),
    writeln(""),
    writeln("3 3 3 "),
    writeln("3 1 2 "),
    writeln("0 2 3 "),
    writeln(""),
    writeln("Addition of identity sandpile:"),
    writeln(""),
    writeln("3 3 3 "),
    writeln("3 3 3 "),
    writeln("3 3 3 "),
    writeln(""),
    writeln("plus"),
    writeln(""),
    writeln("2 1 2 "),
    writeln("1 0 1 "),
    writeln("2 1 2 "),
    writeln(""),
    writeln("equals"),
    writeln(""),
    writeln("3 3 3 "),
    writeln("3 3 3 "),
    writeln("3 3 3 "),
    writeln(""),
    writeln("Addition of identities:"),
    writeln(""),
    writeln("2 1 2 "),
    writeln("1 0 1 "),
    writeln("2 1 2 "),
    writeln(""),
    writeln("plus"),
    writeln(""),
    writeln("2 1 2 "),
    writeln("1 0 1 "),
    writeln("2 1 2 "),
    writeln(""),
    writeln("equals"),
    writeln(""),
    writeln("2 1 2 "),
    writeln("1 0 1 "),
    writeln("2 1 2").
