:- initialization(main).
:- style_check(-singleton).

main :-
    writeln("____________________________________________________________"),
    writeln(""),
    writeln(""),
    writeln("         T     T             T T T T T   T       T T       T"),
    writeln(""),
    writeln(" T T T         T T T   T T         T       T     T T T T T  "),
    writeln(""),
    writeln("     T       T T     T T T T     T T     T T T   T     T T T"),
    writeln(""),
    writeln(" T T T T     T   T   T T   T   T T   T T T       T   T      "),
    writeln(""),
    writeln(" T   T     T     T                   T   T           T T T T"),
    writeln(""),
    writeln("   T   T     T   T T   T T   T T T         T T T     T     T"),
    writeln(""),
    writeln("       T T   T T     T T   T T T   T T     T T   T     T   T"),
    writeln(""),
    writeln("       T T T       T T   T T       T   T T     T T   T T   T"),
    writeln(""),
    writeln(" T   T         T     T   T     T T T   T T   T T T     T T T"),
    writeln(""),
    writeln(" T T T T   T     T T T     T T T   T T T T T     T T     T  "),
    writeln(""),
    writeln(" T T T   T T     T       T   T     T   T         T       T  "),
    writeln(""),
    writeln(" T T   T           T T T T   T   T     T T T T   T T T   T T"),
    writeln(""),
    writeln(" T       T   T       T T             T T T   T   T T T T T  "),
    writeln(""),
    writeln(" T   T T T T T T     T     T   T   T T T T   T T T T T   T T"),
    writeln(""),
    writeln("   T           T       T     T       T T T       T T T T T  "),
    writeln(""),
    writeln(" T   T   T     T   T     T         T T T     T T T   T T T T"),
    writeln(""),
    writeln(" T T T T T T   T T T T   T   T T T     T   T           T T  "),
    writeln(""),
    writeln("   T     T T T     T     T T T T T T   T     T T T T       T"),
    writeln(""),
    writeln("   T T   T     T   T T   T   T T T   T     T   T T T     T T"),
    writeln(""),
    writeln(" T T   T   T     T T   T   T   T     T T   T     T T   T T T"),
    writeln(""),
    writeln("____________________________________________________________"),
    writeln(""),
    writeln(""),
    writeln("   T     T     T             T T T T T   T       T T       T"),
    writeln(""),
    writeln(" T T T         T T T   T T         T       T     T T T T T  "),
    writeln(""),
    writeln("     T       T T     T T T T     T T     T T T   T     T T T"),
    writeln(""),
    writeln(" T T T T     T   T   T T   T   T T   T T T       T   T      "),
    writeln(""),
    writeln(" T   T     T     T                   T   T           T T T T"),
    writeln(""),
    writeln("   T   T     T   T T   T T   T T T         T T T     T     T"),
    writeln(""),
    writeln("       T T   T T     T T   T T T   T T     T T   T     T   T"),
    writeln(""),
    writeln("       T T T       T T   T T       T   T T     T T   T T   T"),
    writeln(""),
    writeln(" T   T         T     T   T     T T T   T T   T T T     T T T"),
    writeln(""),
    writeln(" T T T T   T     T T T     T T T   T T T T T     T T     T  "),
    writeln(""),
    writeln(" T T T   T T     T       T   T     T   T         T       T  "),
    writeln(""),
    writeln(" T T   T           T T T T   T   T     T T T T   T T T   T T"),
    writeln(""),
    writeln(" T       T   T       T T             T T T   T   T T T T T  "),
    writeln(""),
    writeln(" T   T T T T T T     T     T   T   T T T T   T T T T T   T T"),
    writeln(""),
    writeln("   T           T T     T     T       T T T       T T T T T  "),
    writeln(""),
    writeln(" T   T   T     T   T     T         T T T     T T T   T T T T"),
    writeln(""),
    writeln(" T T T T T T   T T T T   T   T T T     T   T           T T  "),
    writeln(""),
    writeln("   T     T T T     T     T T T T T T   T     T T T T       T"),
    writeln(""),
    writeln("   T T   T     T   T T   T   T T T   T     T   T T T     T T"),
    writeln(""),
    writeln(" T T   T   T     T T   T   T   T     T T   T     T T   T T T").
