// Generated by Mochi transpiler v0.10.33 on 2025-07-21 18:20:16 GMT+7
#include <iostream>
#include <string>
#include <sstream>
#include <iomanip>
bool boom(int a, int b) {
    std::cout << std::boolalpha << std::string("boom") << std::endl;
    return true;
}
int main() {
    std::cout << std::boolalpha << (false && boom(1, 2)) << std::endl;
    std::cout << std::boolalpha << (true || boom(1, 2)) << std::endl;
    return 0;
}
