// Generated by Mochi 0.10.32 on 2025-07-21 16:14 +0700
#include <stdio.h>
#include <string.h>
int x = 12;
int main(void) {
    const char *msg = (x > 10 ? "yes" : "no");
    puts(msg);
    return 0;
}
