// Generated by Mochi v0.10.33 on 2025-07-21 16:41:31 GMT+7
import scala.collection.mutable.{ArrayBuffer, Map}
object Main {
  def main(args: Array[String]): Unit = {
    val xs: ArrayBuffer[Int] = ArrayBuffer(1, 2, 3)
    val ys: ArrayBuffer[Any] = ({
      var _res = ArrayBuffer[Any]()
      for (x <- xs) {
        if (x % 2 == 1) {
          _res.append(x)
        }
      }
      _res
    })
    println(ys.contains(1))
    println(ys.contains(2))
    val m: Map[String, Int] = Map("a" -> 1)
    println(m.contains("a"))
    println(m.contains("b"))
    val s: String = "hello"
    println(s.contains("ell"))
    println(s.contains("foo"))
  }
}
