// Generated by Mochi 0.10.59 on 2025-08-07 10:17 +0700
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Numerics;
using System.Collections;

class Program {
    static bool seededNow = false;
    static long nowSeed = 0;
    static long _now() {
        if (!seededNow) {
            var s = Environment.GetEnvironmentVariable("MOCHI_NOW_SEED");
            if (long.TryParse(s, out var v)) {
                nowSeed = v;
                seededNow = true;
            }
        }
        if (seededNow) {
            nowSeed = unchecked(nowSeed * 1664525 + 1013904223);
            nowSeed %= 9223372036854775783L;
            if (nowSeed < 0) nowSeed += 9223372036854775783L;
            return nowSeed;
        }
        return DateTime.UtcNow.Ticks / 100;
    }
    static long _mem() {
        return GC.GetTotalAllocatedBytes(true);
    }
    static long _len(object v) {
        if (v is Array a) return a.Length;
        if (v is string s) return s.Length;
        if (v is System.Collections.ICollection c) return c.Count;
        return Convert.ToString(v).Length;
    }
    static long _mod(long a, long b) {
        if (b == 0) return 0;
        var r = a % b;
        if ((r < 0 && b > 0) || (r > 0 && b < 0)) r += b;
        return r;
    }
    static string _substr(string s, long start, long end) {
        if (start < 0) start = 0;
        if (end < 0) end = 0;
        if (start > s.Length) start = s.Length;
        if (end > s.Length) end = s.Length;
        if (start > end) start = end;
        return s.Substring((int)start, (int)(end - start));
    }
    static string _fmt(object v) {
        if (v is Array a) {
            var parts = new List<string>();
            foreach (var x in a) parts.Add(_fmt(x));
            return "[" + string.Join(", ", parts) + "]";
        }
        if (v is System.Collections.IDictionary d) {
            var keys = new List<string>();
            foreach (var k in d.Keys) keys.Add(k.ToString());
            keys.Sort();
            var parts = new List<string>();
            foreach (var k in keys) parts.Add(k + ":" + _fmt(d[k]));
            return "map[" + string.Join(", ", parts) + "]";
        }
        if (v is System.Collections.IEnumerable e && !(v is string)) {
            var parts = new List<string>();
            foreach (var x in e) parts.Add(_fmt(x));
            return string.Join(", ", parts);
        }
        if (v is string s) return "\"" + s.Replace("\"", "\\\"") + "\"";
        if (v is bool b) return b ? "true" : "false";
        return Convert.ToString(v);
    }
    static string _fmtStr(object v) {
        if (v is Array a) {
            var parts = new List<string>();
            foreach (var x in a) parts.Add(_fmtStr(x));
            return "[" + string.Join(" ", parts) + "]";
        }
        if (v is System.Collections.IDictionary d) {
            var keys = new List<string>();
            foreach (var k in d.Keys) keys.Add(k.ToString());
            keys.Sort();
            var parts = new List<string>();
            foreach (var k in keys) parts.Add(k + ":" + _fmtStr(d[k]));
            return "map[" + string.Join(" ", parts) + "]";
        }
        if (v is System.Collections.IEnumerable e && !(v is string)) {
            var parts = new List<string>();
            foreach (var x in e) parts.Add(_fmtStr(x));
            return string.Join(" ", parts);
        }
        if (v is string s) return "\"" + s.Replace("\"", "\\\"") + "\"";
        if (v is bool b) return b ? "true" : "false";
        return Convert.ToString(v);
    }
    public static string _fmtTop(object v) {
        if (v is Array a && a.Length > 0 && a.GetValue(0) is Array) {
            var parts = new List<string>();
            foreach (var x in a) parts.Add(_fmt(x));
            return string.Join(" ", parts);
        }
        if (v is string s) return s;
        return _fmt(v);
    }
    public static long[] prime_factors(long n_0) {
        if ((n_0 < 2)) {
            return new long[]{};
        };
        long num_1 = n_0;
        long i_2 = 2;
        long[] factors_3 = new long[]{};
        while (((i_2 * i_2) <= num_1)) {
            if ((_mod(num_1, i_2) == 0)) {
                factors_3 = (Enumerable.ToArray(Enumerable.Append<long>(factors_3, i_2)));
                num_1 = (num_1 / i_2);
            } else {
                i_2 = (i_2 + 1);
            }
        };
        if ((num_1 > 1)) {
            factors_3 = (Enumerable.ToArray(Enumerable.Append<long>(factors_3, num_1)));
        };
        return factors_3;
    }

    public static bool list_eq(long[] a_4, long[] b_5) {
        if ((a_4.Length != b_5.Length)) {
            return false;
        };
        long i_6 = 0;
        while ((i_6 < a_4.Length)) {
            if ((a_4[(int)(i_6)] != b_5[(int)(i_6)])) {
                return false;
            }
            i_6 = (i_6 + 1);
        };
        return true;
    }

    public static void test_prime_factors() {
        if ((!Program.list_eq(Program.prime_factors(0), new long[]{}))) {
            throw new Exception("prime_factors(0) failed");
        };
        if ((!Program.list_eq(Program.prime_factors(100), new long[]{2, 2, 5, 5}))) {
            throw new Exception("prime_factors(100) failed");
        };
        if ((!Program.list_eq(Program.prime_factors(2560), new long[]{2, 2, 2, 2, 2, 2, 2, 2, 2, 5}))) {
            throw new Exception("prime_factors(2560) failed");
        };
        if ((!Program.list_eq(Program.prime_factors(97), new long[]{97}))) {
            throw new Exception("prime_factors(97) failed");
        };
    }

    public static void main() {
        Program.test_prime_factors();
        Console.WriteLine(Program._fmtTop(_fmtStr(Program.prime_factors(100))));
        Console.WriteLine(Program._fmtTop(_fmtStr(Program.prime_factors(2560))));
        Console.WriteLine(Program._fmtTop(_fmtStr(Program.prime_factors(97))));
    }

    static void Main() {
        {
            var __memStart = _mem();
            var __start = _now();
            Program.main();
            var __end = _now();
            var __memEnd = _mem();
            var __dur = (__end - __start);
            if (__dur <= 0) __dur = 1;
            var __memDiff = __memEnd - __memStart;
            if (__memDiff <= 0) __memDiff = __memEnd;
            Console.WriteLine("{\"name\":\"main\",\"duration_us\":" + __dur + ",\"memory_bytes\":" + __memDiff + "}");
        }
    }
}
