// Generated by Mochi 0.10.32 on 2025-08-23 13:39 +0700
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <malloc.h>
#include <math.h>

size_t build_menu_len;
size_t sort_desc_len;

size_t append_len;
static char* str_concat(const char *a, const char *b) {
    size_t len1 = strlen(a);
    size_t len2 = strlen(b);
    char *res = malloc(len1 + len2 + 1);
    memcpy(res, a, len1);
    memcpy(res + len1, b, len2);
    res[len1 + len2] = 0;
    return res;
}

static char* str_float(double v) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%f", v);
    char *p = buf + strlen(buf) - 1;
    while (p > buf && *p == '0') *p-- = '\0';
    if (p > buf && *p == '.') *p = '\0';
    return strdup(buf);
}

#include <time.h>
static int seeded_now = 0;
static long long now_seed = 0;
static long long _now(void) {
    if (!seeded_now) {
        const char *s = getenv("MOCHI_NOW_SEED");
        if (s && *s) {
            now_seed = atoll(s);
            seeded_now = 1;
        }
    }
    if (seeded_now) {
        now_seed = (now_seed * 1664525 + 1013904223) % 2147483647;
        return now_seed;
    }
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return (long long)(ts.tv_sec * 1000000000LL + ts.tv_nsec);
}

static long long _mem(void) {
    long long size = 0, rss = 0;
    FILE *f = fopen("/proc/self/statm", "r");
    if (f) {
        if (fscanf(f, "%lld %lld", &size, &rss) != 2) rss = 0;
        fclose(f);
    }
    return rss * (long long)sysconf(_SC_PAGESIZE);
}

static void panic(const char *msg) {
    fputs(msg, stderr);
    fputc('\n', stderr);
    exit(1);
}

typedef struct Anon1 Anon1;
typedef struct GreedyResult GreedyResult;
typedef struct Thing Thing;

struct Anon1 {
    const char* __name;
    const char* name;
    double value;
    double weight;
};

struct GreedyResult {
    Thing *items;
    size_t items_len;
    double total_value;
};

struct Thing {
    const char* name;
    double value;
    double weight;
};

static Thing* list_append_Thing(Thing *arr, size_t *len, Thing val) {
    arr = realloc(arr, (*len + 1) * sizeof(Thing));
    arr[*len] = val;
    (*len)++;
    return arr;
}

const char* food_init[8] = {"Burger", "Pizza", "Coca Cola", "Rice", "Sambhar", "Chicken", "Fries", "Milk"};
const char* *food = food_init;
size_t food_len = 8;
double value_init[8] = {80.0, 100.0, 60.0, 70.0, 50.0, 110.0, 90.0, 60.0};
double *value = value_init;
size_t value_len = 8;
double weight_init[8] = {40.0, 60.0, 40.0, 70.0, 100.0, 85.0, 55.0, 70.0};
double *weight = weight_init;
size_t weight_len = 8;
Thing *foods = NULL;
size_t foods_len = 0;
GreedyResult res;

double get_value(Thing t);
double get_weight(Thing t);
const char* get_name(Thing t);
double value_weight(Thing t);
Thing * build_menu(const char* * names, size_t names_len, double * values, size_t values_len, double * weights, size_t weights_len);
Thing * sort_desc(Thing * items, size_t items_len, double(*key_func)(Thing));
GreedyResult greedy(Thing * items, size_t items_len, double max_cost, double(*key_func)(Thing));
const char* thing_to_string(Thing t);
const char* list_to_string(Thing * ts, size_t ts_len);
int main(void);

double get_value(Thing t) {
    return t.value;
}

double get_weight(Thing t) {
    return t.weight;
}

const char* get_name(Thing t) {
    return t.name;
}

double value_weight(Thing t) {
    return t.value / t.weight;
}

Thing * build_menu(const char* * names, size_t names_len, double * values, size_t values_len, double * weights, size_t weights_len) {
    Thing *menu = NULL;
    size_t menu_len = 0;
    long long i = 0LL;
    while (((i < values_len) && (i < names_len)) && (i < weights_len)) {
        menu = list_append_Thing(menu, &menu_len, (Thing){.name = names[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? names_len + _mochi_idx : _mochi_idx;})], .value = values[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? values_len + _mochi_idx : _mochi_idx;})], .weight = weights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? weights_len + _mochi_idx : _mochi_idx;})]});
        i = i + 1LL;
    }
    return build_menu_len = menu_len, menu;
}

Thing * sort_desc(Thing * items, size_t items_len, double(*key_func)(Thing)) {
    Thing *arr = NULL;
    size_t arr_len = 0;
    long long i = 0LL;
    while (i < items_len) {
        arr = list_append_Thing(arr, &arr_len, items[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? items_len + _mochi_idx : _mochi_idx;})]);
        i = i + 1LL;
    }
    long long j = 1LL;
    while (j < arr_len) {
        Thing key_item = arr[(int)({long long _mochi_idx = j; _mochi_idx < 0 ? arr_len + _mochi_idx : _mochi_idx;})];
        double key_val = key_func(key_item);
        long long k = j - 1LL;
        while ((k >= 0LL) && (key_func(arr[(int)({long long _mochi_idx = k; _mochi_idx < 0 ? arr_len + _mochi_idx : _mochi_idx;})]) < key_val)) {
            arr[(int)(k + 1LL)] = arr[(int)({long long _mochi_idx = k; _mochi_idx < 0 ? arr_len + _mochi_idx : _mochi_idx;})];
            k = k - 1LL;
        }
        arr[(int)(k + 1LL)] = key_item;
        j = j + 1LL;
    }
    return sort_desc_len = arr_len, arr;
}

GreedyResult greedy(Thing * items, size_t items_len, double max_cost, double(*key_func)(Thing)) {
    Thing *items_copy = sort_desc(items, items_len, key_func);
    size_t items_copy_len = sort_desc_len;
    Thing *result = NULL;
    size_t result_len = 0;
    double total_value = 0.0;
    double total_cost = 0.0;
    long long i = 0LL;
    while (i < items_copy_len) {
        Thing it = items_copy[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? items_copy_len + _mochi_idx : _mochi_idx;})];
        double w = get_weight(it);
        if ((total_cost + w) <= max_cost) {
            result = list_append_Thing(result, &result_len, it);
            total_cost = total_cost + w;
            total_value = total_value + get_value(it);
        }
        i = i + 1LL;
    }
    return (GreedyResult){.items = result, .items_len = result_len, .total_value = total_value};
}

const char* thing_to_string(Thing t) {
    return str_concat(str_concat(str_concat(str_concat(str_concat(str_concat("Thing(", t.name), ", "), str_float(t.value)), ", "), str_float(t.weight)), ")");
}

const char* list_to_string(Thing * ts, size_t ts_len) {
    const char* s = "[";
    long long i = 0LL;
    while (i < ts_len) {
        s = str_concat(s, thing_to_string(ts[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? ts_len + _mochi_idx : _mochi_idx;})]));
        if (i < (ts_len - 1LL)) {
            s = str_concat(s, ", ");
        }
        i = i + 1LL;
    }
    s = str_concat(s, "]");
    return s;
}

int main(void) {
    {
        long long __start = _now();
        foods = build_menu(food, food_len, value, value_len, weight, weight_len);
        foods_len = build_menu_len;
        puts(list_to_string(foods, foods_len));
        res = greedy(foods, foods_len, 500.0, get_value);
        puts(list_to_string(res.items, res.items_len));
        puts(str_float(res.total_value));
        long long __end = _now();
        long long __dur_us = (__end - __start) / 1000;
        long long __mem_bytes = _mem();
        printf("{\n  \"duration_us\": %-lld,\n  \"memory_bytes\": %-lld,\n  \"name\": \"main\"\n}\n", __dur_us, __mem_bytes);
    }
    return 0;
}
