-- Generated by Mochi v0.10.74 on 2025-08-26 14:25 GMT+7
function input()
  local line = io.read('*l')
  if line == nil then return '' end
  return line
end
local _nil = {}

local _now_seed = 0
local _now_seeded = false
do
  local s = os.getenv("MOCHI_NOW_SEED")
  if s and s ~= "" then
    local v = tonumber(s)
    if v then
      _now_seed = v
      _now_seeded = true
    end
  end
end
local function _now()
if _now_seeded then
  -- keep the seed within safe integer range for Lua (53 bits)
  _now_seed = (_now_seed * 1664525 + 1013904223) % 9007199254740991
  return _now_seed % 1000000000
end
return os.time() * 1000000000 + math.floor(os.clock() * 1000000000)
end

local function _len(v)
if type(v) == 'table' and v.items ~= nil then
  return #v.items
elseif type(v) == 'table' and (v[1] == nil or v[0] ~= nil) then
    local c = 0
    for k in pairs(v) do
      if k ~= '__name' and k ~= '__order' then
        c = c + 1
      end
    end
    return c
  elseif type(v) == 'string' then
      local l = utf8.len(v)
      if l then return l end
      return #v
    elseif type(v) == 'table' then
        return #v
      else
        return 0
      end
    end
    
    local function _split(s, sep)
    local t = {}
    local pattern = string.format("([^%s]+)", sep)
    string.gsub(s, pattern, function(c) t[#t+1] = c end)
    return t
  end
  
  local function _substring(s, i, j)
  i = i + 1
  if j == nil then j = #s end
  local si = utf8.offset(s, i)
  if not si then return '' end
  local sj = utf8.offset(s, j+1)
  if not sj then sj = -1 end
  return string.sub(s, si, sj-1)
end
do
  collectgarbage()
  local _bench_start_mem = collectgarbage('count') * 1024
  local _bench_start = os.clock()
  function split(s, sep)
    local parts = {}
    local cur = ""
    local i = 0
    while (i < _len(s)) do
      if (((_len(sep) > 0) and ((i + _len(sep)) <= _len(s))) and (_substring(s, i, (i + _len(sep))) == sep)) then
        parts = (function(lst, item)
        local res = {table.unpack(lst or {})}
        res[#res+1] = item
        return res
      end)(parts, cur)
      cur = ""
      i = (i + _len(sep))
    else
      cur = (cur .. string.sub(s, (i + 1), (i + 1)))
      i = (i + 1)
    end
  end
  parts = (function(lst, item)
  local res = {table.unpack(lst or {})}
  res[#res+1] = item
  return res
end)(parts, cur)
return parts
end
function precompute(limit)
  local sieve = {}
  for i = 0, (limit + 1) - 1 do
    sieve = (function(lst, item)
    local res = {table.unpack(lst or {})}
    res[#res+1] = item
    return res
  end)(sieve, true)
end
sieve[0 + 1] = false
sieve[1 + 1] = false
local p = 2
while ((p * p) <= limit) do
  if sieve[p + 1] then
    local j = (p * p)
    while (j <= limit) do
      sieve[j + 1] = false
      j = (j + p)
    end
  end
  p = (p + 1)
end
local primes = {}
for i = 2, (limit + 1) - 1 do
  if sieve[i + 1] then
    primes = (function(lst, item)
    local res = {table.unpack(lst or {})}
    res[#res+1] = item
    return res
  end)(primes, i)
end
end
return primes
end
primes = precompute(32000)
t = (function(v) if type(v)=='string' then v=tonumber(v) or 0 end if v >= 0 then return math.floor(v) else return math.ceil(v) end end)(input())
case_idx = 0
while (case_idx < t) do
  line = input()
  parts = split(line, " ")
  m = (function(v) if type(v)=='string' then v=tonumber(v) or 0 end if v >= 0 then return math.floor(v) else return math.ceil(v) end end)(parts[0 + 1])
  n = (function(v) if type(v)=='string' then v=tonumber(v) or 0 end if v >= 0 then return math.floor(v) else return math.ceil(v) end end)(parts[1 + 1])
  size = ((n - m) + 1)
  segment = {}
  for i = 0, size - 1 do
    segment = (function(lst, item)
    local res = {table.unpack(lst or {})}
    res[#res+1] = item
    return res
  end)(segment, true)
end
for _, p in ipairs(primes) do
  if ((p * p) > n) then
    break
  end
  start = (p * p)
  if (start < m) then
    rem = (m % p)
    if (rem == 0) then
      start = m
    else
      start = (m + (p - rem))
    end
  end
  j = start
  while (j <= n) do
    segment[(j - m) + 1] = false
    j = (tostring(j) .. tostring(p))
  end
end
if (m == 1) then
  segment[0 + 1] = false
end
i = 0
while (i < size) do
  if segment[i + 1] then
    print((i + m))
  end
  i = (i + 1)
end
if (case_idx < (t - 1)) then
  print("")
end
case_idx = (case_idx + 1)
end
local _bench_end = os.clock()
collectgarbage()
local _bench_end_mem = collectgarbage('count') * 1024
local _bench_duration_us = math.floor((_bench_end - _bench_start) * 1000000)
local _bench_mem = math.floor(math.max(0, _bench_end_mem - _bench_start_mem))
print('{\n  "duration_us": ' .. _bench_duration_us .. ',\n  "memory_bytes": ' .. _bench_mem .. ',\n  "name": "main"\n}')
end;
