// Generated by Mochi v0.10.63 on 2025-08-11 15:23:12 GMT+7
import scala.collection.mutable.{ArrayBuffer, Map}
import scala.math.BigInt
import scala.collection.immutable.ListMap
object Main {
  private var _nowSeed: Long = 0L
  private var _nowSeeded: Boolean = false
  private def _now(): Int = {
    if (!_nowSeeded) {
      sys.env.get("MOCHI_NOW_SEED").foreach { s =>
      try { _nowSeed = s.toInt; _nowSeeded = true } catch { case _ : NumberFormatException => () }
    }
  }
  if (_nowSeeded) {
    _nowSeed = (_nowSeed * 1664525 + 1013904223) % 2147483647
    _nowSeed.toInt
  } else {
    Math.abs((System.nanoTime() / 1000).toInt)
  }
}

def toJson(value: Any, indent: Int = 0): String = value match {
  case m: scala.collection.Map[_, _] =>
  val items = ListMap(m.toSeq.sortBy(_._1.toString): _*).toSeq.map{ case (k,v) => "  "*(indent+1)+"\""+k.toString+"\": "+toJson(v, indent+1) }
  "{\n"+items.mkString(",\n")+"\n"+"  "*indent+"}"
  case s: Seq[_] =>
  val items = s.map(x => "  "*(indent+1)+toJson(x, indent+1))
  "[\n"+items.mkString(",\n")+"\n"+"  "*indent+"]"
  case s: String => "\""+s+"\""
  case other => other.toString
}

def digits_fifth_powers_sum(number: BigInt): BigInt = {
  var total: BigInt = BigInt(0)
  var n: BigInt = number
  while (n > BigInt(0)) {
    val digit: BigInt = n % BigInt(10)
    total = total + DIGITS_FIFTH_POWER.lift((digit.toInt).toInt).getOrElse(null)
    n = n / BigInt(10)
  }
  return total
}

def solution(): BigInt = {
  var total: BigInt = BigInt(0)
  var num: BigInt = BigInt(1000)
  while (num < BigInt(1000000)) {
    if (num == digits_fifth_powers_sum(num)) {
      total = total + num
    }
    num = num + BigInt(1)
  }
  return total
}

val DIGITS_FIFTH_POWER: ArrayBuffer[BigInt] = ArrayBuffer(BigInt(0), BigInt(1), BigInt(32), BigInt(243), BigInt(1024), BigInt(3125), BigInt(7776), BigInt(16807), BigInt(32768), BigInt(59049))

def main(args: Array[String]): Unit = {
  {
    System.gc()
    val _startMem = Runtime.getRuntime.totalMemory() - Runtime.getRuntime.freeMemory()
    val _start = _now()
    println(solution())
    val _end = _now()
    System.gc()
    val _endMem = Runtime.getRuntime.totalMemory() - Runtime.getRuntime.freeMemory()
    val _durUs = (_end - _start) / 1000
    var _memDiff = _endMem - _startMem
    if (_memDiff <= 0) _memDiff = _endMem
    println(toJson(scala.collection.immutable.Map("duration_us" -> _durUs, "memory_bytes" -> _memDiff, "name" -> "main")))
  }
}
}
