// Generated by Mochi transpiler v0.10.59 on 2025-08-06 22:09:30 GMT+7
import Foundation
import Dispatch
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

let stdout = FileHandle.standardOutput
extension FileHandle {
    func write(_ string: String) {
        if let data = string.data(using: .utf8) {
            self.write(data)
        }
    }
}

func _p(_ v: Any?) -> String {
    if let val = v {
        if let d = val as? Double {
            if d.rounded(.towardZero) == d {
                return String(Int64(d))
            }
        }
        return String(describing: val)
    }
    return "<nil>"
}

extension Double { init(_ v: Any) { if let d = v as? Double { self = d } else if let i = v as? Int { self = Double(i) } else if let i = v as? Int64 { self = Double(i) } else if let s = v as? String { self = Double(s) ?? 0 } else { self = 0 } } }
var _nowSeed = 0
var _nowSeeded = false
func _now() -> Int {
    if !_nowSeeded {
        if let s = ProcessInfo.processInfo.environment["MOCHI_NOW_SEED"], let v = Int(s) {
            _nowSeed = v
            _nowSeeded = true
        }
    }
    if _nowSeeded {
        _nowSeed = (_nowSeed * 1664525 + 1013904223) % 2147483647
        return _nowSeed
    }
    return Int(DispatchTime.now().uptimeNanoseconds)
}
func _mem() -> Int {
    if let status = try? String(contentsOfFile: "/proc/self/status") {
        for line in status.split(separator: "\n") {
            if line.hasPrefix("VmRSS:") {
                let parts = line.split(whereSeparator: { $0 == " " || $0 == "\t" })
                if parts.count >= 2, let kb = Int(parts[1]) {
                    return kb * 1024
                }
            }
        }
    }
    return 0
}
do {
    let _benchMemStart = _mem()
    let _benchStart = _now()
    func panic(_ msg: String) {
        print(_p(msg))
    }
    func trim_spaces(_ s: String) -> String {
        var start: Int = 0
        var end: Int = (Int(((s).count)) &- 1)
        while ((start <= end) && (String(describing: String(Array(String(describing: (s as! String)))[start..<(start &+ 1)])) == " ")) {
            start = Int((start &+ 1))
        }
        while ((end >= start) && (String(describing: String(Array(String(describing: (s as! String)))[end..<(end &+ 1)])) == " ")) {
            end = Int((end &- 1))
        }
        if (start > end) {
            return ""
        }
        return String(describing: String(Array(String(describing: (s as! String)))[start..<(end &+ 1)]))
    }
    func char_to_digit(_ ch: String) -> Int {
        if (ch == "0") {
            return 0
        }
        if (ch == "1") {
            return 1
        }
        if (ch == "2") {
            return 2
        }
        if (ch == "3") {
            return 3
        }
        if (ch == "4") {
            return 4
        }
        if (ch == "5") {
            return 5
        }
        if (ch == "6") {
            return 6
        }
        if (ch == "7") {
            return 7
        }
        _ = fatalError("Non-octal value was passed to the function")
        return 0
    }
    func oct_to_decimal(_ oct_string: String) -> Int {
        var s: String = String(describing: trim_spaces((oct_string as! String)))
        if (Int(((s).count)) == 0) {
            _ = fatalError("Empty string was passed to the function")
            return 0
        }
        var is_negative: Bool = false
        if (String(describing: String(Array(String(describing: (s as! String)))[0..<1])) == "-") {
            is_negative = true
            s = String(describing: String(Array(String(describing: (s as! String)))[1..<Int(((s).count))]))
        }
        if (Int(((s).count)) == 0) {
            _ = fatalError("Non-octal value was passed to the function")
            return 0
        }
        var decimal_number: Int = 0
        var i: Int = 0
        while (i < Int(((s).count))) {
            let ch = String(describing: String(Array(String(describing: (s as! String)))[i..<(i &+ 1)]))
            let digit = Int(char_to_digit((ch as! String)))
            decimal_number = Int(((8 &* decimal_number) &+ digit))
            i = Int((i &+ 1))
        }
        if is_negative {
            decimal_number = Int(-decimal_number)
        }
        return decimal_number
    }
    func main() {
        print(_p(String(describing: Int(oct_to_decimal("1")))))
        print(_p(String(describing: Int(oct_to_decimal("-1")))))
        print(_p(String(describing: Int(oct_to_decimal("12")))))
        print(_p(String(describing: Int(oct_to_decimal(" 12   ")))))
        print(_p(String(describing: Int(oct_to_decimal("-45")))))
        print(_p(String(describing: Int(oct_to_decimal("0")))))
    }
    _ = main()
    let _benchEnd = _now()
    let _benchMemEnd = _mem()
    print("{\n  \"duration_us\": \((_benchEnd - _benchStart) / 1000),\n  \"memory_bytes\": \(_benchMemEnd - _benchMemStart),\n  \"name\": \"main\"\n}")
}
