// Generated by Mochi transpiler v0.10.59 on 2025-08-07 00:30:06 GMT+7
import Foundation
import Dispatch
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

let stdout = FileHandle.standardOutput
extension FileHandle {
    func write(_ string: String) {
        if let data = string.data(using: .utf8) {
            self.write(data)
        }
    }
}

func _p(_ v: Any?) -> String {
    if let val = v {
        if let d = val as? Double {
            if d.rounded(.towardZero) == d {
                return String(Int64(d))
            }
        }
        return String(describing: val)
    }
    return "<nil>"
}

extension Double { init(_ v: Any) { if let d = v as? Double { self = d } else if let i = v as? Int { self = Double(i) } else if let i = v as? Int64 { self = Double(i) } else if let s = v as? String { self = Double(s) ?? 0 } else { self = 0 } } }
var _nowSeed = 0
var _nowSeeded = false
func _now() -> Int {
    if !_nowSeeded {
        if let s = ProcessInfo.processInfo.environment["MOCHI_NOW_SEED"], let v = Int(s) {
            _nowSeed = v
            _nowSeeded = true
        }
    }
    if _nowSeeded {
        _nowSeed = (_nowSeed * 1664525 + 1013904223) % 2147483647
        return _nowSeed
    }
    return Int(DispatchTime.now().uptimeNanoseconds)
}
func _mem() -> Int {
    if let status = try? String(contentsOfFile: "/proc/self/status") {
        for line in status.split(separator: "\n") {
            if line.hasPrefix("VmRSS:") {
                let parts = line.split(whereSeparator: { $0 == " " || $0 == "\t" })
                if parts.count >= 2, let kb = Int(parts[1]) {
                    return kb * 1024
                }
            }
        }
    }
    return 0
}
func _append<T>(_ xs: [T], _ v: T) -> [T] {
    var out = xs
    out.append(v)
    return out
}
func _set<T>(_ xs: [T], _ idx: Int, _ v: T) -> [T] {
    var out = xs
    if idx < out.count {
        out[idx] = v
    } else {
        out.append(contentsOf: Array(repeating: v, count: idx - out.count + 1))
        out[idx] = v
    }
    return out
}
func _set<K: Hashable, V>(_ xs: [K: V], _ key: K, _ v: V) -> [K: V] {
    var out = xs
    out[key] = v
    return out
}
do {
    let _benchMemStart = _mem()
    let _benchStart = _now()
    func make_list(_ n: Int, _ value: Int) -> [Int?] {
        var res: [Int?] = ([] as! [Int?])
        var i: Int = 0
        while (i < n) {
            res = (_append(res, value) as! [Int?])
            i = Int((i &+ 1))
        }
        return res
    }
    func histogram_stretch(_ image: inout [[Int?]]) -> [[Int?]] {
        let height = Int(((image).count))
        let width = Int((((image[0] as! [Int?])).count))
        var hist: [Int?] = (make_list(256, 0) as! [Int?])
        var i: Int = 0
        while (i < height) {
            var j: Int = 0
            while (j < width) {
                let val = (image[i][j] as? Int ?? 0)
                hist = _set(hist, val, Int(((hist[val] as? Int ?? 0) &+ 1)))
                j = Int((j &+ 1))
            }
            i = Int((i &+ 1))
        }
        var mapping: [Int?] = (make_list(256, 0) as! [Int?])
        var cumulative: Int = 0
        let total = (height &* width)
        var h: Int = 0
        while (h < 256) {
            cumulative = Int((cumulative &+ (hist[h] as? Int ?? 0)))
            mapping = _set(mapping, h, Int((Int((255 &* cumulative)) / total)))
            h = Int((h &+ 1))
        }
        i = 0
        while (i < height) {
            var j: Int = 0
            while (j < width) {
                let val = (image[i][j] as? Int ?? 0)
                image[i][j] = (mapping[val] as? Int ?? 0)
                j = Int((j &+ 1))
            }
            i = Int((i &+ 1))
        }
        return image
    }
    func print_image(_ image: [[Int?]]) {
        var i: Int = 0
        while (i < Int(((image).count))) {
            print(_p("[" + (image[i] as! [Int?]).map{ if let s = $0 as? String { "\"" + s.replacingOccurrences(of: "\"", with: "\\\"") + "\"" } else { _p($0) } }.joined(separator: ", ") + "]"))
            i = Int((i &+ 1))
        }
    }
    var img: [[Int?]] = ([([52, 55, 61] as! [Int?]), ([59, 79, 61] as! [Int?]), ([85, 76, 62] as! [Int?])] as! [[Int?]])
    let result: [[Int?]] = (histogram_stretch(&img) as! [[Int?]])
    _ = print_image((result as! [[Int?]]))
    let _benchEnd = _now()
    let _benchMemEnd = _mem()
    print("{\n  \"duration_us\": \((_benchEnd - _benchStart) / 1000),\n  \"memory_bytes\": \(_benchMemEnd - _benchMemStart),\n  \"name\": \"main\"\n}")
}
