// Generated by Mochi 0.10.32 on 2025-08-13 07:12 +0700
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <malloc.h>


static char* str_int(long long v) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%lld", v);
    return strdup(buf);
}

static long long** list_append_intptr(long long **arr, size_t *len, long long *val) {
    arr = realloc(arr, (*len + 1) * sizeof(long long*));
    arr[*len] = val;
    (*len)++;
    return arr;
}

static size_t* list_append_szt(size_t *arr, size_t *len, size_t val) {
    arr = realloc(arr, (*len + 1) * sizeof(size_t));
    arr[*len] = val;
    (*len)++;
    return arr;
}

#include <time.h>
#include <stdlib.h>
static int seeded_now = 0;
static long long now_seed = 0;
static long long _now(void) {
    if (!seeded_now) {
        const char *s = getenv("MOCHI_NOW_SEED");
        if (s && *s) {
            now_seed = atoll(s);
            seeded_now = 1;
        }
    }
    if (seeded_now) {
        now_seed = (now_seed * 1664525 + 1013904223) % 2147483647;
        return now_seed;
    }
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return (long long)(ts.tv_sec * 1000000000LL + ts.tv_nsec);
}

static long long _mem(void) {
    long long size = 0, rss = 0;
    FILE *f = fopen("/proc/self/statm", "r");
    if (f) {
        if (fscanf(f, "%lld %lld", &size, &rss) != 2) rss = 0;
        fclose(f);
    }
    return rss * (long long)sysconf(_SC_PAGESIZE);
}

static void panic(const char *msg) {
    fputs(msg, stderr);
    fputc('\n', stderr);
    exit(1);
}

static long long* list_append_long_long(long long *arr, size_t *len, long long val) {
    arr = realloc(arr, (*len + 1) * sizeof(long long));
    arr[*len] = val;
    (*len)++;
    return arr;
}

static long long** list_append_long_longptr(long long **arr, size_t *len, long long *val) {
    arr = realloc(arr, (*len + 1) * sizeof(long long*));
    arr[*len] = val;
    (*len)++;
    return arr;
}

long long find_min(long long * numbers, size_t numbers_len);
int main(void);

long long find_min(long long * numbers, size_t numbers_len) {
    long long n = numbers_len;
    long long s = 0LL;
    long long idx = 0LL;
    while (idx < n) {
        s = s + numbers[(int)({long long _mochi_idx = idx; _mochi_idx < 0 ? numbers_len + _mochi_idx : _mochi_idx;})];
        idx = idx + 1LL;
    }
    long long **dp = NULL;
    size_t dp_len = 0;
    size_t *dp_lens = NULL;
    size_t dp_lens_len = 0;
    long long i = 0LL;
    while (i <= n) {
        long long *row = NULL;
        size_t row_len = 0;
        long long j = 0LL;
        while (j <= s) {
            row = list_append_long_long(row, &row_len, 0LL);
            j = j + 1LL;
        }
        dp = list_append_long_longptr(dp, &dp_len, row);
        dp_lens = list_append_szt(dp_lens, &dp_lens_len, row_len);
        i = i + 1LL;
    }
    i = 0LL;
    while (i <= n) {
        dp[(int)(i)][(int)(0LL)] = 1LL;
        i = i + 1LL;
    }
    long long j = 1LL;
    while (j <= s) {
        dp[(int)(0LL)][(int)(j)] = 0LL;
        j = j + 1LL;
    }
    i = 1LL;
    while (i <= n) {
        j = 1LL;
        while (j <= s) {
            dp[(int)(i)][(int)(j)] = dp[(int)({long long _mochi_idx = i - 1LL; _mochi_idx < 0 ? dp_len + _mochi_idx : _mochi_idx;})][(int)({long long _mochi_idx = j; _mochi_idx < 0 ? dp_lens[i - 1LL] + _mochi_idx : _mochi_idx;})];
            if (numbers[(int)({long long _mochi_idx = i - 1LL; _mochi_idx < 0 ? numbers_len + _mochi_idx : _mochi_idx;})] <= j) {
                if (dp[(int)({long long _mochi_idx = i - 1LL; _mochi_idx < 0 ? dp_len + _mochi_idx : _mochi_idx;})][(int)({long long _mochi_idx = j - numbers[(int)({long long _mochi_idx = i - 1LL; _mochi_idx < 0 ? numbers_len + _mochi_idx : _mochi_idx;})]; _mochi_idx < 0 ? dp_lens[i - 1LL] + _mochi_idx : _mochi_idx;})]) {
                    dp[(int)(i)][(int)(j)] = 1LL;
                }
            }
            j = j + 1LL;
        }
        i = i + 1LL;
    }
    long long diff = 0LL;
    j = s / 2LL;
    while (j >= 0LL) {
        if (dp[(int)({long long _mochi_idx = n; _mochi_idx < 0 ? dp_len + _mochi_idx : _mochi_idx;})][(int)({long long _mochi_idx = j; _mochi_idx < 0 ? dp_lens[n] + _mochi_idx : _mochi_idx;})]) {
            diff = s - (2LL * j);
            break;
        }
        j = j - 1LL;
    }
    return diff;
}

int main(void) {
    {
        long long __start = _now();
        puts(str_int(find_min(({long long *tmp = malloc(5 * sizeof(long long)); tmp[0] = 1LL; tmp[1] = 2LL; tmp[2] = 3LL; tmp[3] = 4LL; tmp[4] = 5LL; tmp;}), 5)));
        puts(str_int(find_min(({long long *tmp = malloc(5 * sizeof(long long)); tmp[0] = 5LL; tmp[1] = 5LL; tmp[2] = 5LL; tmp[3] = 5LL; tmp[4] = 5LL; tmp;}), 5)));
        puts(str_int(find_min(({long long *tmp = malloc(4 * sizeof(long long)); tmp[0] = 5LL; tmp[1] = 5LL; tmp[2] = 5LL; tmp[3] = 5LL; tmp;}), 4)));
        puts(str_int(find_min(({long long *tmp = malloc(1 * sizeof(long long)); tmp[0] = 3LL; tmp;}), 1)));
        puts(str_int(find_min(NULL, 0)));
        puts(str_int(find_min(({long long *tmp = malloc(4 * sizeof(long long)); tmp[0] = 1LL; tmp[1] = 2LL; tmp[2] = 3LL; tmp[3] = 4LL; tmp;}), 4)));
        puts(str_int(find_min(({long long *tmp = malloc(4 * sizeof(long long)); tmp[0] = 0LL; tmp[1] = 0LL; tmp[2] = 0LL; tmp[3] = 0LL; tmp;}), 4)));
        puts(str_int(find_min(({double *tmp = malloc(4 * sizeof(double)); tmp[0] = -1.0; tmp[1] = -5.0; tmp[2] = 5LL; tmp[3] = 1LL; tmp;}), 4)));
        puts(str_int(find_min(({long long *tmp = malloc(5 * sizeof(long long)); tmp[0] = 9LL; tmp[1] = 9LL; tmp[2] = 9LL; tmp[3] = 9LL; tmp[4] = 9LL; tmp;}), 5)));
        puts(str_int(find_min(({long long *tmp = malloc(4 * sizeof(long long)); tmp[0] = 1LL; tmp[1] = 5LL; tmp[2] = 10LL; tmp[3] = 3LL; tmp;}), 4)));
        puts(str_int(find_min(({double *tmp = malloc(3 * sizeof(double)); tmp[0] = -1.0; tmp[1] = 0LL; tmp[2] = 1LL; tmp;}), 3)));
        puts(str_int(find_min(({long long *tmp = malloc(10 * sizeof(long long)); tmp[0] = 10LL; tmp[1] = 9LL; tmp[2] = 8LL; tmp[3] = 7LL; tmp[4] = 6LL; tmp[5] = 5LL; tmp[6] = 4LL; tmp[7] = 3LL; tmp[8] = 2LL; tmp[9] = 1LL; tmp;}), 10)));
        long long __end = _now();
        long long __dur_us = (__end - __start) / 1000;
        long long __mem_bytes = _mem();
        printf("{\n  \"duration_us\": %-lld,\n  \"memory_bytes\": %-lld,\n  \"name\": \"main\"\n}\n", __dur_us, __mem_bytes);
    }
    return 0;
}
