// Generated by Mochi 0.10.32 on 2025-08-13 15:57 +0700
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

size_t make_list_len;

static char* str_int(long long v) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%lld", v);
    return strdup(buf);
}

static void panic(const char *msg) {
    fputs(msg, stderr);
    fputc('\n', stderr);
    exit(1);
}

static long long* list_append_long_long(long long *arr, size_t *len, long long val) {
    arr = realloc(arr, (*len + 1) * sizeof(long long));
    arr[*len] = val;
    (*len)++;
    return arr;
}

long long * make_list(long long len, long long value);
long long trapped_rainwater(long long * heights, size_t heights_len);
int main(void);

long long * make_list(long long len, long long value) {
    long long *arr = NULL;
    size_t arr_len = 0;
    long long i = 0LL;
    while (i < len) {
        arr = list_append_long_long(arr, &arr_len, value);
        i = i + 1LL;
    }
    return make_list_len = arr_len, arr;
}

long long trapped_rainwater(long long * heights, size_t heights_len) {
    if (heights_len == 0LL) {
        return 0LL;
    }
    long long i = 0LL;
    while (i < heights_len) {
        if (heights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})] < 0LL) {
            panic("No height can be negative");
        }
        i = i + 1LL;
    }
    long long length = heights_len;
    long long *left_max = make_list(length, 0LL);
    size_t left_max_len = make_list_len;
    left_max[(int)(0LL)] = heights[(int)({long long _mochi_idx = 0LL; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})];
    i = 1LL;
    while (i < length) {
        if (heights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})] > left_max[(int)({long long _mochi_idx = i - 1LL; _mochi_idx < 0 ? left_max_len + _mochi_idx : _mochi_idx;})]) {
            left_max[(int)(i)] = heights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})];
        } else {
            left_max[(int)(i)] = left_max[(int)({long long _mochi_idx = i - 1LL; _mochi_idx < 0 ? left_max_len + _mochi_idx : _mochi_idx;})];
        }
        i = i + 1LL;
    }
    long long *right_max = make_list(length, 0LL);
    size_t right_max_len = make_list_len;
    long long last = length - 1LL;
    right_max[(int)(last)] = heights[(int)({long long _mochi_idx = last; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})];
    i = last - 1LL;
    while (i >= 0LL) {
        if (heights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})] > right_max[(int)({long long _mochi_idx = i + 1LL; _mochi_idx < 0 ? right_max_len + _mochi_idx : _mochi_idx;})]) {
            right_max[(int)(i)] = heights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})];
        } else {
            right_max[(int)(i)] = right_max[(int)({long long _mochi_idx = i + 1LL; _mochi_idx < 0 ? right_max_len + _mochi_idx : _mochi_idx;})];
        }
        i = i - 1LL;
    }
    long long total = 0LL;
    i = 0LL;
    while (i < length) {
        long long left = left_max[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? left_max_len + _mochi_idx : _mochi_idx;})];
        long long right = right_max[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? right_max_len + _mochi_idx : _mochi_idx;})];
        long long smaller = (left < right ? left : right);
        total = total + (smaller - heights[(int)({long long _mochi_idx = i; _mochi_idx < 0 ? heights_len + _mochi_idx : _mochi_idx;})]);
        i = i + 1LL;
    }
    return total;
}

int main(void) {
    puts(str_int(trapped_rainwater(({long long *tmp = malloc(12 * sizeof(long long)); tmp[0] = 0LL; tmp[1] = 1LL; tmp[2] = 0LL; tmp[3] = 2LL; tmp[4] = 1LL; tmp[5] = 0LL; tmp[6] = 1LL; tmp[7] = 3LL; tmp[8] = 2LL; tmp[9] = 1LL; tmp[10] = 2LL; tmp[11] = 1LL; tmp;}), 12)));
    puts(str_int(trapped_rainwater(({long long *tmp = malloc(6 * sizeof(long long)); tmp[0] = 7LL; tmp[1] = 1LL; tmp[2] = 5LL; tmp[3] = 3LL; tmp[4] = 6LL; tmp[5] = 4LL; tmp;}), 6)));
    return 0;
}
