;; Generated on 2025-07-25 10:01 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start3 (now)
)
)
 (begin (define door 1)
 (define incrementer 0)
 (call/cc (lambda (break2)
 (letrec ((loop1 (lambda (current)
 (if (< current 101)
 (begin (begin (let ((line (string-append (string-append "Door " (to-str current)
)
 " ")
)
)
 (begin (if (equal? current door)
 (begin (set! line (string-append line "Open")
)
 (set! incrementer (+ incrementer 1)
)
 (set! door (+ (+ door (* 2 incrementer)
)
 1)
)
)
 (begin (set! line (string-append line "Closed")
)
)
)
 (display (to-str line)
)
 (newline)
)
)
)
 (loop1 (+ current 1)
)
)
 (quote nil)
)
)
)
)
 (loop1 1)
)
)
)
 (let ((end4 (now)
)
)
 (let ((dur5 (quotient (- end4 start3)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur5)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
