;; Generated on 2025-07-25 08:58 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (* (current-seconds) 1000000000)))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start19 (now)
)
)
 (begin (define (fields s)
 (call/cc (lambda (ret1)
 (let ((words (list)
)
)
 (begin (let ((cur "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (let ((ch (substring s i (+ i 1)
)
)
)
 (begin (if (or (or (string=? ch " ")
 (string=? ch "\n")
)
 (string=? ch "\t")
)
 (begin (if (> (cond ((string? cur)
 (string-length cur)
)
 ((hash-table? cur)
 (hash-table-size cur)
)
 (else (length cur)
)
)
 0)
 (begin (set! words (append words (list cur)
)
)
 (set! cur "")
)
 (quote nil)
)
)
 (begin (set! cur (string-append cur ch)
)
)
)
 (set! i (+ i 1)
)
)
)
 (loop2)
)
 (quote nil)
)
)
)
)
 (loop2)
)
)
)
 (if (> (cond ((string? cur)
 (string-length cur)
)
 ((hash-table? cur)
 (hash-table-size cur)
)
 (else (length cur)
)
)
 0)
 (begin (set! words (append words (list cur)
)
)
)
 (quote nil)
)
 (ret1 words)
)
)
)
)
)
)
)
)
)
 (define (takeRunes s n)
 (call/cc (lambda (ret4)
 (let ((idx 0)
)
 (begin (let ((count 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< idx (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (if (equal? count n)
 (begin (ret4 (substring s 0 idx)
)
)
 (quote nil)
)
 (set! idx (+ idx 1)
)
 (set! count (+ count 1)
)
 (loop5)
)
 (quote nil)
)
)
)
)
 (loop5)
)
)
)
 (ret4 s)
)
)
)
)
)
)
)
 (define (distinct xs)
 (call/cc (lambda (ret7)
 (let ((m (alist->hash-table (list)
)
)
)
 (begin (let ((out (list)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (< i (cond ((string? xs)
 (string-length xs)
)
 ((hash-table? xs)
 (hash-table-size xs)
)
 (else (length xs)
)
)
)
 (begin (let ((x (list-ref xs i)
)
)
 (begin (if (not (cond ((string? m)
 (if (string-contains m x)
 #t #f)
)
 ((hash-table? m)
 (if (hash-table-exists? m x)
 #t #f)
)
 (else (if (member x m)
 #t #f)
)
)
)
 (begin (hash-table-set! m x #t)
 (set! out (append out (list x)
)
)
)
 (quote nil)
)
 (set! i (+ i 1)
)
)
)
 (loop8)
)
 (quote nil)
)
)
)
)
 (loop8)
)
)
)
 (ret7 out)
)
)
)
)
)
)
)
)
)
 (define (abbrevLen words)
 (call/cc (lambda (ret10)
 (let ((size (cond ((string? words)
 (string-length words)
)
 ((hash-table? words)
 (hash-table-size words)
)
 (else (length words)
)
)
)
)
 (begin (let ((l 1)
)
 (begin (call/cc (lambda (break12)
 (letrec ((loop11 (lambda ()
 (if #t (begin (let ((abbrs (list)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break14)
 (letrec ((loop13 (lambda ()
 (if (< i size)
 (begin (set! abbrs (append abbrs (list (takeRunes (list-ref words i)
 l)
)
)
)
 (set! i (+ i 1)
)
 (loop13)
)
 (quote nil)
)
)
)
)
 (loop13)
)
)
)
 (if (equal? (cond ((string? (distinct abbrs)
)
 (string-length (distinct abbrs)
)
)
 ((hash-table? (distinct abbrs)
)
 (hash-table-size (distinct abbrs)
)
)
 (else (length (distinct abbrs)
)
)
)
 size)
 (begin (ret10 l)
)
 (quote nil)
)
 (set! l (+ l 1)
)
)
)
)
)
 (loop11)
)
 (quote nil)
)
)
)
)
 (loop11)
)
)
)
 (ret10 0)
)
)
)
)
)
)
)
 (define (pad2 n)
 (call/cc (lambda (ret15)
 (let ((s (to-str n)
)
)
 (begin (if (< (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 2)
 (begin (ret15 (string-append " " s)
)
)
 (quote nil)
)
 (ret15 s)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret16)
 (let ((lines (list "Sunday Monday Tuesday Wednesday Thursday Friday Saturday" "Sondag Maandag Dinsdag Woensdag Donderdag Vrydag Saterdag" "E_djelë E_hënë E_martë E_mërkurë E_enjte E_premte E_shtunë" "Ehud Segno Maksegno Erob Hamus Arbe Kedame" "Al_Ahad Al_Ithinin Al_Tholatha'a Al_Arbia'a Al_Kamis Al_Gomia'a Al_Sabit" "Guiragui Yergou_shapti Yerek_shapti Tchorek_shapti Hink_shapti Ourpat Shapat" "domingu llunes martes miércoles xueves vienres sábadu" "Bazar_gÜnÜ Birinci_gÜn Çkinci_gÜn ÜçÜncÜ_gÜn DÖrdÜncÜ_gÜn Bes,inci_gÜn Altòncò_gÜn" "Igande Astelehen Astearte Asteazken Ostegun Ostiral Larunbat" "Robi_bar Shom_bar Mongal_bar Budhh_bar BRihashpati_bar Shukro_bar Shoni_bar" "Nedjelja Ponedeljak Utorak Srijeda Cxetvrtak Petak Subota" "Disul Dilun Dimeurzh Dimerc'her Diriaou Digwener Disadorn" "nedelia ponedelnik vtornik sriada chetvartak petak sabota" "sing_kei_yaht sing_kei_yat sing_kei_yee sing_kei_saam sing_kei_sie sing_kei_ng sing_kei_luk" "Diumenge Dilluns Dimarts Dimecres Dijous Divendres Dissabte" "Dzeenkk-eh Dzeehn_kk-ehreh Dzeehn_kk-ehreh_nah_kay_dzeeneh Tah_neesee_dzeehn_neh Deehn_ghee_dzee-neh Tl-oowey_tts-el_dehlee Dzeentt-ahzee" "dy_Sul dy_Lun dy_Meurth dy_Mergher dy_You dy_Gwener dy_Sadorn" "Dimanch Lendi Madi Mèkredi Jedi Vandredi Samdi" "nedjelja ponedjeljak utorak srijeda cxetvrtak petak subota" "nede^le ponde^lí úterÿ str^eda c^tvrtek pátek sobota" "Sondee Mondee Tiisiday Walansedee TOOsedee Feraadee Satadee" "s0ndag mandag tirsdag onsdag torsdag fredag l0rdag" "zondag maandag dinsdag woensdag donderdag vrijdag zaterdag" "Diman^co Lundo Mardo Merkredo ^Jaùdo Vendredo Sabato" "pÜhapäev esmaspäev teisipäev kolmapäev neljapäev reede laupäev" "Diu_prima Diu_sequima Diu_tritima Diu_quartima Diu_quintima Diu_sextima Diu_sabbata" "sunnudagur mánadagur tÿsdaguy mikudagur hósdagur friggjadagur leygardagur" "Yek_Sham'beh Do_Sham'beh Seh_Sham'beh Cha'har_Sham'beh Panj_Sham'beh Jom'eh Sham'beh" "sunnuntai maanantai tiistai keskiviiko torsktai perjantai lauantai" "dimanche lundi mardi mercredi jeudi vendredi samedi" "Snein Moandei Tiisdei Woansdei Tonersdei Freed Sneon" "Domingo Segunda_feira Martes Mércores Joves Venres Sábado" "k'vira orshabati samshabati otkhshabati khutshabati p'arask'evi shabati" "Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Samstag" "Kiriaki' Defte'ra Tri'ti Teta'rti Pe'mpti Paraskebi' Sa'bato" "ravivaar somvaar mangalvaar budhvaar guruvaar shukravaar shanivaar" "pópule pó`akahi pó`alua pó`akolu pó`ahá pó`alima pó`aono" "Yom_rishon Yom_sheni Yom_shlishi Yom_revi'i Yom_chamishi Yom_shishi Shabat" "ravivara somavar mangalavar budhavara brahaspativar shukravara shanivar" "vasárnap hétfö kedd szerda csütörtök péntek szombat" "Sunnudagur Mánudagur ╞riδjudagur Miδvikudagar Fimmtudagur FÖstudagur Laugardagur" "sundio lundio mardio merkurdio jovdio venerdio saturdio" "Minggu Senin Selasa Rabu Kamis Jumat Sabtu" "Dominica Lunedi Martedi Mercuridi Jovedi Venerdi Sabbato" "Dé_Domhnaigh Dé_Luain Dé_Máirt Dé_Ceadaoin Dé_ardaoin Dé_hAoine Dé_Sathairn" "domenica lunedí martedí mercoledí giovedí venerdí sabato" "Nichiyou_bi Getzuyou_bi Kayou_bi Suiyou_bi Mokuyou_bi Kin'you_bi Doyou_bi" "Il-yo-il Wol-yo-il Hwa-yo-il Su-yo-il Mok-yo-il Kum-yo-il To-yo-il" "Dies_Dominica Dies_Lunæ Dies_Martis Dies_Mercurii Dies_Iovis Dies_Veneris Dies_Saturni" "sve-tdien pirmdien otrdien tresvdien ceturtdien piektdien sestdien" "Sekmadienis Pirmadienis Antradienis Trec^iadienis Ketvirtadienis Penktadienis S^es^tadienis" "Wangu Kazooba Walumbe Mukasa Kiwanuka Nnagawonye Wamunyi" "xing-_qi-_rì xing-_qi-_yi-. xing-_qi-_èr xing-_qi-_san-. xing-_qi-_sì xing-_qi-_wuv. xing-_qi-_liù" "Jedoonee Jelune Jemayrt Jecrean Jardaim Jeheiney Jesam" "Jabot Manre Juje Wonje Taije Balaire Jarere" "geminrongo minòmishi mártes mièrkoles misheushi bèrnashi mishábaro" "Ahad Isnin Selasa Rabu Khamis Jumaat Sabtu" "sφndag mandag tirsdag onsdag torsdag fredag lφrdag" "lo_dimenge lo_diluns lo_dimarç lo_dimèrcres lo_dijòus lo_divendres lo_dissabte" "djadomingo djaluna djamars djarason djaweps djabièrna djasabra" "Niedziela Poniedzial/ek Wtorek S,roda Czwartek Pia,tek Sobota" "Domingo segunda-feire terça-feire quarta-feire quinta-feire sexta-feira såbado" "Domingo Lunes martes Miercoles Jueves Viernes Sabado" "Duminicª Luni Mart'i Miercuri Joi Vineri Sâmbªtª" "voskresenie ponedelnik vtornik sreda chetverg pyatnitsa subbota" "Sunday Di-luain Di-màirt Di-ciadain Di-ardaoin Di-haoine Di-sathurne" "nedjelja ponedjeljak utorak sreda cxetvrtak petak subota" "Sontaha Mmantaha Labobedi Laboraro Labone Labohlano Moqebelo" "Iridha- Sandhudha- Anga.haruwa-dha- Badha-dha- Brahaspa.thindha- Sikura-dha- Sena.sura-dha-" "nedel^a pondelok utorok streda s^tvrtok piatok sobota" "Nedelja Ponedeljek Torek Sreda Cxetrtek Petek Sobota" "domingo lunes martes miércoles jueves viernes sábado" "sonde mundey tude-wroko dride-wroko fode-wroko freyda Saturday" "Jumapili Jumatatu Jumanne Jumatano Alhamisi Ijumaa Jumamosi" "söndag måndag tisdag onsdag torsdag fredag lordag" "Linggo Lunes Martes Miyerkoles Huwebes Biyernes Sabado" "Lé-pài-jít Pài-it Pài-jï Pài-sañ Pài-sì Pài-gÖ. Pài-lák" "wan-ar-tit wan-tjan wan-ang-kaan wan-phoet wan-pha-ru-hat-sa-boh-die wan-sook wan-sao" "Tshipi Mosupologo Labobedi Laboraro Labone Labotlhano Matlhatso" "Pazar Pazartesi Sali Çar,samba Per,sembe Cuma Cumartesi" "nedilya ponedilok vivtorok sereda chetver pyatnytsya subota" "Chu?_Nhâ.t Thú*_Hai Thú*_Ba Thú*_Tu* Thú*_Na'm Thú*_Sáu Thú*_Ba?y" "dydd_Sul dyds_Llun dydd_Mawrth dyds_Mercher dydd_Iau dydd_Gwener dyds_Sadwrn" "Dibeer Altine Talaata Allarba Al_xebes Aljuma Gaaw" "iCawa uMvulo uLwesibini uLwesithathu uLuwesine uLwesihlanu uMgqibelo" "zuntik montik dinstik mitvokh donershtik fraytik shabes" "iSonto uMsombuluko uLwesibili uLwesithathu uLwesine uLwesihlanu uMgqibelo" "Dies_Dominica Dies_Lunæ Dies_Martis Dies_Mercurii Dies_Iovis Dies_Veneris Dies_Saturni" "Bazar_gÜnÜ Bazar_ærtæsi Çærs,ænbæ_axs,amò Çærs,ænbæ_gÜnÜ CÜmæ_axs,amò CÜmæ_gÜnÜ CÜmæ_Senbæ" "Sun Moon Mars Mercury Jove Venus Saturn" "zondag maandag dinsdag woensdag donderdag vrijdag zaterdag" "KoseEraa GyoOraa BenEraa Kuoraa YOwaaraa FeEraa Memenaa" "Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Sonnabend" "Domingo Luns Terza_feira Corta_feira Xoves Venres Sábado" "Dies_Solis Dies_Lunae Dies_Martis Dies_Mercurii Dies_Iovis Dies_Veneris Dies_Sabbatum" "xing-_qi-_tiàn xing-_qi-_yi-. xing-_qi-_èr xing-_qi-_san-. xing-_qi-_sì xing-_qi-_wuv. xing-_qi-_liù" "djadomingu djaluna djamars djarason djaweps djabièrnè djasabra" "Killachau Atichau Quoyllurchau Illapachau Chaskachau Kuychichau Intichau")
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break18)
 (letrec ((loop17 (lambda ()
 (if (< i (cond ((string? lines)
 (string-length lines)
)
 ((hash-table? lines)
 (hash-table-size lines)
)
 (else (length lines)
)
)
)
 (begin (let ((words (fields (list-ref lines i)
)
)
)
 (begin (let ((l (abbrevLen words)
)
)
 (begin (display (to-str (string-append (string-append (pad2 l)
 "  ")
 (list-ref lines i)
)
)
)
 (newline)
 (set! i (+ i 1)
)
)
)
)
)
 (loop17)
)
 (quote nil)
)
)
)
)
 (loop17)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end20 (now)
)
)
 (let ((dur21 (quotient (- end20 start19)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur21)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
