;; Generated on 2025-07-25 08:58 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (* (current-seconds) 1000000000)))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start7 (now)
)
)
 (begin (define (pfacSum i)
 (call/cc (lambda (ret1)
 (let ((sum 0)
)
 (begin (let ((p 1)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (<= p (quotient i 2)
)
 (begin (if (equal? (modulo i p)
 0)
 (begin (set! sum (+ sum p)
)
)
 (quote nil)
)
 (set! p (+ p 1)
)
 (loop2)
)
 (quote nil)
)
)
)
)
 (loop2)
)
)
)
 (ret1 sum)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret4)
 (let ((d 0)
)
 (begin (let ((a 0)
)
 (begin (let ((pnum 0)
)
 (begin (let ((i 1)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (<= i 20000)
 (begin (let ((j (pfacSum i)
)
)
 (begin (if (< j i)
 (begin (set! d (+ d 1)
)
)
 (quote nil)
)
 (if (equal? j i)
 (begin (set! pnum (+ pnum 1)
)
)
 (quote nil)
)
 (if (> j i)
 (begin (set! a (+ a 1)
)
)
 (quote nil)
)
 (set! i (+ i 1)
)
)
)
 (loop5)
)
 (quote nil)
)
)
)
)
 (loop5)
)
)
)
 (display (to-str (string-append (string-append "There are " (to-str d)
)
 " deficient numbers between 1 and 20000")
)
)
 (newline)
 (display (to-str (string-append (string-append "There are " (to-str a)
)
 " abundant numbers  between 1 and 20000")
)
)
 (newline)
 (display (to-str (string-append (string-append "There are " (to-str pnum)
)
 " perfect numbers between 1 and 20000")
)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end8 (now)
)
)
 (let ((dur9 (quotient (- end8 start7)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur9)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
