;; Generated on 2025-07-25 19:44 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start6 (now)
)
)
 (begin (define (pow base exp)
 (call/cc (lambda (ret1)
 (let ((result 1)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i exp)
 (begin (set! result (* result base)
)
 (set! i (+ i 1)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 result)
)
)
)
)
)
)
)
 (define (ackermann2 m n)
 (call/cc (lambda (ret4)
 (begin (if (equal? m 0)
 (begin (ret4 (+ n 1)
)
)
 (quote ()
)
)
 (if (equal? m 1)
 (begin (ret4 (+ n 2)
)
)
 (quote ()
)
)
 (if (equal? m 2)
 (begin (ret4 (+ (* 2 n)
 3)
)
)
 (quote ()
)
)
 (if (equal? m 3)
 (begin (ret4 (- (* 8 (pow 2 n)
)
 3)
)
)
 (quote ()
)
)
 (if (equal? n 0)
 (begin (ret4 (ackermann2 (- m 1)
 1)
)
)
 (quote ()
)
)
 (ret4 (ackermann2 (- m 1)
 (ackermann2 m (- n 1)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret5)
 (begin (display (to-str (string-append "A(0, 0)
 = " (to-str (ackermann2 0 0)
)
)
)
)
 (newline)
 (display (to-str (string-append "A(1, 2)
 = " (to-str (ackermann2 1 2)
)
)
)
)
 (newline)
 (display (to-str (string-append "A(2, 4)
 = " (to-str (ackermann2 2 4)
)
)
)
)
 (newline)
 (display (to-str (string-append "A(3, 4)
 = " (to-str (ackermann2 3 4)
)
)
)
)
 (newline)
)
)
)
)
 (main)
 (let ((end7 (now)
)
)
 (let ((dur8 (quotient (- end7 start6)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur8)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
