;; Generated on 2025-07-25 20:10 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start5 (now)
)
)
 (begin (define (search_user directory username)
 (call/cc (lambda (ret1)
 (ret1 (hash-table-ref/default directory username (quote ()
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret2)
 (let ((client (alist->hash-table (list (cons "Base" "dc=example,dc=com")
 (cons "Host" "ldap.example.com")
 (cons "Port" 389)
 (cons "GroupFilter" "(memberUid=%s)
")
)
)
)
)
 (begin (let ((directory (alist->hash-table (list (cons "username" (list "admins" "users")
)
 (cons "john" (list "users")
)
)
)
)
)
 (begin (let ((groups (search_user directory "username")
)
)
 (begin (if (> (cond ((string? groups)
 (string-length groups)
)
 ((hash-table? groups)
 (hash-table-size groups)
)
 (else (length groups)
)
)
 0)
 (begin (let ((out "Groups: [")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (< i (cond ((string? groups)
 (string-length groups)
)
 ((hash-table? groups)
 (hash-table-size groups)
)
 (else (length groups)
)
)
)
 (begin (set! out (string-append (string-append (string-append out "\"")
 (cond ((string? groups)
 (string-ref groups i)
)
 ((hash-table? groups)
 (hash-table-ref groups i)
)
 (else (list-ref groups i)
)
)
)
 "\"")
)
 (if (< i (- (cond ((string? groups)
 (string-length groups)
)
 ((hash-table? groups)
 (hash-table-size groups)
)
 (else (length groups)
)
)
 1)
)
 (begin (set! out (string-append out ", ")
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (set! out (string-append out "]")
)
 (display (to-str out)
)
 (newline)
)
)
)
)
)
 (begin (display (to-str "User not found")
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end6 (now)
)
)
 (let ((dur7 (quotient (- end6 start5)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur7)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
