;; Generated on 2025-07-25 20:10 +0700
(import (only (scheme base) call/cc when list-ref list-set! list))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(let ((start3 (now)
)
)
 (begin (define (connect client)
 (call/cc (lambda (ret1)
 (ret1 (and (not (string=? (hash-table-ref client "Host")
 "")
)
 (> (hash-table-ref client "Port")
 0)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret2)
 (let ((client (alist->hash-table (list (cons "Base" "dc=example,dc=com")
 (cons "Host" "ldap.example.com")
 (cons "Port" 389)
 (cons "UseSSL" #f)
 (cons "BindDN" "uid=readonlyuser,ou=People,dc=example,dc=com")
 (cons "BindPassword" "readonlypassword")
 (cons "UserFilter" "(uid=%s)
")
 (cons "GroupFilter" "(memberUid=%s)
")
 (cons "Attributes" (list "givenName" "sn" "mail" "uid")
)
)
)
)
)
 (begin (if (connect client)
 (begin (display (to-str (string-append "Connected to " (hash-table-ref client "Host")
)
)
)
 (newline)
)
 (begin (display (to-str "Failed to connect")
)
 (newline)
)
)
)
)
)
)
)
 (main)
 (let ((end4 (now)
)
)
 (let ((dur5 (quotient (- end4 start3)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur5)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
