;; Generated on 2025-07-26 21:31 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start4 (now)
)
)
 (begin (define (angleDiff b1 b2)
 (call/cc (lambda (ret1)
 (let ((d (- b2 b1)
)
)
 (begin (if (_lt d (- 0 180.0)
)
 (begin (ret1 (+ d 360.0)
)
)
 (quote ()
)
)
 (if (> d 180.0)
 (begin (ret1 (- d 360.0)
)
)
 (quote ()
)
)
 (ret1 d)
)
)
)
)
)
 (define testCases (_list (_list 20.0 45.0)
 (_list (- 0 45.0)
 45.0)
 (_list (- 0 85.0)
 90.0)
 (_list (- 0 95.0)
 90.0)
 (_list (- 0 45.0)
 125.0)
 (_list (- 0 45.0)
 145.0)
 (_list 29.4803 (- 0 88.6381)
)
 (_list (- 0 78.3251)
 (- 0 159.036)
)
)
)
 (call/cc (lambda (break3)
 (letrec ((loop2 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((tc (car xs)
)
)
 (begin (display (to-str (angleDiff (cond ((string? tc)
 (substring tc 0 (+ 0 1)
)
)
 ((hash-table? tc)
 (hash-table-ref tc 0)
)
 (else (list-ref tc 0)
)
)
 (cond ((string? tc)
 (substring tc 1 (+ 1 1)
)
)
 ((hash-table? tc)
 (hash-table-ref tc 1)
)
 (else (list-ref tc 1)
)
)
)
)
)
 (newline)
)
)
 (loop2 (cdr xs)
)
)
)
)
)
)
 (loop2 testCases)
)
)
)
 (let ((end5 (now)
)
)
 (let ((dur6 (quotient (- end5 start4)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur6)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
