;; Generated on 2025-07-26 21:32 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start7 (now)
)
)
 (begin (define (fib n)
 (call/cc (lambda (ret1)
 (begin (if (< n 2)
 (begin (ret1 n)
)
 (quote ()
)
)
 (let ((a 0)
)
 (begin (let ((b 1)
)
 (begin (let ((i 1)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i n)
 (begin (let ((t (+ a b)
)
)
 (begin (set! a b)
 (set! b t)
 (set! i (+ i 1)
)
)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 b)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret4)
 (call/cc (lambda (break6)
 (letrec ((loop5 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((i (car xs)
)
)
 (begin (if (_lt i 0)
 (begin (display (to-str (string-append (string-append "fib(" (to-str i)
)
 ")
 returned error: negative n is forbidden")
)
)
 (newline)
)
 (begin (display (to-str (string-append (string-append (string-append "fib(" (to-str i)
)
 ")
 = ")
 (to-str (fib i)
)
)
)
)
 (newline)
)
)
)
)
 (loop5 (cdr xs)
)
)
)
)
)
)
 (loop5 (_list (- 1)
 0 1 2 3 4 5 6 7 8 9 10)
)
)
)
)
)
)
)
 (main)
 (let ((end8 (now)
)
)
 (let ((dur9 (quotient (- end8 start7)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur9)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
