;; Generated on 2025-07-26 21:34 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start10 (now)
)
)
 (begin (define (abs x)
 (call/cc (lambda (ret1)
 (begin (if (< x 0.0)
 (begin (ret1 (- x)
)
)
 (quote ()
)
)
 (ret1 x)
)
)
)
)
 (define (maxf a b)
 (call/cc (lambda (ret2)
 (begin (if (> a b)
 (begin (ret2 a)
)
 (quote ()
)
)
 (ret2 b)
)
)
)
)
 (define (isClose a b)
 (call/cc (lambda (ret3)
 (let ((relTol 1e-09)
)
 (begin (let ((t (abs (- a b)
)
)
)
 (begin (let ((u (* relTol (maxf (abs a)
 (abs b)
)
)
)
)
 (begin (ret3 (_le t u)
)
)
)
)
)
)
)
)
)
)
 (define (sqrtApprox x)
 (call/cc (lambda (ret4)
 (let ((guess x)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i 10)
 (begin (set! guess (/ (+ guess (/ x guess)
)
 2.0)
)
 (set! i (+ i 1)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret4 guess)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret7)
 (let ((root2 (sqrtApprox 2.0)
)
)
 (begin (let ((pairs (_list (_list 1.0000000000000002e+14 1.0000000000000002e+14)
 (_list 100.01 100.011)
 (_list (/ 1.0000000000000002e+13 10000.0)
 1.0000000000000001e+09)
 (_list 0.001 0.0010000001)
 (_list 1.01e-22 0.0)
 (_list (* root2 root2)
 2.0)
 (_list (* (- root2)
 root2)
 (- 2.0)
)
 (_list 100000000000000000.0 100000000000000000.0)
 (_list 3.141592653589793 3.141592653589793)
)
)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((pair (car xs)
)
)
 (begin (let ((a (cond ((string? pair)
 (substring pair 0 (+ 0 1)
)
)
 ((hash-table? pair)
 (hash-table-ref pair 0)
)
 (else (list-ref pair 0)
)
)
)
)
 (begin (let ((b (cond ((string? pair)
 (substring pair 1 (+ 1 1)
)
)
 ((hash-table? pair)
 (hash-table-ref pair 1)
)
 (else (list-ref pair 1)
)
)
)
)
 (begin (let ((s (if (isClose a b)
 "≈" "≉")
)
)
 (begin (display (to-str (string-append (string-append (string-append (string-append (to-str a)
 " ")
 s)
 " ")
 (to-str b)
)
)
)
 (newline)
)
)
)
)
)
)
)
)
 (loop8 (cdr xs)
)
)
)
)
)
)
 (loop8 pairs)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end11 (now)
)
)
 (let ((dur12 (quotient (- end11 start10)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur12)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
