;; Generated on 2025-07-26 21:43 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start3 (now)
)
)
 (begin (define (main)
 (call/cc (lambda (ret1)
 (let ((a 12)
)
 (begin (let ((b 8)
)
 (begin (display (to-str (string-append (string-append (string-append (string-append (to-str a)
 " + ")
 (to-str b)
)
 " = ")
 (to-str (+ a b)
)
)
)
)
 (newline)
 (display (to-str (string-append (string-append (string-append (string-append (to-str a)
 " - ")
 (to-str b)
)
 " = ")
 (to-str (- a b)
)
)
)
)
 (newline)
 (display (to-str (string-append (string-append (string-append (string-append (to-str a)
 " * ")
 (to-str b)
)
 " = ")
 (to-str (* a b)
)
)
)
)
 (newline)
 (display (to-str (string-append (string-append (string-append (string-append (to-str a)
 " / ")
 (to-str b)
)
 " = ")
 (to-str (let ((v2 (quotient a b)
)
)
 (cond ((string? v2)
 (inexact->exact (string->number v2)
)
)
 ((boolean? v2)
 (if v2 1 0)
)
 (else (inexact->exact v2)
)
)
)
)
)
)
)
 (newline)
 (display (to-str (string-append (string-append (string-append (string-append (to-str a)
 " % ")
 (to-str b)
)
 " = ")
 (to-str (modulo a b)
)
)
)
)
 (newline)
)
)
)
)
)
)
)
 (main)
 (let ((end4 (now)
)
)
 (let ((dur5 (quotient (- end4 start3)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur5)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
