;; Generated on 2025-07-26 21:42 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start7 (now)
)
)
 (begin (define (add a b)
 (call/cc (lambda (ret1)
 (ret1 (alist->hash-table (_list (cons "re" (+ (hash-table-ref a "re")
 (hash-table-ref b "re")
)
)
 (cons "im" (+ (hash-table-ref a "im")
 (hash-table-ref b "im")
)
)
)
)
)
)
)
)
 (define (mul a b)
 (call/cc (lambda (ret2)
 (ret2 (alist->hash-table (_list (cons "re" (- (* (hash-table-ref a "re")
 (hash-table-ref b "re")
)
 (* (hash-table-ref a "im")
 (hash-table-ref b "im")
)
)
)
 (cons "im" (+ (* (hash-table-ref a "re")
 (hash-table-ref b "im")
)
 (* (hash-table-ref a "im")
 (hash-table-ref b "re")
)
)
)
)
)
)
)
)
)
 (define (neg a)
 (call/cc (lambda (ret3)
 (ret3 (alist->hash-table (_list (cons "re" (- (hash-table-ref a "re")
)
)
 (cons "im" (- (hash-table-ref a "im")
)
)
)
)
)
)
)
)
 (define (inv a)
 (call/cc (lambda (ret4)
 (let ((denom (+ (* (hash-table-ref a "re")
 (hash-table-ref a "re")
)
 (* (hash-table-ref a "im")
 (hash-table-ref a "im")
)
)
)
)
 (begin (ret4 (alist->hash-table (_list (cons "re" (/ (hash-table-ref a "re")
 denom)
)
 (cons "im" (/ (- (hash-table-ref a "im")
)
 denom)
)
)
)
)
)
)
)
)
)
 (define (conj a)
 (call/cc (lambda (ret5)
 (ret5 (alist->hash-table (_list (cons "re" (hash-table-ref a "re")
)
 (cons "im" (- (hash-table-ref a "im")
)
)
)
)
)
)
)
)
 (define (cstr a)
 (call/cc (lambda (ret6)
 (let ((s (string-append "(" (to-str (hash-table-ref a "re")
)
)
)
)
 (begin (if (>= (hash-table-ref a "im")
 0)
 (begin (set! s (string-append (string-append (string-append s "+")
 (to-str (hash-table-ref a "im")
)
)
 "i)
")
)
)
 (begin (set! s (string-append (string-append s (to-str (hash-table-ref a "im")
)
)
 "i)
")
)
)
)
 (ret6 s)
)
)
)
)
)
 (define a (alist->hash-table (_list (cons "re" 1.0)
 (cons "im" 1.0)
)
)
)
 (define b (alist->hash-table (_list (cons "re" 3.14159)
 (cons "im" 1.25)
)
)
)
 (display (to-str (string-append "a:       " (cstr a)
)
)
)
 (newline)
 (display (to-str (string-append "b:       " (cstr b)
)
)
)
 (newline)
 (display (to-str (string-append "a + b:   " (cstr (add a b)
)
)
)
)
 (newline)
 (display (to-str (string-append "a * b:   " (cstr (mul a b)
)
)
)
)
 (newline)
 (display (to-str (string-append "-a:      " (cstr (neg a)
)
)
)
)
 (newline)
 (display (to-str (string-append "1 / a:   " (cstr (inv a)
)
)
)
)
 (newline)
 (display (to-str (string-append "a̅:       " (cstr (conj a)
)
)
)
)
 (newline)
 (let ((end8 (now)
)
)
 (let ((dur9 (quotient (- end8 start7)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur9)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
