;; Generated on 2025-07-26 21:52 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start11 (now)
)
)
 (begin (define (concatInts a b)
 (call/cc (lambda (ret1)
 (let ((out (_list)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((v (car xs)
)
)
 (begin (set! out (append out (_list v)
)
)
)
)
 (loop2 (cdr xs)
)
)
)
)
)
)
 (loop2 a)
)
)
)
 (call/cc (lambda (break5)
 (letrec ((loop4 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((v (car xs)
)
)
 (begin (set! out (append out (_list v)
)
)
)
)
 (loop4 (cdr xs)
)
)
)
)
)
)
 (loop4 b)
)
)
)
 (ret1 out)
)
)
)
)
)
 (define (concatAny a b)
 (call/cc (lambda (ret6)
 (let ((out (_list)
)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((v (car xs)
)
)
 (begin (set! out (append out (_list v)
)
)
)
)
 (loop7 (cdr xs)
)
)
)
)
)
)
 (loop7 a)
)
)
)
 (call/cc (lambda (break10)
 (letrec ((loop9 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((v (car xs)
)
)
 (begin (set! out (append out (_list v)
)
)
)
)
 (loop9 (cdr xs)
)
)
)
)
)
)
 (loop9 b)
)
)
)
 (ret6 out)
)
)
)
)
)
 (define a (_list 1 2 3)
)
 (define b (_list 7 12 60)
)
 (display (to-str (to-str (concatInts a b)
)
)
)
 (newline)
 (define i (_list 1 2 3)
)
 (define j (_list "Crosby" "Stills" "Nash" "Young")
)
 (display (to-str (to-str (concatAny i j)
)
)
)
 (newline)
 (define l (_list 1 2 3)
)
 (define m (_list 7 12 60)
)
 (display (to-str (to-str (concatInts l m)
)
)
)
 (newline)
 (let ((end12 (now)
)
)
 (let ((dur13 (quotient (- end12 start11)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur13)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
