;; Generated on 2025-07-26 21:54 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start5 (now)
)
)
 (begin (define (removeKey m k)
 (call/cc (lambda (ret1)
 (let ((out (alist->hash-table (_list)
)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((key (car xs)
)
)
 (begin (if (not (string=? key k)
)
 (begin (hash-table-set! out key (hash-table-ref/default m key (quote ()
)
)
)
)
 (quote ()
)
)
)
)
 (loop2 (cdr xs)
)
)
)
)
)
)
 (loop2 (hash-table-keys m)
)
)
)
)
 (ret1 out)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret4)
 (let ((x (quote ()
)
)
)
 (begin (set! x (alist->hash-table (_list)
)
)
 (hash-table-set! x "foo" 3)
 (let ((y1 (hash-table-ref/default x "bar" (quote ()
)
)
)
)
 (begin (let ((ok (cond ((string? x)
 (if (string-contains x "bar")
 #t #f)
)
 ((hash-table? x)
 (if (hash-table-exists? x "bar")
 #t #f)
)
 (else (if (member "bar" x)
 #t #f)
)
)
)
)
 (begin (display (to-str y1)
)
 (newline)
 (display (to-str (if ok #t #f)
)
)
 (newline)
 (set! x (removeKey x "foo")
)
 (set! x (alist->hash-table (_list (cons "foo" 2)
 (cons "bar" 42)
 (cons "baz" (- 1)
)
)
)
)
 (display (to-str (hash-table-ref/default x "foo" (quote ()
)
)
)
)
 (display " ")
 (display (to-str (hash-table-ref/default x "bar" (quote ()
)
)
)
)
 (display " ")
 (display (to-str (hash-table-ref/default x "baz" (quote ()
)
)
)
)
 (newline)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end6 (now)
)
)
 (let ((dur7 (quotient (- end6 start5)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur7)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
