;; Generated on 2025-07-26 21:55 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start7 (now)
)
)
 (begin (define (merge base update)
 (call/cc (lambda (ret1)
 (let ((result (alist->hash-table (_list)
)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((k (car xs)
)
)
 (begin (hash-table-set! result k (hash-table-ref/default base k (quote ()
)
)
)
)
)
 (loop2 (cdr xs)
)
)
)
)
)
)
 (loop2 (hash-table-keys base)
)
)
)
)
 (call/cc (lambda (break5)
 (letrec ((loop4 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((k (car xs)
)
)
 (begin (hash-table-set! result k (hash-table-ref/default update k (quote ()
)
)
)
)
)
 (loop4 (cdr xs)
)
)
)
)
)
)
 (loop4 (hash-table-keys update)
)
)
)
)
 (ret1 result)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret6)
 (let ((base (alist->hash-table (_list (cons "name" "Rocket Skates")
 (cons "price" 12.75)
 (cons "color" "yellow")
)
)
)
)
 (begin (let ((update (alist->hash-table (_list (cons "price" 15.25)
 (cons "color" "red")
 (cons "year" 1974)
)
)
)
)
 (begin (let ((result (merge base update)
)
)
 (begin (display (to-str result)
)
 (newline)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end8 (now)
)
)
 (let ((dur9 (quotient (- end8 start7)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur9)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
