;; Generated on 2025-07-26 23:50 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(let ((start10 (now)
)
)
 (begin (define (powf base exp)
 (call/cc (lambda (ret1)
 (let ((result 1.0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i exp)
 (begin (set! result (* result base)
)
 (set! i (+ i 1)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 result)
)
)
)
)
)
)
)
 (define (nthRoot x n)
 (call/cc (lambda (ret4)
 (let ((low 0.0)
)
 (begin (let ((high x)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i 60)
 (begin (let ((mid (/ (+ low high)
 2.0)
)
)
 (begin (if (_gt (powf mid n)
 x)
 (begin (set! high mid)
)
 (begin (set! low mid)
)
)
 (set! i (+ i 1)
)
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret4 low)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret7)
 (let ((sum 0.0)
)
 (begin (let ((sumRecip 0.0)
)
 (begin (let ((prod 1.0)
)
 (begin (let ((n 1)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (<= n 10)
 (begin (let ((f n)
)
 (begin (set! sum (+ sum f)
)
 (set! sumRecip (+ sumRecip (/ 1.0 f)
)
)
 (set! prod (* prod f)
)
 (set! n (+ n 1)
)
)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
 (let ((count 10.0)
)
 (begin (let ((a (/ sum count)
)
)
 (begin (let ((g (nthRoot prod 10)
)
)
 (begin (let ((h (/ count sumRecip)
)
)
 (begin (display (to-str (string-append (string-append (string-append (string-append (string-append "A: " (to-str a)
)
 " G: ")
 (to-str g)
)
 " H: ")
 (to-str h)
)
)
)
 (newline)
 (display (to-str (string-append "A >= G >= H: " (to-str (and (_ge a g)
 (_ge g h)
)
)
)
)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end11 (now)
)
)
 (let ((dur12 (quotient (- end11 start10)
 1000)
)
)
 (begin (display (string-append "{\n  \"duration_us\": " (number->string dur12)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
