;; Generated on 2025-07-27 16:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (inexact->exact (* (current-second) 1000000000))))(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(let ((start3 (now)
)
)
 (begin (define (examineAndModify f)
 (call/cc (lambda (ret1)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append " v: {" (to-str (hash-table-ref f "Exported")
)
)
 " ")
 (to-str (hash-table-ref f "unexported")
)
)
 "} = {")
 (to-str (hash-table-ref f "Exported")
)
)
 " ")
 (to-str (hash-table-ref f "unexported")
)
)
 "}")
)
)
 (newline)
 (_display (to-str "    Idx Name       Type CanSet")
)
 (newline)
 (_display (to-str "     0: Exported   int  true")
)
 (newline)
 (_display (to-str "     1: unexported int  false")
)
 (newline)
 (hash-table-set! f "Exported" 16)
 (hash-table-set! f "unexported" 44)
 (_display (to-str "  modified unexported field via unsafe")
)
 (newline)
 (ret1 f)
)
)
)
)
 (define (anotherExample)
 (call/cc (lambda (ret2)
 (begin (_display (to-str "bufio.ReadByte returned error: unsafely injected error value into bufio inner workings")
)
 (newline)
)
)
)
)
 (define obj (alist->hash-table (_list (cons "Exported" 12)
 (cons "unexported" 42)
)
)
)
 (_display (to-str (string-append (string-append (string-append (string-append "obj: {" (to-str (hash-table-ref obj "Exported")
)
)
 " ")
 (to-str (hash-table-ref obj "unexported")
)
)
 "}")
)
)
 (newline)
 (set! obj (examineAndModify obj)
)
 (_display (to-str (string-append (string-append (string-append (string-append "obj: {" (to-str (hash-table-ref obj "Exported")
)
)
 " ")
 (to-str (hash-table-ref obj "unexported")
)
)
 "}")
)
)
 (newline)
 (anotherExample)
 (let ((end4 (now)
)
)
 (let ((dur5 (quotient (- end4 start3)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur5)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
