;; Generated on 2025-07-27 23:17 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(let ((start11 (now)
)
)
 (begin (define epsilon 1e-15)
 (define (absf x)
 (call/cc (lambda (ret1)
 (begin (if (< x 0.0)
 (begin (ret1 (- x)
)
)
 (quote ()
)
)
 (ret1 x)
)
)
)
)
 (define (pow10 n)
 (call/cc (lambda (ret2)
 (let ((r 1.0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (< i n)
 (begin (set! r (* r 10.0)
)
 (set! i (+ i 1)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (ret2 r)
)
)
)
)
)
)
)
 (define (formatFloat f prec)
 (call/cc (lambda (ret5)
 (let ((scale (pow10 prec)
)
)
 (begin (let ((scaled (+ (* f scale)
 0.5)
)
)
 (begin (let ((n (let ((v6 scaled)
)
 (cond ((string? v6)
 (exact (floor (string->number v6)
)
)
)
 ((boolean? v6)
 (if v6 1 0)
)
 (else (exact (floor v6)
)
)
)
)
)
)
 (begin (let ((digits (to-str n)
)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (<= (cond ((string? digits)
 (string-length digits)
)
 ((hash-table? digits)
 (hash-table-size digits)
)
 (else (length digits)
)
)
 prec)
 (begin (set! digits (string-append "0" digits)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
 (let ((intPart (substring digits 0 (- (cond ((string? digits)
 (string-length digits)
)
 ((hash-table? digits)
 (hash-table-size digits)
)
 (else (length digits)
)
)
 prec)
)
)
)
 (begin (let ((fracPart (substring digits (- (cond ((string? digits)
 (string-length digits)
)
 ((hash-table? digits)
 (hash-table-size digits)
)
 (else (length digits)
)
)
 prec)
 (cond ((string? digits)
 (string-length digits)
)
 ((hash-table? digits)
 (hash-table-size digits)
)
 (else (length digits)
)
)
)
)
)
 (begin (ret5 (string-append (string-append intPart ".")
 fracPart)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define factval 1)
 (define e 2.0)
 (define n 2)
 (define term 1.0)
 (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if #t (begin (set! factval (* factval n)
)
 (set! n (+ n 1)
)
 (set! term (/ 1.0 factval)
)
 (set! e (+ e term)
)
 (if (_lt (absf term)
 epsilon)
 (begin (break10 (quote ()
)
)
)
 (quote ()
)
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
 (_display (to-str (string-append "e = " (formatFloat e 15)
)
)
)
 (newline)
 (let ((end12 (now)
)
)
 (let ((dur13 (quotient (- end12 start11)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur13)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
