;; Generated on 2025-08-02 17:26 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (mod n m) (call/cc (lambda (ret1) (ret1 (modulo (+ (modulo n m) m) m)))))
(define (isPrime n) (call/cc (lambda (ret2) (begin (if (< n 2) (begin (ret2 #f)) (quote ())) (if (equal? (modulo n 2) 0) (begin (ret2 (equal? n 2))) (quote ())) (if (equal? (modulo n 3) 0) (begin (ret2 (equal? n 3))) (quote ())) (let ((d 5)) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda () (if (_le (* d d) n) (begin (if (equal? (modulo n d) 0) (begin (ret2 #f)) (quote ())) (set! d (+ d 2)) (if (equal? (modulo n d) 0) (begin (ret2 #f)) (quote ())) (set! d (+ d 4)) (loop3)) (quote ()))))) (loop3)))) (ret2 #t)))))))
(define (pad n width) (call/cc (lambda (ret5) (let ((s (to-str n))) (begin (call/cc (lambda (break7) (letrec ((loop6 (lambda () (if (< (cond ((string? s) (string-length s)) ((hash-table? s) (hash-table-size s)) (else (length s))) width) (begin (set! s (string-append " " s)) (loop6)) (quote ()))))) (loop6)))) (ret5 s))))))
(define (carmichael p1) (call/cc (lambda (ret8) (call/cc (lambda (break10) (letrec ((loop9 (lambda (h3) (if (< h3 p1) (begin (begin (call/cc (lambda (break12) (letrec ((loop11 (lambda (d) (if (< d (_add h3 p1)) (begin (begin (if (and (equal? (fmod (* (_add h3 p1) (- p1 1)) d) 0) (equal? (mod (* (- p1) p1) h3) (fmod d h3))) (begin (let ((p2 (_add 1 (quotient (* (- p1 1) (_add h3 p1)) d)))) (begin (if (not (isPrime p2)) (begin (loop11 (+ d 1))) (quote ())) (let ((p3 (_add 1 (quotient (* p1 p2) h3)))) (begin (if (not (isPrime p3)) (begin (loop11 (+ d 1))) (quote ())) (if (not (equal? (fmod (* p2 p3) (- p1 1)) 1)) (begin (loop11 (+ d 1))) (quote ())) (let ((c (* (* p1 p2) p3))) (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append (pad p1 2) "   ") (pad p2 4)) "   ") (pad p3 5)) "     ") (to-str c)))) (newline)))))))) (quote ()))) (loop11 (+ d 1))) (quote ()))))) (loop11 1))))) (loop9 (+ h3 1))) (quote ()))))) (loop9 2)))))))
(_display (to-str "The following are Carmichael munbers for p1 <= 61:\n"))
(newline)
(_display (to-str "p1     p2      p3     product"))
(newline)
(_display (to-str "==     ==      ==     ======="))
(newline)
(call/cc (lambda (break14) (letrec ((loop13 (lambda (p1) (if (< p1 62) (begin (begin (if (isPrime p1) (begin (carmichael p1)) (quote ()))) (loop13 (+ p1 1))) (quote ()))))) (loop13 2))))
