;; Generated on 2025-08-02 18:09 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (main) (call/cc (lambda (ret1) (let ((pkg_dog "Salt")) (begin (let ((Dog "Pepper")) (begin (let ((pkg_DOG "Mustard")) (begin (define (packageSees d1 d2 d3) (call/cc (lambda (ret2) (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append "Package sees: " d1) " ") d2) " ") d3))) (newline) (ret2 (alist->hash-table (_list (cons "pkg_dog" #t) (cons "Dog" #t) (cons "pkg_DOG" #t)))))))) (let ((d (packageSees pkg_dog Dog pkg_DOG))) (begin (_display (to-str (string-append (string-append "There are " (to-str (cond ((string? d) (string-length d)) ((hash-table? d) (hash-table-size d)) (else (length d))))) " dogs.\n"))) (newline) (let ((dog "Benjamin")) (begin (set! d (packageSees pkg_dog Dog pkg_DOG)) (_display (to-str (string-append (string-append (string-append (string-append (string-append "Main sees:   " dog) " ") Dog) " ") pkg_DOG))) (newline) (hash-table-set! d "dog" #t) (hash-table-set! d "Dog" #t) (hash-table-set! d "pkg_DOG" #t) (_display (to-str (string-append (string-append "There are " (to-str (cond ((string? d) (string-length d)) ((hash-table? d) (hash-table-size d)) (else (length d))))) " dogs.\n"))) (newline) (set! Dog "Samba") (set! d (packageSees pkg_dog Dog pkg_DOG)) (_display (to-str (string-append (string-append (string-append (string-append (string-append "Main sees:   " dog) " ") Dog) " ") pkg_DOG))) (newline) (hash-table-set! d "dog" #t) (hash-table-set! d "Dog" #t) (hash-table-set! d "pkg_DOG" #t) (_display (to-str (string-append (string-append "There are " (to-str (cond ((string? d) (string-length d)) ((hash-table? d) (hash-table-size d)) (else (length d))))) " dogs.\n"))) (newline) (let ((DOG "Bernie")) (begin (set! d (packageSees pkg_dog Dog pkg_DOG)) (_display (to-str (string-append (string-append (string-append (string-append (string-append "Main sees:   " dog) " ") Dog) " ") DOG))) (newline) (hash-table-set! d "dog" #t) (hash-table-set! d "Dog" #t) (hash-table-set! d "pkg_DOG" #t) (hash-table-set! d "DOG" #t) (_display (to-str (string-append (string-append "There are " (to-str (cond ((string? d) (string-length d)) ((hash-table? d) (hash-table-size d)) (else (length d))))) " dogs."))) (newline))))))))))))))))
(main)
