;; Generated on 2025-08-02 18:09 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (indexOf s ch) (call/cc (lambda (ret1) (let ((i 0)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (< i (cond ((string? s) (string-length s)) ((hash-table? s) (hash-table-size s)) (else (length s)))) (begin (if (string=? (_substring s i (+ i 1)) ch) (begin (ret1 i)) (quote ())) (set! i (+ i 1)) (loop2)) (quote ()))))) (loop2)))) (ret1 (- 1)))))))
(define (rotate s n) (call/cc (lambda (ret4) (ret4 (string-append (_substring s n (string-length s)) (_substring s 0 n))))))
(define (scrambleLeft s) (call/cc (lambda (ret5) (ret5 (string-append (string-append (string-append (_substring s 0 1) (_substring s 2 14)) (_substring s 1 2)) (_substring s 14 (string-length s)))))))
(define (scrambleRight s) (call/cc (lambda (ret6) (ret6 (string-append (string-append (string-append (string-append (_substring s 1 3) (_substring s 4 15)) (_substring s 3 4)) (_substring s 15 (string-length s))) (_substring s 0 1))))))
(define (chao text encode) (call/cc (lambda (ret7) (let ((left "HXUCZVAMDSLKPEFJRIGTWOBNYQ")) (begin (let ((right "PTLNBQDEOYSFAVZKGJRIHWXUMC")) (begin (let ((out "")) (begin (let ((i 0)) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (< i (cond ((string? text) (string-length text)) ((hash-table? text) (hash-table-size text)) (else (length text)))) (begin (let ((ch (_substring text i (+ i 1)))) (begin (let ((idx 0)) (begin (if encode (begin (set! idx (indexOf right ch)) (set! out (string-append out (_substring left idx (+ idx 1))))) (begin (set! idx (indexOf left ch)) (set! out (string-append out (_substring right idx (+ idx 1)))))) (set! left (rotate left idx)) (set! right (rotate right idx)) (set! left (scrambleLeft left)) (set! right (scrambleRight right)) (set! i (+ i 1)))))) (loop8)) (quote ()))))) (loop8)))) (ret7 out))))))))))))
(define (main) (call/cc (lambda (ret10) (let ((plain "WELLDONEISBETTERTHANWELLSAID")) (begin (let ((cipher (chao plain #t))) (begin (_display (to-str plain)) (newline) (_display (to-str cipher)) (newline) (_display (to-str (chao cipher #f))) (newline))))))))
(main)
