;; Generated on 2025-08-02 18:09 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (egcd a b) (call/cc (lambda (ret1) (begin (if (equal? a 0) (begin (ret1 (_list b 0 1))) (quote ())) (let ((res (egcd (modulo b a) a))) (begin (let ((g (cond ((string? res) (_substring res 0 (+ 0 1))) ((hash-table? res) (hash-table-ref res 0)) (else (list-ref res 0))))) (begin (let ((x1 (cond ((string? res) (_substring res 1 (+ 1 1))) ((hash-table? res) (hash-table-ref res 1)) (else (list-ref res 1))))) (begin (let ((y1 (cond ((string? res) (_substring res 2 (+ 2 1))) ((hash-table? res) (hash-table-ref res 2)) (else (list-ref res 2))))) (begin (ret1 (_list g (- y1 (* (quotient b a) x1)) x1))))))))))))))
(define (modInv a m) (call/cc (lambda (ret2) (let ((r (egcd a m))) (begin (if (not (equal? (cond ((string? r) (_substring r 0 (+ 0 1))) ((hash-table? r) (hash-table-ref r 0)) (else (list-ref r 0))) 1)) (begin (ret2 0)) (quote ())) (let ((x (cond ((string? r) (_substring r 1 (+ 1 1))) ((hash-table? r) (hash-table-ref r 1)) (else (list-ref r 1))))) (begin (if (_lt x 0) (begin (ret2 (_add x m))) (quote ())) (ret2 x))))))))
(define (crt a n) (call/cc (lambda (ret3) (let ((prod 1)) (begin (let ((i 0)) (begin (call/cc (lambda (break5) (letrec ((loop4 (lambda () (if (< i (cond ((string? n) (string-length n)) ((hash-table? n) (hash-table-size n)) (else (length n)))) (begin (set! prod (* prod (list-ref n i))) (set! i (+ i 1)) (loop4)) (quote ()))))) (loop4)))) (let ((x 0)) (begin (set! i 0) (call/cc (lambda (break7) (letrec ((loop6 (lambda () (if (< i (cond ((string? n) (string-length n)) ((hash-table? n) (hash-table-size n)) (else (length n)))) (begin (let ((ni (list-ref n i))) (begin (let ((ai (list-ref a i))) (begin (let ((p (quotient prod ni))) (begin (let ((inv (modInv (modulo p ni) ni))) (begin (set! x (_add x (* (* ai inv) p))) (set! i (+ i 1)))))))))) (loop6)) (quote ()))))) (loop6)))) (ret3 (modulo x prod)))))))))))
(define n (_list 3 5 7))
(define a (_list 2 3 2))
(define res (crt a n))
(_display (to-str (string-append (to-str res) " <nil>")))
(newline)
