;; Generated on 2025-07-28 11:58 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start21 (now)
)
)
 (begin (define (sqrtApprox x)
 (call/cc (lambda (ret1)
 (let ((guess x)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i 20)
 (begin (set! guess (/ (_add guess (/ x guess)
)
 2.0)
)
 (set! i (+ i 1)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 guess)
)
)
)
)
)
)
)
 (define (cholesky a)
 (call/cc (lambda (ret4)
 (let ((n (cond ((string? a)
 (string-length a)
)
 ((hash-table? a)
 (hash-table-size a)
)
 (else (length a)
)
)
)
)
 (begin (let ((l (_list)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i n)
 (begin (let ((row (_list)
)
)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (< j n)
 (begin (set! row (append row (_list 0.0)
)
)
 (set! j (+ j 1)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
 (set! l (append l (_list row)
)
)
 (set! i (+ i 1)
)
)
)
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (set! i 0)
 (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if (< i n)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break12)
 (letrec ((loop11 (lambda ()
 (if (<= j i)
 (begin (let ((sum (cond ((string? (list-ref a i)
)
 (substring (list-ref a i)
 j (+ j 1)
)
)
 ((hash-table? (list-ref a i)
)
 (hash-table-ref (list-ref a i)
 j)
)
 (else (list-ref (list-ref a i)
 j)
)
)
)
)
 (begin (let ((k 0)
)
 (begin (call/cc (lambda (break14)
 (letrec ((loop13 (lambda ()
 (if (< k j)
 (begin (set! sum (- sum (* (cond ((string? (list-ref l i)
)
 (substring (list-ref l i)
 k (+ k 1)
)
)
 ((hash-table? (list-ref l i)
)
 (hash-table-ref (list-ref l i)
 k)
)
 (else (list-ref (list-ref l i)
 k)
)
)
 (cond ((string? (list-ref l j)
)
 (substring (list-ref l j)
 k (+ k 1)
)
)
 ((hash-table? (list-ref l j)
)
 (hash-table-ref (list-ref l j)
 k)
)
 (else (list-ref (list-ref l j)
 k)
)
)
)
)
)
 (set! k (+ k 1)
)
 (loop13)
)
 (quote ()
)
)
)
)
)
 (loop13)
)
)
)
 (if (equal? i j)
 (begin (list-set! (list-ref l i)
 j (sqrtApprox sum)
)
)
 (begin (list-set! (list-ref l i)
 j (/ sum (cond ((string? (list-ref l j)
)
 (substring (list-ref l j)
 j (+ j 1)
)
)
 ((hash-table? (list-ref l j)
)
 (hash-table-ref (list-ref l j)
 j)
)
 (else (list-ref (list-ref l j)
 j)
)
)
)
)
)
)
 (set! j (+ j 1)
)
)
)
)
)
 (loop11)
)
 (quote ()
)
)
)
)
)
 (loop11)
)
)
)
 (set! i (+ i 1)
)
)
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
 (ret4 l)
)
)
)
)
)
)
)
)
)
 (define (printMat m)
 (call/cc (lambda (ret15)
 (let ((i 0)
)
 (begin (call/cc (lambda (break17)
 (letrec ((loop16 (lambda ()
 (if (< i (cond ((string? m)
 (string-length m)
)
 ((hash-table? m)
 (hash-table-size m)
)
 (else (length m)
)
)
)
 (begin (let ((line "")
)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break19)
 (letrec ((loop18 (lambda ()
 (if (< j (cond ((string? (list-ref m i)
)
 (string-length (list-ref m i)
)
)
 ((hash-table? (list-ref m i)
)
 (hash-table-size (list-ref m i)
)
)
 (else (length (list-ref m i)
)
)
)
)
 (begin (set! line (string-append line (to-str (cond ((string? (list-ref m i)
)
 (substring (list-ref m i)
 j (+ j 1)
)
)
 ((hash-table? (list-ref m i)
)
 (hash-table-ref (list-ref m i)
 j)
)
 (else (list-ref (list-ref m i)
 j)
)
)
)
)
)
 (if (_lt j (- (cond ((string? (list-ref m i)
)
 (string-length (list-ref m i)
)
)
 ((hash-table? (list-ref m i)
)
 (hash-table-size (list-ref m i)
)
)
 (else (length (list-ref m i)
)
)
)
 1)
)
 (begin (set! line (string-append line " ")
)
)
 (quote ()
)
)
 (set! j (+ j 1)
)
 (loop18)
)
 (quote ()
)
)
)
)
)
 (loop18)
)
)
)
 (_display (to-str line)
)
 (newline)
 (set! i (+ i 1)
)
)
)
)
)
 (loop16)
)
 (quote ()
)
)
)
)
)
 (loop16)
)
)
)
)
)
)
)
)
 (define (demo a)
 (call/cc (lambda (ret20)
 (begin (_display (to-str "A:")
)
 (newline)
 (printMat a)
 (let ((l (cholesky a)
)
)
 (begin (_display (to-str "L:")
)
 (newline)
 (printMat l)
)
)
)
)
)
)
 (demo (_list (_list 25.0 15.0 (- 5.0)
)
 (_list 15.0 18.0 0.0)
 (_list (- 5.0)
 0.0 11.0)
)
)
 (demo (_list (_list 18.0 22.0 54.0 42.0)
 (_list 22.0 70.0 86.0 62.0)
 (_list 54.0 86.0 174.0 134.0)
 (_list 42.0 62.0 134.0 106.0)
)
)
 (let ((end22 (now)
)
)
 (let ((dur23 (quotient (- end22 start21)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur23)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
