;; Generated on 2025-07-28 11:58 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start5 (now)
)
)
 (begin (define (quibble items)
 (call/cc (lambda (ret1)
 (let ((n (cond ((string? items)
 (string-length items)
)
 ((hash-table? items)
 (hash-table-size items)
)
 (else (length items)
)
)
)
)
 (begin (if (equal? n 0)
 (begin (ret1 "{}")
)
 (if (equal? n 1)
 (begin (ret1 (string-append (string-append "{" (list-ref items 0)
)
 "}")
)
)
 (if (equal? n 2)
 (begin (ret1 (string-append (string-append (string-append (string-append "{" (list-ref items 0)
)
 " and ")
 (list-ref items 1)
)
 "}")
)
)
 (begin (let ((prefix "")
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda (i)
 (if (< i (- n 1)
)
 (begin (begin (if (equal? i (- n 1)
)
 (begin (break3 (quote ()
)
)
)
 (quote ()
)
)
 (if (_gt i 0)
 (begin (set! prefix (string-append prefix ", ")
)
)
 (quote ()
)
)
 (set! prefix (string-append prefix (list-ref items i)
)
)
)
 (loop2 (+ i 1)
)
)
 (quote ()
)
)
)
)
)
 (loop2 0)
)
)
)
 (ret1 (string-append (string-append (string-append (string-append "{" prefix)
 " and ")
 (list-ref items (- n 1)
)
)
 "}")
)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret4)
 (begin (_display (to-str (quibble (_list)
)
)
)
 (newline)
 (_display (to-str (quibble (_list "ABC")
)
)
)
 (newline)
 (_display (to-str (quibble (_list "ABC" "DEF")
)
)
)
 (newline)
 (_display (to-str (quibble (_list "ABC" "DEF" "G" "H")
)
)
)
 (newline)
)
)
)
)
 (main)
 (let ((end6 (now)
)
)
 (let ((dur7 (quotient (- end6 start5)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur7)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
