;; Generated on 2025-08-03 00:11 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start15 (now))) (begin (define (newTerm a b) (call/cc (lambda (ret1) (ret1 (alist->hash-table (_list (cons "a" a) (cons "b" b))))))) (define (cfSqrt2 nTerms) (call/cc (lambda (ret2) (let ((f (_list))) (begin (let ((n 0)) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda () (if (< n nTerms) (begin (set! f (append f (_list (newTerm 2 1)))) (set! n (+ n 1)) (loop3)) (quote ()))))) (loop3)))) (if (> nTerms 0) (begin (hash-table-set! (list-ref f 0) "a" 1)) (quote ())) (ret2 f)))))))) (define (cfNap nTerms) (call/cc (lambda (ret5) (let ((f (_list))) (begin (let ((n 0)) (begin (call/cc (lambda (break7) (letrec ((loop6 (lambda () (if (< n nTerms) (begin (set! f (append f (_list (newTerm n (- n 1))))) (set! n (+ n 1)) (loop6)) (quote ()))))) (loop6)))) (if (> nTerms 0) (begin (hash-table-set! (list-ref f 0) "a" 2)) (quote ())) (if (> nTerms 1) (begin (hash-table-set! (list-ref f 1) "b" 1)) (quote ())) (ret5 f)))))))) (define (cfPi nTerms) (call/cc (lambda (ret8) (let ((f (_list))) (begin (let ((n 0)) (begin (call/cc (lambda (break10) (letrec ((loop9 (lambda () (if (< n nTerms) (begin (let ((g (- (* 2 n) 1))) (begin (set! f (append f (_list (newTerm 6 (* g g))))) (set! n (+ n 1)))) (loop9)) (quote ()))))) (loop9)))) (if (> nTerms 0) (begin (hash-table-set! (list-ref f 0) "a" 3)) (quote ())) (ret8 f)))))))) (define (real f) (call/cc (lambda (ret11) (let ((r 0.0)) (begin (let ((i (- (cond ((string? f) (string-length f)) ((hash-table? f) (hash-table-size f)) (else (length f))) 1))) (begin (call/cc (lambda (break13) (letrec ((loop12 (lambda () (if (> i 0) (begin (set! r (/ (+ 0.0 (cond ((string? (list-ref f i)) (_substring (list-ref f i) "b" (+ "b" 1))) ((hash-table? (list-ref f i)) (hash-table-ref (list-ref f i) "b")) (else (list-ref (list-ref f i) "b")))) (+ (+ 0.0 (cond ((string? (list-ref f i)) (_substring (list-ref f i) "a" (+ "a" 1))) ((hash-table? (list-ref f i)) (hash-table-ref (list-ref f i) "a")) (else (list-ref (list-ref f i) "a")))) r))) (set! i (- i 1)) (loop12)) (quote ()))))) (loop12)))) (if (> (cond ((string? f) (string-length f)) ((hash-table? f) (hash-table-size f)) (else (length f))) 0) (begin (set! r (+ r (+ 0.0 (cond ((string? (list-ref f 0)) (_substring (list-ref f 0) "a" (+ "a" 1))) ((hash-table? (list-ref f 0)) (hash-table-ref (list-ref f 0) "a")) (else (list-ref (list-ref f 0) "a"))))))) (quote ())) (ret11 r)))))))) (define (main) (call/cc (lambda (ret14) (begin (_display (to-str (string-append "sqrt2: " (to-str (real (cfSqrt2 20)))))) (newline) (_display (to-str (string-append "nap:   " (to-str (real (cfNap 20)))))) (newline) (_display (to-str (string-append "pi:    " (to-str (real (cfPi 20)))))) (newline))))) (main) (let ((end16 (now))) (let ((dur17 (quotient (- end16 start15) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur17) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
