;; Generated on 2025-08-03 00:11 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start14 (now))) (begin (define (gcd a b) (call/cc (lambda (ret1) (let ((x a)) (begin (if (< x 0) (begin (set! x (- x))) (quote ())) (let ((y b)) (begin (if (< y 0) (begin (set! y (- y))) (quote ())) (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (not (equal? y 0)) (begin (let ((t (modulo x y))) (begin (set! x y) (set! y t))) (loop2)) (quote ()))))) (loop2)))) (ret1 x)))))))) (define (parseRational s) (call/cc (lambda (ret4) (let ((intPart 0)) (begin (let ((fracPart 0)) (begin (let ((denom 1)) (begin (let ((afterDot #f)) (begin (let ((i 0)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (< i (cond ((string? s) (string-length s)) ((hash-table? s) (hash-table-size s)) (else (length s)))) (begin (let ((ch (_substring s i (+ i 1)))) (begin (if (string=? ch ".") (begin (set! afterDot #t)) (begin (let ((d (- (let ((v7 ch)) (cond ((string? v7) (exact (floor (string->number v7)))) ((boolean? v7) (if v7 1 0)) (else (exact (floor v7))))) (let ((v8 "0")) (cond ((string? v8) (exact (floor (string->number v8)))) ((boolean? v8) (if v8 1 0)) (else (exact (floor v8)))))))) (begin (if (not afterDot) (begin (set! intPart (_add (* intPart 10) d))) (begin (set! fracPart (_add (* fracPart 10) d)) (set! denom (* denom 10)))))))) (set! i (+ i 1)))) (loop5)) (quote ()))))) (loop5)))) (let ((num (_add (* intPart denom) fracPart))) (begin (let ((g (gcd num denom))) (begin (ret4 (alist->hash-table (_list (cons "num" (let ((v9 (quotient num g))) (cond ((string? v9) (inexact->exact (floor (string->number v9)))) ((boolean? v9) (if v9 1 0)) (else (inexact->exact (floor v9)))))) (cons "den" (let ((v10 (quotient denom g))) (cond ((string? v10) (inexact->exact (floor (string->number v10)))) ((boolean? v10) (if v10 1 0)) (else (inexact->exact (floor v10)))))))))))))))))))))))))) (define (main) (call/cc (lambda (ret11) (let ((inputs (_list "0.9054054" "0.518518" "0.75"))) (begin (call/cc (lambda (break13) (letrec ((loop12 (lambda (xs) (if (null? xs) (quote ()) (begin (let ((s (car xs))) (begin (let ((r (parseRational s))) (begin (_display (to-str (string-append (string-append (string-append (string-append s " = ") (to-str (cond ((string? r) (_substring r "num" (+ "num" 1))) ((hash-table? r) (hash-table-ref r "num")) (else (list-ref r "num"))))) "/") (to-str (cond ((string? r) (_substring r "den" (+ "den" 1))) ((hash-table? r) (hash-table-ref r "den")) (else (list-ref r "den"))))))) (newline))))) (loop12 (cdr xs))))))) (loop12 inputs))))))))) (main) (let ((end15 (now))) (let ((dur16 (quotient (- end15 start14) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur16) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
