;; Generated on 2025-08-03 09:40 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start16 (now))) (begin (define (padLeft n width) (call/cc (lambda (ret1) (let ((s (to-str n))) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (< (cond ((string? s) (string-length s)) ((hash-table? s) (hash-table-size s)) (else (length s))) width) (begin (set! s (string-append " " s)) (loop2)) (quote ()))))) (loop2)))) (ret1 s)))))) (define (modPow base exp mod) (call/cc (lambda (ret4) (let ((result (modulo 1 mod))) (begin (let ((b (modulo base mod))) (begin (let ((e exp)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (> e 0) (begin (if (equal? (modulo e 2) 1) (begin (set! result (modulo (* result b) mod))) (quote ())) (set! b (modulo (* b b) mod)) (set! e (quotient e 2)) (loop5)) (quote ()))))) (loop5)))) (ret4 result)))))))))) (define (main) (call/cc (lambda (ret7) (let ((k 2)) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (<= k 10) (begin (_display (to-str (string-append (string-append "The first 50 Curzon numbers using a base of " (to-str k)) " :"))) (newline) (let ((count 0)) (begin (let ((n 1)) (begin (let ((curzon50 (_list))) (begin (call/cc (lambda (break11) (letrec ((loop10 (lambda () (if #t (begin (let ((d (_add (* k n) 1))) (begin (if (equal? (fmod (_add (modPow k n d) 1) d) 0) (begin (if (< count 50) (begin (set! curzon50 (append curzon50 (_list n)))) (quote ())) (set! count (+ count 1)) (if (equal? count 50) (begin (let ((idx 0)) (begin (call/cc (lambda (break13) (letrec ((loop12 (lambda () (if (< idx (cond ((string? curzon50) (string-length curzon50)) ((hash-table? curzon50) (hash-table-size curzon50)) (else (length curzon50)))) (begin (let ((line "")) (begin (let ((j 0)) (begin (call/cc (lambda (break15) (letrec ((loop14 (lambda () (if (< j 10) (begin (set! line (string-append (string-append line (padLeft (list-ref curzon50 idx) 4)) " ")) (set! idx (+ idx 1)) (set! j (+ j 1)) (loop14)) (quote ()))))) (loop14)))) (_display (to-str (_substring line 0 (- (cond ((string? line) (string-length line)) ((hash-table? line) (hash-table-size line)) (else (length line))) 1)))) (newline))))) (loop12)) (quote ()))))) (loop12))))))) (quote ())) (if (equal? count 1000) (begin (_display (to-str (string-append "\nOne thousandth: " (to-str n)))) (newline) (break11 (quote ()))) (quote ()))) (quote ())) (set! n (+ n 1)))) (loop10)) (quote ()))))) (loop10)))) (_display (to-str "")) (newline) (set! k (+ k 2)))))))) (loop8)) (quote ()))))) (loop8))))))))) (main) (let ((end17 (now))) (let ((dur18 (quotient (- end17 start16) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur18) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
