;; Generated on 2025-08-03 09:40 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start7 (now))) (begin (define (ord ch) (call/cc (lambda (ret1) (let ((upper "ABCDEFGHIJKLMNOPQRSTUVWXYZ")) (begin (if (and (string>=? ch "0") (string<=? ch "9")) (begin (ret1 (+ (_parseIntStr ch 10) 48))) (quote ())) (let ((idx (indexOf upper ch))) (begin (if (>= idx 0) (begin (ret1 (+ 65 idx))) (quote ())) (ret1 0)))))))) (define (isCusip s) (call/cc (lambda (ret2) (begin (if (not (equal? (cond ((string? s) (string-length s)) ((hash-table? s) (hash-table-size s)) (else (length s))) 9)) (begin (ret2 #f)) (quote ())) (let ((sum 0)) (begin (let ((i 0)) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda () (if (< i 8) (begin (let ((c (_substring s i (+ i 1)))) (begin (let ((v 0)) (begin (if (and (string>=? c "0") (string<=? c "9")) (begin (set! v (_parseIntStr c 10))) (if (and (string>=? c "A") (string<=? c "Z")) (begin (set! v (- (ord c) 55))) (if (string=? c "*") (begin (set! v 36)) (if (string=? c "@") (begin (set! v 37)) (if (string=? c "#") (begin (set! v 38)) (begin (ret2 #f))))))) (if (equal? (modulo i 2) 1) (begin (set! v (* v 2))) (quote ())) (set! sum (_add (_add sum (quotient v 10)) (modulo v 10))) (set! i (+ i 1)))))) (loop3)) (quote ()))))) (loop3)))) (ret2 (equal? (_parseIntStr (_substring s 8 9) 10) (modulo (- 10 (modulo sum 10)) 10))))))))))) (define candidates (_list "037833100" "17275R102" "38259P508" "594918104" "68389X106" "68389X105")) (call/cc (lambda (break6) (letrec ((loop5 (lambda (xs) (if (null? xs) (quote ()) (begin (let ((cand (car xs))) (begin (let ((b "incorrect")) (begin (if (isCusip cand) (begin (set! b "correct")) (quote ())) (_display (to-str (string-append (string-append cand " -> ") b))) (newline))))) (loop5 (cdr xs))))))) (loop5 candidates)))) (let ((end8 (now))) (let ((dur9 (quotient (- end8 start7) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur9) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
