;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(define seed 1)
(define (rnd)
 (call/cc (lambda (ret1)
 (begin (set! seed (modulo (_add (* seed 214013)
 2531011)
 2147483648)
)
 (ret1 (quotient seed 65536)
)
)
)
)
)
(define (deal game)
 (call/cc (lambda (ret2)
 (begin (set! seed game)
 (let ((deck (_list)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (< i 52)
 (begin (set! deck (append deck (_list (- 51 i)
)
)
)
 (set! i (+ i 1)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (set! i 0)
 (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i 51)
 (begin (let ((j (- 51 (fmod (rnd)
 (- 52 i)
)
)
)
)
 (begin (let ((tmp (list-ref deck i)
)
)
 (begin (list-set! deck i (list-ref deck j)
)
 (list-set! deck j tmp)
 (set! i (+ i 1)
)
)
)
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret2 deck)
)
)
)
)
)
)
)
)
(define suits "CDHS")
(define nums "A23456789TJQK")
(define (show cards)
 (call/cc (lambda (ret7)
 (let ((i 0)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (< i (cond ((string? cards)
 (string-length cards)
)
 ((hash-table? cards)
 (hash-table-size cards)
)
 (else (length cards)
)
)
)
 (begin (let ((c (list-ref cards i)
)
)
 (begin (write "stdout" (string-append (string-append " " (substring nums (quotient c 4)
 (_add (quotient c 4)
 1)
)
)
 (substring suits (modulo c 4)
 (_add (modulo c 4)
 1)
)
)
)
 (if (or (equal? (modulo (+ i 1)
 8)
 0)
 (equal? (+ i 1)
 (cond ((string? cards)
 (string-length cards)
)
 ((hash-table? cards)
 (hash-table-size cards)
)
 (else (length cards)
)
)
)
)
 (begin (_display (to-str "")
)
 (newline)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
)
)
)
)
)
(_display (to-str "")
)
(newline)
(_display (to-str "Game #1")
)
(newline)
(show (deal 1)
)
(_display (to-str "")
)
(newline)
(_display (to-str "Game #617")
)
(newline)
(show (deal 617)
)
