;; Generated on 2025-08-03 09:40 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start10 (now))) (begin (define (isPrime n) (call/cc (lambda (ret1) (begin (if (< n 2) (begin (ret1 #f)) (quote ())) (if (equal? (modulo n 2) 0) (begin (ret1 (equal? n 2))) (quote ())) (if (equal? (modulo n 3) 0) (begin (ret1 (equal? n 3))) (quote ())) (let ((d 5)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (_le (* d d) n) (begin (if (equal? (modulo n d) 0) (begin (ret1 #f)) (quote ())) (set! d (+ d 2)) (if (equal? (modulo n d) 0) (begin (ret1 #f)) (quote ())) (set! d (+ d 4)) (loop2)) (quote ()))))) (loop2)))) (ret1 #t))))))) (define (listToString xs) (call/cc (lambda (ret4) (let ((s "[")) (begin (let ((i 0)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (< i (cond ((string? xs) (string-length xs)) ((hash-table? xs) (hash-table-size xs)) (else (length xs)))) (begin (set! s (string-append s (to-str (list-ref xs i)))) (if (_lt i (- (cond ((string? xs) (string-length xs)) ((hash-table? xs) (hash-table-size xs)) (else (length xs))) 1)) (begin (set! s (string-append s " "))) (quote ())) (set! i (+ i 1)) (loop5)) (quote ()))))) (loop5)))) (ret4 (string-append s "]"))))))))) (define (main) (call/cc (lambda (ret7) (let ((count 0)) (begin (let ((limit 25)) (begin (let ((n 17)) (begin (let ((repunit 1111111111111111)) (begin (let ((eleven 11)) (begin (let ((hundred 100)) (begin (let ((deceptive (_list))) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (< count limit) (begin (if (and (and (not (isPrime n)) (not (equal? (modulo n 3) 0))) (not (equal? (modulo n 5) 0))) (begin (let ((bn n)) (begin (if (equal? (fmod repunit bn) 0) (begin (set! deceptive (append deceptive (_list n))) (set! count (+ count 1))) (quote ()))))) (quote ())) (set! n (+ n 2)) (set! repunit (+ (* repunit hundred) eleven)) (loop8)) (quote ()))))) (loop8)))) (_display (to-str (string-append (string-append "The first " (to-str limit)) " deceptive numbers are:"))) (newline) (_display (to-str (listToString deceptive))) (newline)))))))))))))))))) (main) (let ((end11 (now))) (let ((dur12 (quotient (- end11 start10) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur12) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
