;; Generated on 2025-07-28 11:25 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(define (ord ch)
 (call/cc (lambda (ret1)
 (begin (if (string=? ch "5")
 (begin (ret1 53)
)
 (quote ()
)
)
 (if (string=? ch "T")
 (begin (ret1 84)
)
 (quote ()
)
)
 (if (string=? ch " ")
 (begin (ret1 32)
)
 (quote ()
)
)
 (if (string=? ch "é")
 (begin (ret1 233)
)
 (quote ()
)
)
 (if (string=? ch "🐺")
 (begin (ret1 128058)
)
 (quote ()
)
)
 (ret1 0)
)
)
)
)
(define (hex n)
 (call/cc (lambda (ret2)
 (let ((digits "0123456789abcdef")
)
 (begin (if (equal? n 0)
 (begin (ret2 "0x0")
)
 (quote ()
)
)
 (let ((m n)
)
 (begin (let ((out "")
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (> m 0)
 (begin (let ((d (modulo m 16)
)
)
 (begin (set! out (string-append (substring digits d (+ d 1)
)
 out)
)
 (set! m (quotient m 16)
)
)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (ret2 (string-append "0x" out)
)
)
)
)
)
)
)
)
)
)
(define (quote s)
 (call/cc (lambda (ret5)
 (ret5 (string-append (string-append "'" s)
 "'")
)
)
)
)
(define (analyze s)
 (call/cc (lambda (ret6)
 (let ((le (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append "Analyzing " (quote s)
)
 " which has a length of ")
 (to-str le)
)
 ":")
)
)
 (newline)
 (if (> le 1)
 (begin (let ((i 1)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (< i le)
 (begin (let ((cur (substring s i (+ i 1)
)
)
)
 (begin (let ((prev (substring s (- i 1)
 i)
)
)
 (begin (if (not (string=? cur prev)
)
 (begin (_display (to-str "  Not all characters in the string are the same.")
)
 (newline)
 (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append "  " (quote cur)
)
 " (")
 (hex (ord cur)
)
)
 ")
 is different at position ")
 (to-str (+ i 1)
)
)
 ".")
)
)
 (newline)
 (_display (to-str "")
)
 (newline)
 (ret6 (quote ()
)
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
)
)
)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
)
)
)
 (quote ()
)
)
 (_display (to-str "  All characters in the string are the same.")
)
 (newline)
 (_display (to-str "")
)
 (newline)
)
)
)
)
)
(define (main)
 (call/cc (lambda (ret9)
 (let ((strings (_list "" "   " "2" "333" ".55" "tttTTT" "4444 444k" "pépé" "🐶🐶🐺🐶" "🎄🎄🎄🎄")
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda ()
 (if (< i (cond ((string? strings)
 (string-length strings)
)
 ((hash-table? strings)
 (hash-table-size strings)
)
 (else (length strings)
)
)
)
 (begin (analyze (list-ref strings i)
)
 (set! i (+ i 1)
)
 (loop10)
)
 (quote ()
)
)
)
)
)
 (loop10)
)
)
)
)
)
)
)
)
)
)
(main)
