;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start21 (now)
)
)
 (begin (define (pad s width)
 (call/cc (lambda (ret1)
 (let ((out s)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< (cond ((string? out)
 (string-length out)
)
 ((hash-table? out)
 (hash-table-size out)
)
 (else (length out)
)
)
 width)
 (begin (set! out (string-append " " out)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 out)
)
)
)
)
)
 (define (mult n base)
 (call/cc (lambda (ret4)
 (let ((m 1)
)
 (begin (let ((x n)
)
 (begin (let ((b base)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (> x 0)
 (begin (set! m (* m (modulo x b)
)
)
 (set! x (quotient x b)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret4 m)
)
)
)
)
)
)
)
)
)
 (define (multDigitalRoot n base)
 (call/cc (lambda (ret7)
 (let ((m n)
)
 (begin (let ((mp 0)
)
 (begin (let ((b base)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (>= m b)
 (begin (set! m (mult m base)
)
 (set! mp (+ mp 1)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
 (ret7 (alist->hash-table (_list (cons "mp" mp)
 (cons "mdr" (let ((v10 m)
)
 (cond ((string? v10)
 (exact (floor (string->number v10)
)
)
)
 ((boolean? v10)
 (if v10 1 0)
)
 (else (exact (floor v10)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret11)
 (let ((base 10)
)
 (begin (let ((size 5)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (pad "Number" 20)
 " ")
 (pad "MDR" 3)
)
 " ")
 (pad "MP" 3)
)
)
)
 (newline)
 (let ((nums (_list 123321 7739 893 899998 3778888999 277777788888899)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break13)
 (letrec ((loop12 (lambda ()
 (if (< i (cond ((string? nums)
 (string-length nums)
)
 ((hash-table? nums)
 (hash-table-size nums)
)
 (else (length nums)
)
)
)
 (begin (let ((n (list-ref nums i)
)
)
 (begin (let ((r (multDigitalRoot n base)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (pad (to-str n)
 20)
 " ")
 (pad (to-str (hash-table-ref r "mdr")
)
 3)
)
 " ")
 (pad (to-str (hash-table-ref r "mp")
)
 3)
)
)
)
 (newline)
 (set! i (+ i 1)
)
)
)
)
)
 (loop12)
)
 (quote ()
)
)
)
)
)
 (loop12)
)
)
)
 (_display (to-str "")
)
 (newline)
 (let ((list (_list)
)
)
 (begin (let ((idx 0)
)
 (begin (call/cc (lambda (break15)
 (letrec ((loop14 (lambda ()
 (if (< idx base)
 (begin (set! list (append list (_list (_list)
)
)
)
 (set! idx (+ idx 1)
)
 (loop14)
)
 (quote ()
)
)
)
)
)
 (loop14)
)
)
)
 (let ((cnt (* size base)
)
)
 (begin (let ((n 0)
)
 (begin (let ((b base)
)
 (begin (call/cc (lambda (break17)
 (letrec ((loop16 (lambda ()
 (if (> cnt 0)
 (begin (let ((r (multDigitalRoot n base)
)
)
 (begin (let ((mdr (hash-table-ref r "mdr")
)
)
 (begin (if (< (cond ((string? (list-ref list mdr)
)
 (string-length (list-ref list mdr)
)
)
 ((hash-table? (list-ref list mdr)
)
 (hash-table-size (list-ref list mdr)
)
)
 (else (length (list-ref list mdr)
)
)
)
 size)
 (begin (list-set! list mdr (append (list-ref list mdr)
 (_list (let ((v18 n)
)
 (cond ((string? v18)
 (exact (floor (string->number v18)
)
)
)
 ((boolean? v18)
 (if v18 1 0)
)
 (else (exact (floor v18)
)
)
)
)
)
)
)
 (set! cnt (- cnt 1)
)
)
 (quote ()
)
)
 (set! n (+ n 1)
)
)
)
)
)
 (loop16)
)
 (quote ()
)
)
)
)
)
 (loop16)
)
)
)
 (_display (to-str "MDR: First")
)
 (newline)
 (let ((j 0)
)
 (begin (call/cc (lambda (break20)
 (letrec ((loop19 (lambda ()
 (if (< j base)
 (begin (_display (to-str (string-append (string-append (pad (to-str j)
 3)
 ": ")
 (to-str (list-ref list j)
)
)
)
)
 (newline)
 (set! j (+ j 1)
)
 (loop19)
)
 (quote ()
)
)
)
)
)
 (loop19)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end22 (now)
)
)
 (let ((dur23 (quotient (- end22 start21)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur23)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
