;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start12 (now)
)
)
 (begin (define (padRight s w)
 (call/cc (lambda (ret1)
 (let ((r s)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< (cond ((string? r)
 (string-length r)
)
 ((hash-table? r)
 (hash-table-size r)
)
 (else (length r)
)
)
 w)
 (begin (set! r (string-append r " ")
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 r)
)
)
)
)
)
 (define (linearCombo c)
 (call/cc (lambda (ret4)
 (let ((out "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i (cond ((string? c)
 (string-length c)
)
 ((hash-table? c)
 (hash-table-size c)
)
 (else (length c)
)
)
)
 (begin (let ((n (list-ref c i)
)
)
 (begin (if (not (equal? n 0)
)
 (begin (let ((op "")
)
 (begin (if (and (< n 0)
 (equal? (cond ((string? out)
 (string-length out)
)
 ((hash-table? out)
 (hash-table-size out)
)
 (else (length out)
)
)
 0)
)
 (begin (set! op "-")
)
 (if (< n 0)
 (begin (set! op " - ")
)
 (if (and (> n 0)
 (equal? (cond ((string? out)
 (string-length out)
)
 ((hash-table? out)
 (hash-table-size out)
)
 (else (length out)
)
)
 0)
)
 (begin (set! op "")
)
 (begin (set! op " + ")
)
)
)
)
 (let ((av n)
)
 (begin (if (< av 0)
 (begin (set! av (- av)
)
)
 (quote ()
)
)
 (let ((coeff (string-append (to-str av)
 "*")
)
)
 (begin (if (equal? av 1)
 (begin (set! coeff "")
)
 (quote ()
)
)
 (set! out (string-append (string-append (string-append (string-append (string-append out op)
 coeff)
 "e(")
 (to-str (+ i 1)
)
)
 ")
")
)
)
)
)
)
)
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (if (equal? (cond ((string? out)
 (string-length out)
)
 ((hash-table? out)
 (hash-table-size out)
)
 (else (length out)
)
)
 0)
 (begin (ret4 "0")
)
 (quote ()
)
)
 (ret4 out)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret7)
 (let ((combos (_list (_list 1 2 3)
 (_list 0 1 2 3)
 (_list 1 0 3 4)
 (_list 1 2 0)
 (_list 0 0 0)
 (_list 0)
 (_list 1 1 1)
 (_list (- 1)
 (- 1)
 (- 1)
)
 (_list (- 1)
 (- 2)
 0 (- 3)
)
 (_list (- 1)
)
)
)
)
 (begin (let ((idx 0)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (< idx (cond ((string? combos)
 (string-length combos)
)
 ((hash-table? combos)
 (hash-table-size combos)
)
 (else (length combos)
)
)
)
 (begin (let ((c (list-ref combos idx)
)
)
 (begin (let ((t "[")
)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda ()
 (if (< j (cond ((string? c)
 (string-length c)
)
 ((hash-table? c)
 (hash-table-size c)
)
 (else (length c)
)
)
)
 (begin (set! t (string-append t (to-str (list-ref c j)
)
)
)
 (if (_lt j (- (cond ((string? c)
 (string-length c)
)
 ((hash-table? c)
 (hash-table-size c)
)
 (else (length c)
)
)
 1)
)
 (begin (set! t (string-append t ", ")
)
)
 (quote ()
)
)
 (set! j (+ j 1)
)
 (loop10)
)
 (quote ()
)
)
)
)
)
 (loop10)
)
)
)
 (set! t (string-append t "]")
)
 (let ((lc (linearCombo c)
)
)
 (begin (_display (to-str (string-append (string-append (padRight t 15)
 "  ->  ")
 lc)
)
)
 (newline)
 (set! idx (+ idx 1)
)
)
)
)
)
)
)
)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end13 (now)
)
)
 (let ((dur14 (quotient (- end13 start12)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur14)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
