;; Generated on 2025-08-03 10:21 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start9 (now))) (begin (define nodes (alist->hash-table (_list))) (define head (- 0 1)) (define tail (- 0 1)) (define (listString) (call/cc (lambda (ret1) (begin (if (equal? head (- 0 1)) (begin (ret1 "<nil>")) (quote ())) (let ((r (string-append "[" (cond ((string? (hash-table-ref/default nodes head (quote ()))) (_substring (hash-table-ref/default nodes head (quote ())) "value" (+ "value" 1))) ((hash-table? (hash-table-ref/default nodes head (quote ()))) (hash-table-ref (hash-table-ref/default nodes head (quote ())) "value")) (else (list-ref (hash-table-ref/default nodes head (quote ())) "value")))))) (begin (let ((id (let ((v2 (cond ((string? (hash-table-ref/default nodes head (quote ()))) (_substring (hash-table-ref/default nodes head (quote ())) "next" (+ "next" 1))) ((hash-table? (hash-table-ref/default nodes head (quote ()))) (hash-table-ref (hash-table-ref/default nodes head (quote ())) "next")) (else (list-ref (hash-table-ref/default nodes head (quote ())) "next"))))) (cond ((string? v2) (inexact->exact (floor (string->number v2)))) ((boolean? v2) (if v2 1 0)) (else (inexact->exact (floor v2))))))) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda () (if (not (equal? id (- 0 1))) (begin (set! r (string-append (string-append r " ") (cond ((string? (hash-table-ref/default nodes id (quote ()))) (_substring (hash-table-ref/default nodes id (quote ())) "value" (+ "value" 1))) ((hash-table? (hash-table-ref/default nodes id (quote ()))) (hash-table-ref (hash-table-ref/default nodes id (quote ())) "value")) (else (list-ref (hash-table-ref/default nodes id (quote ())) "value"))))) (set! id (let ((v5 (cond ((string? (hash-table-ref/default nodes id (quote ()))) (_substring (hash-table-ref/default nodes id (quote ())) "next" (+ "next" 1))) ((hash-table? (hash-table-ref/default nodes id (quote ()))) (hash-table-ref (hash-table-ref/default nodes id (quote ())) "next")) (else (list-ref (hash-table-ref/default nodes id (quote ())) "next"))))) (cond ((string? v5) (inexact->exact (floor (string->number v5)))) ((boolean? v5) (if v5 1 0)) (else (inexact->exact (floor v5)))))) (loop3)) (quote ()))))) (loop3)))) (set! r (string-append r "]")) (ret1 r))))))))) (_display (to-str (listString))) (newline) (hash-table-set! nodes 0 (alist->hash-table (_list (cons "value" "A") (cons "next" (- 0 1)) (cons "prev" (- 0 1))))) (set! head 0) (set! tail 0) (hash-table-set! nodes 1 (alist->hash-table (_list (cons "value" "B") (cons "next" (- 0 1)) (cons "prev" 0)))) (hash-table-set! (hash-table-ref nodes 0) "next" 1) (set! tail 1) (_display (to-str (listString))) (newline) (hash-table-set! nodes 2 (alist->hash-table (_list (cons "value" "C") (cons "next" 1) (cons "prev" 0)))) (hash-table-set! (hash-table-ref nodes 1) "prev" 2) (hash-table-set! (hash-table-ref nodes 0) "next" 2) (_display (to-str (listString))) (newline) (define out "From tail:") (define id tail) (call/cc (lambda (break7) (letrec ((loop6 (lambda () (if (not (equal? id (- 0 1))) (begin (set! out (string-append (string-append out " ") (cond ((string? (hash-table-ref/default nodes id (quote ()))) (_substring (hash-table-ref/default nodes id (quote ())) "value" (+ "value" 1))) ((hash-table? (hash-table-ref/default nodes id (quote ()))) (hash-table-ref (hash-table-ref/default nodes id (quote ())) "value")) (else (list-ref (hash-table-ref/default nodes id (quote ())) "value"))))) (set! id (let ((v8 (cond ((string? (hash-table-ref/default nodes id (quote ()))) (_substring (hash-table-ref/default nodes id (quote ())) "prev" (+ "prev" 1))) ((hash-table? (hash-table-ref/default nodes id (quote ()))) (hash-table-ref (hash-table-ref/default nodes id (quote ())) "prev")) (else (list-ref (hash-table-ref/default nodes id (quote ())) "prev"))))) (cond ((string? v8) (inexact->exact (floor (string->number v8)))) ((boolean? v8) (if v8 1 0)) (else (inexact->exact (floor v8)))))) (loop6)) (quote ()))))) (loop6)))) (_display (to-str out)) (newline) (let ((end10 (now))) (let ((dur11 (quotient (- end10 start9) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur11) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
