;; Generated on 2025-08-03 10:21 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start14 (now))) (begin (define (repeat ch n) (call/cc (lambda (ret1) (let ((s "")) (begin (let ((i 0)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (< i n) (begin (set! s (string-append s ch)) (set! i (+ i 1)) (loop2)) (quote ()))))) (loop2)))) (ret1 s)))))))) (define (cubLine n dx dy cde) (call/cc (lambda (ret4) (let ((line (string-append (repeat " " (+ n 1)) (_substring cde 0 1)))) (begin (let ((d (- (* 9 dx) 1))) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (> d 0) (begin (set! line (string-append line (_substring cde 1 2))) (set! d (- d 1)) (loop5)) (quote ()))))) (loop5)))) (set! line (string-append line (_substring cde 0 1))) (set! line (string-append (_add line (repeat " " dy)) (_substring cde 2 (string-length cde)))) (_display (to-str line)) (newline)))))))) (define (cuboid dx dy dz) (call/cc (lambda (ret7) (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append "cuboid " (to-str dx)) " ") (to-str dy)) " ") (to-str dz)) ":"))) (newline) (cubLine (+ dy 1) dx 0 "+-") (let ((i 1)) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (<= i dy) (begin (cubLine (_add (- dy i) 1) dx (- i 1) "/ |") (set! i (+ i 1)) (loop8)) (quote ()))))) (loop8)))) (cubLine 0 dx dy "+-|") (let ((j (- (- (* 4 dz) dy) 2))) (begin (call/cc (lambda (break11) (letrec ((loop10 (lambda () (if (> j 0) (begin (cubLine 0 dx dy "| |") (set! j (- j 1)) (loop10)) (quote ()))))) (loop10)))) (cubLine 0 dx dy "| +") (set! i 1) (call/cc (lambda (break13) (letrec ((loop12 (lambda () (if (<= i dy) (begin (cubLine 0 dx (- dy i) "| /") (set! i (+ i 1)) (loop12)) (quote ()))))) (loop12)))) (cubLine 0 dx 0 "+-\n"))))))))) (cuboid 2 3 4) (_display (to-str "")) (newline) (cuboid 1 1 1) (_display (to-str "")) (newline) (cuboid 6 2 1) (let ((end15 (now))) (let ((dur16 (quotient (- end15 start14) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur16) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
