;; Generated on 2025-08-03 10:21 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start16 (now))) (begin (define (sqrtApprox x) (call/cc (lambda (ret1) (begin (if (<= x 0.0) (begin (ret1 0.0)) (quote ())) (let ((guess x)) (begin (let ((i 0)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (< i 20) (begin (set! guess (/ (_add guess (/ x guess)) 2.0)) (set! i (+ i 1)) (loop2)) (quote ()))))) (loop2)))) (ret1 guess))))))))) (define (powf base exp) (call/cc (lambda (ret4) (let ((result 1.0)) (begin (let ((i 0)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (< i exp) (begin (set! result (* result base)) (set! i (+ i 1)) (loop5)) (quote ()))))) (loop5)))) (ret4 result)))))))) (define (normalize v) (call/cc (lambda (ret7) (let ((len (sqrtApprox (_add (_add (* (hash-table-ref v "x") (hash-table-ref v "x")) (* (hash-table-ref v "y") (hash-table-ref v "y"))) (* (hash-table-ref v "z") (hash-table-ref v "z")))))) (begin (ret7 (alist->hash-table (_list (cons "x" (/ (hash-table-ref v "x") len)) (cons "y" (/ (hash-table-ref v "y") len)) (cons "z" (/ (hash-table-ref v "z") len)))))))))) (define (dot a b) (call/cc (lambda (ret8) (let ((d (_add (_add (* (hash-table-ref a "x") (hash-table-ref b "x")) (* (hash-table-ref a "y") (hash-table-ref b "y"))) (* (hash-table-ref a "z") (hash-table-ref b "z"))))) (begin (if (< d 0.0) (begin (ret8 (- d))) (quote ())) (ret8 0.0)))))) (define (drawSphere r k ambient light shades) (call/cc (lambda (ret9) (let ((i (- r))) (begin (call/cc (lambda (break11) (letrec ((loop10 (lambda () (if (<= i r) (begin (let ((x (+ (+ 0.0 i) 0.5))) (begin (let ((line "")) (begin (let ((j (- (* 2 r)))) (begin (call/cc (lambda (break13) (letrec ((loop12 (lambda () (if (_le j (* 2 r)) (begin (let ((y (_add (/ (+ 0.0 j) 2.0) 0.5))) (begin (if (_le (_add (* x x) (* y y)) (* (+ 0.0 r) (+ 0.0 r))) (begin (let ((zsq (- (- (* (+ 0.0 r) (+ 0.0 r)) (* x x)) (* y y)))) (begin (let ((vec (normalize (alist->hash-table (_list (cons "x" x) (cons "y" y) (cons "z" (sqrtApprox zsq))))))) (begin (let ((b (_add (powf (dot light vec) k) ambient))) (begin (let ((intensity (let ((v14 (* (- 1.0 b) (- (+ 0.0 (cond ((string? shades) (string-length shades)) ((hash-table? shades) (hash-table-size shades)) (else (length shades)))) 1.0)))) (cond ((string? v14) (inexact->exact (floor (string->number v14)))) ((boolean? v14) (if v14 1 0)) (else (inexact->exact (floor v14))))))) (begin (if (< intensity 0) (begin (set! intensity 0)) (quote ())) (if (>= intensity (cond ((string? shades) (string-length shades)) ((hash-table? shades) (hash-table-size shades)) (else (length shades)))) (begin (set! intensity (- (cond ((string? shades) (string-length shades)) ((hash-table? shades) (hash-table-size shades)) (else (length shades))) 1))) (quote ())) (set! line (string-append line (_substring shades intensity (+ intensity 1))))))))))))) (begin (set! line (string-append line " ")))) (set! j (+ j 1)))) (loop12)) (quote ()))))) (loop12)))) (_display (to-str line)) (newline) (set! i (+ i 1)))))))) (loop10)) (quote ()))))) (loop10))))))))) (define (main) (call/cc (lambda (ret15) (let ((shades ".:!*oe&#%@")) (begin (let ((light (normalize (alist->hash-table (_list (cons "x" 30.0) (cons "y" 30.0) (cons "z" (- 50.0))))))) (begin (drawSphere 20 4 0.1 light shades) (drawSphere 10 2 0.4 light shades)))))))) (main) (let ((end17 (now))) (let ((dur18 (quotient (- end17 start16) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur18) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
