;; Generated on 2025-08-03 10:21 +0700
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (srfi 1))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start20 (now))) (begin (define (pow2 n) (call/cc (lambda (ret1) (let ((p 1)) (begin (let ((i 0)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (< i n) (begin (set! p (* p 2)) (set! i (+ i 1)) (loop2)) (quote ()))))) (loop2)))) (ret1 p)))))))) (define (btoi b) (call/cc (lambda (ret4) (begin (if b (begin (ret4 1)) (quote ())) (ret4 0))))) (define (addNoCells cells) (call/cc (lambda (ret5) (let ((l "O")) (begin (let ((r "O")) (begin (if (string=? (_substring cells 0 1) "O") (begin (set! l ".")) (quote ())) (if (string=? (_substring cells (- (cond ((string? cells) (string-length cells)) ((hash-table? cells) (hash-table-size cells)) (else (length cells))) 1) (cond ((string? cells) (string-length cells)) ((hash-table? cells) (hash-table-size cells)) (else (length cells)))) "O") (begin (set! r ".")) (quote ())) (set! cells (string-append (string-append l cells) r)) (set! cells (string-append (string-append l cells) r)) (ret5 cells)))))))) (define (step cells ruleVal) (call/cc (lambda (ret6) (let ((newCells "")) (begin (let ((i 0)) (begin (call/cc (lambda (break8) (letrec ((loop7 (lambda () (if (_lt i (- (cond ((string? cells) (string-length cells)) ((hash-table? cells) (hash-table-size cells)) (else (length cells))) 2)) (begin (let ((bin 0)) (begin (let ((b 2)) (begin (let ((n i)) (begin (call/cc (lambda (break10) (letrec ((loop9 (lambda () (if (_lt n (+ i 3)) (begin (set! bin (_add bin (* (btoi (string=? (_substring cells n (+ n 1)) "O")) (pow2 b)))) (set! b (- b 1)) (set! n (+ n 1)) (loop9)) (quote ()))))) (loop9)))) (let ((a ".")) (begin (if (equal? (fmod (/ ruleVal (pow2 bin)) 2) 1) (begin (set! a "O")) (quote ())) (set! newCells (string-append newCells a)) (set! i (+ i 1)))))))))) (loop7)) (quote ()))))) (loop7)))) (ret6 newCells)))))))) (define (repeat ch n) (call/cc (lambda (ret11) (let ((s "")) (begin (let ((i 0)) (begin (call/cc (lambda (break13) (letrec ((loop12 (lambda () (if (< i n) (begin (set! s (string-append s ch)) (set! i (+ i 1)) (loop12)) (quote ()))))) (loop12)))) (ret11 s)))))))) (define (evolve l ruleVal) (call/cc (lambda (ret14) (begin (_display (to-str (string-append (string-append " Rule #" (to-str ruleVal)) ":"))) (newline) (let ((cells "O")) (begin (let ((x 0)) (begin (call/cc (lambda (break16) (letrec ((loop15 (lambda () (if (< x l) (begin (set! cells (addNoCells cells)) (let ((width (+ 40 (quotient (cond ((string? cells) (string-length cells)) ((hash-table? cells) (hash-table-size cells)) (else (length cells))) 2)))) (begin (let ((spaces (repeat " " (- width (cond ((string? cells) (string-length cells)) ((hash-table? cells) (hash-table-size cells)) (else (length cells))))))) (begin (_display (to-str (string-append spaces cells))) (newline) (set! cells (step cells ruleVal)) (set! x (+ x 1)))))) (loop15)) (quote ()))))) (loop15)))))))))))) (define (main) (call/cc (lambda (ret17) (call/cc (lambda (break19) (letrec ((loop18 (lambda (xs) (if (null? xs) (quote ()) (begin (let ((r (car xs))) (begin (evolve 25 r) (_display (to-str "")) (newline))) (loop18 (cdr xs))))))) (loop18 (_list 90 30)))))))) (main) (let ((end21 (now))) (let ((dur22 (quotient (- end21 start20) 1000))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur22) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
