;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start3 (now)
)
)
 (begin (define (isEmptyDir fs name)
 (call/cc (lambda (ret1)
 (begin (if (cond ((string? fs)
 (if (string-contains fs name)
 #t #f)
)
 ((hash-table? fs)
 (if (hash-table-exists? fs name)
 #t #f)
)
 (else (if (member name fs)
 #t #f)
)
)
 (begin (ret1 (equal? (cond ((string? (hash-table-ref/default fs name (quote ()
)
)
)
 (string-length (hash-table-ref/default fs name (quote ()
)
)
)
)
 ((hash-table? (hash-table-ref/default fs name (quote ()
)
)
)
 (hash-table-size (hash-table-ref/default fs name (quote ()
)
)
)
)
 (else (length (hash-table-ref/default fs name (quote ()
)
)
)
)
)
 0)
)
)
 (quote ()
)
)
 (ret1 #t)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret2)
 (let ((fs (alist->hash-table (_list)
)
)
)
 (begin (hash-table-set! fs "/tmp" (_list)
)
 (hash-table-set! fs "/var" (_list "log")
)
 (if (isEmptyDir fs "/tmp")
 (begin (_display (to-str "/tmp is empty")
)
 (newline)
)
 (begin (_display (to-str "/tmp is not empty")
)
 (newline)
)
)
)
)
)
)
)
 (main)
 (let ((end4 (now)
)
)
 (let ((dur5 (quotient (- end4 start3)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur5)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
