;; Generated on 2025-07-28 10:03 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(let ((start14 (now)
)
)
 (begin (define (log2 x)
 (call/cc (lambda (ret1)
 (let ((k 0.0)
)
 (begin (let ((v x)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (>= v 2.0)
 (begin (set! v (/ v 2.0)
)
 (set! k (+ k 1.0)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (call/cc (lambda (break5)
 (letrec ((loop4 (lambda ()
 (if (< v 1.0)
 (begin (set! v (* v 2.0)
)
 (set! k (- k 1.0)
)
 (loop4)
)
 (quote ()
)
)
)
)
)
 (loop4)
)
)
)
 (let ((z (/ (- v 1.0)
 (+ v 1.0)
)
)
)
 (begin (let ((zpow z)
)
 (begin (let ((sum z)
)
 (begin (let ((i 3)
)
 (begin (call/cc (lambda (break7)
 (letrec ((loop6 (lambda ()
 (if (<= i 9)
 (begin (set! zpow (* (* zpow z)
 z)
)
 (set! sum (_add sum (/ zpow i)
)
)
 (set! i (+ i 2)
)
 (loop6)
)
 (quote ()
)
)
)
)
)
 (loop6)
)
)
)
 (let ((ln2 0.6931471805599453)
)
 (begin (ret1 (_add k (/ (* 2.0 sum)
 ln2)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (H data)
 (call/cc (lambda (ret8)
 (begin (if (string=? data "")
 (begin (ret8 0.0)
)
 (quote ()
)
)
 (let ((counts (alist->hash-table (_list)
)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if (< i (cond ((string? data)
 (string-length data)
)
 ((hash-table? data)
 (hash-table-size data)
)
 (else (length data)
)
)
)
 (begin (let ((ch (substring data i (+ i 1)
)
)
)
 (begin (if (cond ((string? counts)
 (if (string-contains counts ch)
 #t #f)
)
 ((hash-table? counts)
 (if (hash-table-exists? counts ch)
 #t #f)
)
 (else (if (member ch counts)
 #t #f)
)
)
 (begin (hash-table-set! counts ch (+ (hash-table-ref/default counts ch (quote ()
)
)
 1)
)
)
 (begin (hash-table-set! counts ch 1)
)
)
 (set! i (+ i 1)
)
)
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
 (let ((entropy 0.0)
)
 (begin (let ((l (cond ((string? data)
 (string-length data)
)
 ((hash-table? data)
 (hash-table-size data)
)
 (else (length data)
)
)
)
)
 (begin (call/cc (lambda (break12)
 (letrec ((loop11 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((ch (car xs)
)
)
 (begin (let ((px (/ (hash-table-ref/default counts ch (quote ()
)
)
 l)
)
)
 (begin (if (> px 0.0)
 (begin (set! entropy (- entropy (* px (log2 px)
)
)
)
)
 (quote ()
)
)
)
)
)
)
 (loop11 (cdr xs)
)
)
)
)
)
)
 (loop11 (hash-table-keys counts)
)
)
)
)
 (ret8 entropy)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret13)
 (begin (_display (to-str (to-str (H "1223334444")
)
)
)
 (newline)
)
)
)
)
 (main)
 (let ((end15 (now)
)
)
 (let ((dur16 (quotient (- end15 start14)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur16)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
