;; Generated on 2025-08-04 08:17 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start11 (current-jiffy)) (jps14 (jiffies-per-second))) (begin (define PI 3.141592653589793) (define (sinApprox x) (call/cc (lambda (ret1) (let ((term x)) (begin (let ((sum x)) (begin (let ((n 1)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (<= n 10) (begin (let ((denom (+ 0.0 (* (* 2 n) (_add (* 2 n) 1))))) (begin (set! term (/ (* (* (- term) x) x) denom)) (set! sum (+ sum term)) (set! n (+ n 1)))) (loop2)) (quote ()))))) (loop2)))) (ret1 sum)))))))))) (define (cosApprox x) (call/cc (lambda (ret4) (let ((term 1.0)) (begin (let ((sum 1.0)) (begin (let ((n 1)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (<= n 10) (begin (let ((denom (+ 0.0 (* (- (* 2 n) 1) (* 2 n))))) (begin (set! term (/ (* (* (- term) x) x) denom)) (set! sum (+ sum term)) (set! n (+ n 1)))) (loop5)) (quote ()))))) (loop5)))) (ret4 sum)))))))))) (define (cis x) (call/cc (lambda (ret7) (ret7 (alist->hash-table (_list (cons "re" (cosApprox x)) (cons "im" (sinApprox x)))))))) (define (add a b) (call/cc (lambda (ret8) (ret8 (alist->hash-table (_list (cons "re" (+ (hash-table-ref a "re") (hash-table-ref b "re"))) (cons "im" (+ (hash-table-ref a "im") (hash-table-ref b "im"))))))))) (define (cstr a) (call/cc (lambda (ret9) (let ((s (string-append "(" (to-str (hash-table-ref a "re"))))) (begin (if (>= (hash-table-ref a "im") 0) (begin (set! s (string-append (string-append (string-append s "+") (to-str (hash-table-ref a "im"))) "i)"))) (begin (set! s (string-append (string-append s (to-str (hash-table-ref a "im"))) "i)")))) (ret9 s)))))) (define (main) (call/cc (lambda (ret10) (let ((result (add (cis PI) (alist->hash-table (_list (cons "re" 1.0) (cons "im" 0.0)))))) (begin (_display (to-str (cstr result))) (newline)))))) (main) (let ((end12 (current-jiffy))) (let ((dur13 (quotient (* (- end12 start11) 1000000) jps14))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur13) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
