;; Generated on 2025-08-04 08:09 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(let ((start12 (current-jiffy)) (jps15 (jiffies-per-second))) (begin (define (ln x) (call/cc (lambda (ret1) (let ((k 0.0)) (begin (let ((v x)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (>= v 2.0) (begin (set! v (/ v 2.0)) (set! k (+ k 1.0)) (loop2)) (quote ()))))) (loop2)))) (call/cc (lambda (break5) (letrec ((loop4 (lambda () (if (< v 1.0) (begin (set! v (* v 2.0)) (set! k (- k 1.0)) (loop4)) (quote ()))))) (loop4)))) (let ((z (/ (- v 1.0) (+ v 1.0)))) (begin (let ((zpow z)) (begin (let ((sum z)) (begin (let ((i 3)) (begin (call/cc (lambda (break7) (letrec ((loop6 (lambda () (if (<= i 9) (begin (set! zpow (* (* zpow z) z)) (set! sum (_add sum (/ zpow (+ 0.0 i)))) (set! i (+ i 2)) (loop6)) (quote ()))))) (loop6)))) (let ((ln2 0.6931471805599453)) (begin (ret1 (_add (* k ln2) (* 2.0 sum)))))))))))))))))))) (define (harmonic n) (call/cc (lambda (ret8) (let ((sum 0.0)) (begin (let ((i 1)) (begin (call/cc (lambda (break10) (letrec ((loop9 (lambda () (if (<= i n) (begin (set! sum (_add sum (/ 1.0 (+ 0.0 i)))) (set! i (+ i 1)) (loop9)) (quote ()))))) (loop9)))) (ret8 sum)))))))) (define (main) (call/cc (lambda (ret11) (let ((n 100000)) (begin (let ((gamma (- (harmonic n) (ln (+ 0.0 n))))) (begin (_display (to-str (to-str gamma))) (newline)))))))) (main) (let ((end13 (current-jiffy))) (let ((dur14 (quotient (* (- end13 start12) 1000000) jps15))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur14) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
