;; Generated on 2025-08-04 09:21 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(let ((start12 (current-jiffy)) (jps15 (jiffies-per-second))) (begin (define (chr n) (call/cc (lambda (ret1) (let ((upper "ABCDEFGHIJKLMNOPQRSTUVWXYZ")) (begin (let ((lower "abcdefghijklmnopqrstuvwxyz")) (begin (if (and (>= n 65) (< n 91)) (begin (ret1 (_substring upper (- n 65) (- n 64)))) (quote ())) (if (and (>= n 97) (< n 123)) (begin (ret1 (_substring lower (- n 97) (- n 96)))) (quote ())) (if (equal? n 32) (begin (ret1 " ")) (quote ())) (if (equal? n 33) (begin (ret1 "!")) (quote ())) (if (equal? n 44) (begin (ret1 ",")) (quote ())) (if (equal? n 13) (begin (ret1 "")) (quote ())) (if (equal? n 10) (begin (ret1 "\n")) (quote ())) (ret1 "?")))))))) (define (bf dLen code) (call/cc (lambda (ret2) (let ((ds (_list))) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda (i) (if (< i dLen) (begin (begin (set! ds (append ds (_list 0)))) (loop3 (+ i 1))) (quote ()))))) (loop3 0)))) (let ((dp 0)) (begin (let ((ip 0)) (begin (let ((out "")) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (< ip (_len code)) (begin (let ((ch (_substring code ip (+ ip 1)))) (begin (if (string=? ch ">") (begin (set! dp (+ dp 1))) (if (string=? ch "<") (begin (set! dp (- dp 1))) (if (string=? ch "+") (begin (list-set! ds dp (+ (list-ref ds dp) 1))) (if (string=? ch "-") (begin (list-set! ds dp (- (list-ref ds dp) 1))) (if (string=? ch ".") (begin (set! out (string-append out (chr (list-ref ds dp))))) (if (string=? ch ",") (begin) (if (string=? ch "[") (begin (if (equal? (list-ref ds dp) 0) (begin (let ((nc 1)) (begin (call/cc (lambda (break8) (letrec ((loop7 (lambda () (if (> nc 0) (begin (set! ip (+ ip 1)) (let ((cc (_substring code ip (+ ip 1)))) (begin (if (string=? cc "[") (begin (set! nc (+ nc 1))) (if (string=? cc "]") (begin (set! nc (- nc 1))) (quote ()))))) (loop7)) (quote ()))))) (loop7))))))) (quote ()))) (if (string=? ch "]") (begin (if (not (equal? (list-ref ds dp) 0)) (begin (let ((nc 1)) (begin (call/cc (lambda (break10) (letrec ((loop9 (lambda () (if (> nc 0) (begin (set! ip (- ip 1)) (let ((cc (_substring code ip (+ ip 1)))) (begin (if (string=? cc "]") (begin (set! nc (+ nc 1))) (if (string=? cc "[") (begin (set! nc (- nc 1))) (quote ()))))) (loop9)) (quote ()))))) (loop9))))))) (quote ()))) (quote ()))))))))) (set! ip (+ ip 1)))) (loop5)) (quote ()))))) (loop5)))) (ret2 out)))))))))))) (define (main) (call/cc (lambda (ret11) (let ((prog "++++++++++[>+>+++>++++>+++++++>++++++++>+++++++++>++\n++++++++>+++++++++++>++++++++++++<<<<<<<<<-]>>>>+.>>>\n>+..<.<++++++++.>>>+.<<+.<<<<++++.<++.>>>+++++++.>>>.+++.\n<+++++++.--------.<<<<<+.<+++.---.")) (begin (let ((out (bf 10 prog))) (begin (_display (to-str out)) (newline)))))))) (main) (let ((end13 (current-jiffy))) (let ((dur14 (quotient (* (- end13 start12) 1000000) jps15))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur14) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
