;; Generated on 2025-08-04 08:17 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(define (hailstone n) (call/cc (lambda (ret1) (let ((seq (_list))) (begin (let ((x n)) (begin (set! seq (append seq (_list x))) (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (> x 1) (begin (if (equal? (modulo x 2) 0) (begin (set! x (quotient x 2))) (begin (set! x (_add (* 3 x) 1)))) (set! seq (append seq (_list x))) (loop2)) (quote ()))))) (loop2)))) (ret1 seq))))))))
(define (listString xs) (call/cc (lambda (ret4) (let ((s "[")) (begin (let ((i 0)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (< i (_len xs)) (begin (set! s (string-append s (to-str (list-ref xs i)))) (if (_lt i (- (_len xs) 1)) (begin (set! s (string-append s " "))) (quote ())) (set! i (+ i 1)) (loop5)) (quote ()))))) (loop5)))) (set! s (string-append s "]")) (ret4 s))))))))
(define (libMain) (call/cc (lambda (ret7) (let ((seq (hailstone 27))) (begin (_display (to-str "")) (newline) (_display (to-str "Hailstone sequence for the number 27:")) (newline) (_display (to-str (string-append (string-append "  has " (to-str (_len seq))) " elements"))) (newline) (_display (to-str (string-append "  starts with " (listString (if (string? seq) (_substring seq 0 4) (take (drop seq 0) (- 4 0))))))) (newline) (_display (to-str (string-append "  ends with " (listString (if (string? seq) (_substring seq (- (_len seq) 4) (_len seq)) (take (drop seq (- (_len seq) 4)) (- (_len seq) (- (_len seq) 4)))))))) (newline) (let ((longest 0)) (begin (let ((length 0)) (begin (let ((i 1)) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (< i 100000) (begin (let ((l (_len (hailstone i)))) (begin (if (> l length) (begin (set! longest i) (set! length l)) (quote ())) (set! i (+ i 1)))) (loop8)) (quote ()))))) (loop8)))) (_display (to-str "")) (newline) (_display (to-str (string-append (string-append (string-append (to-str longest) " has the longest Hailstone sequence, its length being ") (to-str length)) "."))) (newline))))))))))))
(libMain)
