;; Generated on 2025-08-04 09:21 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(let ((start8 (current-jiffy)) (jps11 (jiffies-per-second))) (begin (define (floorMod a b) (call/cc (lambda (ret1) (let ((r (modulo a b))) (begin (if (< r 0) (begin (set! r (+ r b))) (quote ())) (ret1 r)))))) (define (run bc) (call/cc (lambda (ret2) (let ((acc 0)) (begin (let ((pc 0)) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda () (if (< pc 32) (begin (let ((op (quotient (list-ref bc pc) 32))) (begin (let ((arg (modulo (list-ref bc pc) 32))) (begin (set! pc (+ pc 1)) (if (equal? op 0) (begin) (if (equal? op 1) (begin (set! acc (list-ref bc arg))) (if (equal? op 2) (begin (list-set! bc arg acc)) (if (equal? op 3) (begin (set! acc (floorMod (+ acc (list-ref bc arg)) 256))) (if (equal? op 4) (begin (set! acc (floorMod (- acc (list-ref bc arg)) 256))) (if (equal? op 5) (begin (if (equal? acc 0) (begin (set! pc arg)) (quote ()))) (if (equal? op 6) (begin (set! pc arg)) (if (equal? op 7) (begin (break4 (quote ()))) (begin (break4 (quote ()))))))))))))))) (loop3)) (quote ()))))) (loop3)))) (ret2 acc)))))))) (define (main) (call/cc (lambda (ret5) (let ((programs (_list (_list 35 100 224 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) (_list 44 106 76 43 141 75 168 192 44 224 8 7 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) (_list 46 79 109 78 47 77 48 145 171 80 192 46 224 1 1 0 8 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0) (_list 45 111 69 112 71 0 78 0 171 79 192 46 224 32 0 28 1 0 0 0 6 0 2 26 5 20 3 30 1 22 4 24) (_list 35 132 224 0 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) (_list 35 132 224 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) (_list 35 100 224 1 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)))) (begin (let ((i 0)) (begin (call/cc (lambda (break7) (letrec ((loop6 (lambda () (if (< i (_len programs)) (begin (let ((res (run (list-ref programs i)))) (begin (_display (to-str (to-str res))) (newline) (set! i (+ i 1)))) (loop6)) (quote ()))))) (loop6))))))))))) (main) (let ((end9 (current-jiffy))) (let ((dur10 (quotient (* (- end9 start8) 1000000) jps11))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur10) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
