;; Generated on 2025-08-04 09:21 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(let ((start13 (current-jiffy)) (jps16 (jiffies-per-second))) (begin (define (p x e) (call/cc (lambda (ret1) (let ((r 1.0)) (begin (let ((i 0)) (begin (call/cc (lambda (break4) (letrec ((loop3 (lambda () (if (< i (let ((v2 e)) (cond ((string? v2) (inexact->exact (floor (string->number v2)))) ((boolean? v2) (if v2 1 0)) (else (inexact->exact (floor v2)))))) (begin (set! r (* r x)) (set! i (+ i 1)) (loop3)) (quote ()))))) (loop3)))) (ret1 r)))))))) (define (padInt f) (call/cc (lambda (ret5) (let ((s (to-str (let ((v6 f)) (cond ((string? v6) (inexact->exact (floor (string->number v6)))) ((boolean? v6) (if v6 1 0)) (else (inexact->exact (floor v6)))))))) (begin (if (>= f 0) (begin (ret5 (string-append " " s))) (quote ())) (ret5 s)))))) (define ops (_list "-x.p(e)" "-(x).p(e)" "(-x).p(e)" "-(x.p(e))")) (call/cc (lambda (break8) (letrec ((loop7 (lambda (xs) (if (null? xs) (quote ()) (begin (let ((x (car xs))) (begin (call/cc (lambda (break10) (letrec ((loop9 (lambda (xs) (if (null? xs) (quote ()) (begin (let ((e (car xs))) (begin (let ((a (- (p x e)))) (begin (let ((b (- (p x e)))) (begin (let ((c (p (- x) e))) (begin (let ((d (- (p x e)))) (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append (string-append "x = " (if (_lt x 0) "" " ")) (to-str (let ((v11 x)) (cond ((string? v11) (inexact->exact (floor (string->number v11)))) ((boolean? v11) (if v11 1 0)) (else (inexact->exact (floor v11))))))) " e = ") (to-str (let ((v12 e)) (cond ((string? v12) (inexact->exact (floor (string->number v12)))) ((boolean? v12) (if v12 1 0)) (else (inexact->exact (floor v12))))))) " | ") (list-ref ops 0)) " = ") (padInt a)) " | ") (list-ref ops 1)) " = ") (padInt b)) " | ") (list-ref ops 2)) " = ") (padInt c)) " | ") (list-ref ops 3)) " = ") (padInt d)))) (newline))))))))))) (loop9 (cdr xs))))))) (loop9 (_list 2.0 3.0))))))) (loop7 (cdr xs))))))) (loop7 (_list (- 5.0) 5.0))))) (let ((end14 (current-jiffy))) (let ((dur15 (quotient (* (- end14 start13) 1000000) jps16))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur15) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
