;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start12 (now)
)
)
 (begin (define FASTA (string-append (string-append (string-append (string-append (string-append ">Rosetta_Example_1\n" "THERECANBENOSPACE\n")
 ">Rosetta_Example_2\n")
 "THERECANBESEVERAL\n")
 "LINESBUTTHEYALLMUST\n")
 "BECONCATENATED")
)
 (define (splitLines s)
 (call/cc (lambda (ret1)
 (let ((lines (_list)
)
)
 (begin (let ((start 0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (if (string=? (substring s i (+ i 1)
)
 "\n")
 (begin (set! lines (append lines (_list (substring s start i)
)
)
)
 (set! i (+ i 1)
)
 (set! start i)
)
 (begin (set! i (+ i 1)
)
)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (set! lines (append lines (_list (substring s start (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
)
)
)
 (ret1 lines)
)
)
)
)
)
)
)
)
)
 (define (parseFasta text)
 (call/cc (lambda (ret4)
 (let ((key "")
)
 (begin (let ((val "")
)
 (begin (let ((out (_list)
)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((line (car xs)
)
)
 (begin (if (string=? line "")
 (begin (loop5 (cdr xs)
)
)
 (quote ()
)
)
 (if (string=? (substring line 0 1)
 ">")
 (begin (if (not (string=? key "")
)
 (begin (set! out (append out (_list (string-append (string-append key ": ")
 val)
)
)
)
)
 (quote ()
)
)
 (let ((hdr (substring line 1 (cond ((string? line)
 (string-length line)
)
 ((hash-table? line)
 (hash-table-size line)
)
 (else (length line)
)
)
)
)
)
 (begin (let ((idx 0)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (and (< idx (cond ((string? hdr)
 (string-length hdr)
)
 ((hash-table? hdr)
 (hash-table-size hdr)
)
 (else (length hdr)
)
)
)
 (not (string=? (substring hdr idx (+ idx 1)
)
 " ")
)
)
 (begin (set! idx (+ idx 1)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
 (set! key (substring hdr 0 idx)
)
 (set! val "")
)
)
)
)
)
 (begin (if (string=? key "")
 (begin (_display (to-str "missing header")
)
 (newline)
 (ret4 (_list)
)
)
 (quote ()
)
)
 (set! val (string-append val line)
)
)
)
)
)
 (loop5 (cdr xs)
)
)
)
)
)
)
 (loop5 (splitLines text)
)
)
)
)
 (if (not (string=? key "")
)
 (begin (set! out (append out (_list (string-append (string-append key ": ")
 val)
)
)
)
)
 (quote ()
)
)
 (ret4 out)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret9)
 (let ((res (parseFasta FASTA)
)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((line (car xs)
)
)
 (begin (_display (to-str line)
)
 (newline)
)
)
 (loop10 (cdr xs)
)
)
)
)
)
)
 (loop10 res)
)
)
)
)
)
)
)
)
 (main)
 (let ((end13 (now)
)
)
 (let ((dur14 (quotient (- end13 start12)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur14)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
