;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start15 (now)
)
)
 (begin (define (bernoulli n)
 (call/cc (lambda (ret1)
 (let ((a (_list)
)
)
 (begin (let ((m 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (<= m n)
 (begin (set! a (append a (_list (/ 1 (+ m 1)
)
)
)
)
 (let ((j m)
)
 (begin (call/cc (lambda (break5)
 (letrec ((loop4 (lambda ()
 (if (>= j 1)
 (begin (list-set! a (- j 1)
 (* j (- (list-ref a (- j 1)
)
 (list-ref a j)
)
)
)
 (set! j (- j 1)
)
 (loop4)
)
 (quote ()
)
)
)
)
)
 (loop4)
)
)
)
 (set! m (+ m 1)
)
)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 (list-ref a 0)
)
)
)
)
)
)
)
)
 (define (binom n k)
 (call/cc (lambda (ret6)
 (begin (if (or (< k 0)
 (> k n)
)
 (begin (ret6 0)
)
 (quote ()
)
)
 (let ((kk k)
)
 (begin (if (_gt kk (- n kk)
)
 (begin (set! kk (- n kk)
)
)
 (quote ()
)
)
 (let ((res 1)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (< i kk)
 (begin (set! res (* res (- n i)
)
)
 (set! i (+ i 1)
)
 (set! res (/ res i)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
 (ret6 res)
)
)
)
)
)
)
)
)
)
)
 (define (coeff p j)
 (call/cc (lambda (ret9)
 (let ((base (/ 1 (+ p 1)
)
)
)
 (begin (let ((c base)
)
 (begin (if (equal? (modulo j 2)
 1)
 (begin (set! c (- c)
)
)
 (quote ()
)
)
 (set! c (* c (binom (+ p 1)
 j)
)
)
 (set! c (* c (bernoulli j)
)
)
 (ret9 c)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret10)
 (let ((p 0)
)
 (begin (call/cc (lambda (break12)
 (letrec ((loop11 (lambda ()
 (if (< p 10)
 (begin (let ((line (string-append (to-str p)
 " :")
)
)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break14)
 (letrec ((loop13 (lambda ()
 (if (<= j p)
 (begin (let ((c (coeff p j)
)
)
 (begin (if (not (string=? (to-str c)
 "0/1")
)
 (begin (set! line (string-append (string-append (string-append line " ")
 (to-str c)
)
 "×n")
)
 (let ((exp (- (+ p 1)
 j)
)
)
 (begin (if (> exp 1)
 (begin (set! line (string-append (string-append line "^")
 (to-str exp)
)
)
)
 (quote ()
)
)
)
)
)
 (quote ()
)
)
 (set! j (+ j 1)
)
)
)
 (loop13)
)
 (quote ()
)
)
)
)
)
 (loop13)
)
)
)
 (_display (to-str line)
)
 (newline)
 (set! p (+ p 1)
)
)
)
)
)
 (loop11)
)
 (quote ()
)
)
)
)
)
 (loop11)
)
)
)
)
)
)
)
)
 (main)
 (let ((end16 (now)
)
)
 (let ((dur17 (quotient (- end16 start15)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur17)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
