;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start23 (now)
)
)
 (begin (define (bernoulli n)
 (call/cc (lambda (ret1)
 (let ((a (_list)
)
)
 (begin (let ((m 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (<= m n)
 (begin (set! a (append a (_list (/ 1 (+ m 1)
)
)
)
)
 (let ((j m)
)
 (begin (call/cc (lambda (break5)
 (letrec ((loop4 (lambda ()
 (if (>= j 1)
 (begin (list-set! a (- j 1)
 (* j (- (list-ref a (- j 1)
)
 (list-ref a j)
)
)
)
 (set! j (- j 1)
)
 (loop4)
)
 (quote ()
)
)
)
)
)
 (loop4)
)
)
)
 (set! m (+ m 1)
)
)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (if (not (equal? n 1)
)
 (begin (ret1 (list-ref a 0)
)
)
 (quote ()
)
)
 (ret1 (- (list-ref a 0)
)
)
)
)
)
)
)
)
)
 (define (binom n k)
 (call/cc (lambda (ret6)
 (begin (if (or (< k 0)
 (> k n)
)
 (begin (ret6 0)
)
 (quote ()
)
)
 (let ((kk k)
)
 (begin (if (_gt kk (- n kk)
)
 (begin (set! kk (- n kk)
)
)
 (quote ()
)
)
 (let ((res 1)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (< i kk)
 (begin (set! res (* res (- n i)
)
)
 (set! i (+ i 1)
)
 (set! res (/ res i)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
 (ret6 res)
)
)
)
)
)
)
)
)
)
)
 (define (faulhaberRow p)
 (call/cc (lambda (ret9)
 (let ((coeffs (_list)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda ()
 (if (<= i p)
 (begin (set! coeffs (append coeffs (_list 0)
)
)
 (set! i (+ i 1)
)
 (loop10)
)
 (quote ()
)
)
)
)
)
 (loop10)
)
)
)
 (let ((j 0)
)
 (begin (let ((sign (- 1)
)
)
 (begin (call/cc (lambda (break13)
 (letrec ((loop12 (lambda ()
 (if (<= j p)
 (begin (set! sign (- sign)
)
 (let ((c (/ 1 (+ p 1)
)
)
)
 (begin (if (< sign 0)
 (begin (set! c (- c)
)
)
 (quote ()
)
)
 (set! c (* c (binom (+ p 1)
 j)
)
)
 (set! c (* c (bernoulli j)
)
)
 (list-set! coeffs (- p j)
 c)
 (set! j (+ j 1)
)
)
)
 (loop12)
)
 (quote ()
)
)
)
)
)
 (loop12)
)
)
)
 (ret9 coeffs)
)
)
)
)
)
)
)
)
)
)
)
 (define (ratStr r)
 (call/cc (lambda (ret14)
 (let ((s (to-str r)
)
)
 (begin (if (endsWith s "/1")
 (begin (ret14 (substring s 0 (- (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 2)
)
)
)
 (quote ()
)
)
 (ret14 s)
)
)
)
)
)
 (define (endsWith s suf)
 (call/cc (lambda (ret15)
 (begin (if (< (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 (cond ((string? suf)
 (string-length suf)
)
 ((hash-table? suf)
 (hash-table-size suf)
)
 (else (length suf)
)
)
)
 (begin (ret15 #f)
)
 (quote ()
)
)
 (ret15 (string=? (substring s (- (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 (cond ((string? suf)
 (string-length suf)
)
 ((hash-table? suf)
 (hash-table-size suf)
)
 (else (length suf)
)
)
)
 (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 suf)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret16)
 (let ((p 0)
)
 (begin (call/cc (lambda (break18)
 (letrec ((loop17 (lambda ()
 (if (< p 10)
 (begin (let ((row (faulhaberRow p)
)
)
 (begin (let ((line "")
)
 (begin (let ((idx 0)
)
 (begin (call/cc (lambda (break20)
 (letrec ((loop19 (lambda ()
 (if (< idx (cond ((string? row)
 (string-length row)
)
 ((hash-table? row)
 (hash-table-size row)
)
 (else (length row)
)
)
)
 (begin (set! line (string-append line (padStart (ratStr (cond ((string? row)
 (substring row idx (+ idx 1)
)
)
 ((hash-table? row)
 (hash-table-ref row idx)
)
 (else (list-ref row idx)
)
)
)
 5 " ")
)
)
 (if (_lt idx (- (cond ((string? row)
 (string-length row)
)
 ((hash-table? row)
 (hash-table-size row)
)
 (else (length row)
)
)
 1)
)
 (begin (set! line (string-append line "  ")
)
)
 (quote ()
)
)
 (set! idx (+ idx 1)
)
 (loop19)
)
 (quote ()
)
)
)
)
)
 (loop19)
)
)
)
 (_display (to-str line)
)
 (newline)
 (set! p (+ p 1)
)
)
)
)
)
)
)
 (loop17)
)
 (quote ()
)
)
)
)
)
 (loop17)
)
)
)
 (_display (to-str "")
)
 (newline)
 (let ((k 17)
)
 (begin (let ((coeffs (faulhaberRow k)
)
)
 (begin (let ((nn 1000)
)
 (begin (let ((np 1)
)
 (begin (let ((sum 0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break22)
 (letrec ((loop21 (lambda ()
 (if (< i (cond ((string? coeffs)
 (string-length coeffs)
)
 ((hash-table? coeffs)
 (hash-table-size coeffs)
)
 (else (length coeffs)
)
)
)
 (begin (set! np (* np nn)
)
 (set! sum (_add sum (* (cond ((string? coeffs)
 (substring coeffs i (+ i 1)
)
)
 ((hash-table? coeffs)
 (hash-table-ref coeffs i)
)
 (else (list-ref coeffs i)
)
)
 np)
)
)
 (set! i (+ i 1)
)
 (loop21)
)
 (quote ()
)
)
)
)
)
 (loop21)
)
)
)
 (_display (to-str (ratStr sum)
)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end24 (now)
)
)
 (let ((dur25 (quotient (- end24 start23)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur25)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
