;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start21 (now)
)
)
 (begin (define (floorf x)
 (call/cc (lambda (ret1)
 (let ((y (let ((v2 x)
)
 (cond ((string? v2)
 (inexact->exact (floor (string->number v2)
)
)
)
 ((boolean? v2)
 (if v2 1 0)
)
 (else (inexact->exact (floor v2)
)
)
)
)
)
)
 (begin (ret1 (+ 0.0 y)
)
)
)
)
)
)
 (define (indexOf s ch)
 (call/cc (lambda (ret3)
 (let ((i 0)
)
 (begin (call/cc (lambda (break5)
 (letrec ((loop4 (lambda ()
 (if (< i (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (if (string=? (substring s i (+ i 1)
)
 ch)
 (begin (ret3 i)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop4)
)
 (quote ()
)
)
)
)
)
 (loop4)
)
)
)
 (ret3 (- 0 1)
)
)
)
)
)
)
 (define (fmt8 x)
 (call/cc (lambda (ret6)
 (let ((y (/ (floorf (_add (* x 100000000.0)
 0.5)
)
 100000000.0)
)
)
 (begin (let ((s (to-str y)
)
)
 (begin (let ((dot (indexOf s ".")
)
)
 (begin (if (equal? dot (- 0 1)
)
 (begin (set! s (string-append s ".00000000")
)
)
 (begin (let ((decs (- (- (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 dot)
 1)
)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if (_lt decs 8)
 (begin (set! s (string-append s "0")
)
 (set! decs (_add decs 1)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
)
)
)
)
 (ret6 s)
)
)
)
)
)
)
)
)
)
 (define (pad2 x)
 (call/cc (lambda (ret9)
 (let ((s (to-str x)
)
)
 (begin (if (< (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 2)
 (begin (set! s (string-append " " s)
)
)
 (quote ()
)
)
 (ret9 s)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret10)
 (let ((maxIt 13)
)
 (begin (let ((maxItJ 10)
)
 (begin (let ((a1 1.0)
)
 (begin (let ((a2 0.0)
)
 (begin (let ((d1 3.2)
)
 (begin (_display (to-str " i       d")
)
 (newline)
 (let ((i 2)
)
 (begin (call/cc (lambda (break12)
 (letrec ((loop11 (lambda ()
 (if (<= i maxIt)
 (begin (let ((a (_add a1 (/ (- a1 a2)
 d1)
)
)
)
 (begin (let ((j 1)
)
 (begin (call/cc (lambda (break14)
 (letrec ((loop13 (lambda ()
 (if (<= j maxItJ)
 (begin (let ((x 0.0)
)
 (begin (let ((y 0.0)
)
 (begin (let ((k 1)
)
 (begin (let ((limit (pow_int 2 i)
)
)
 (begin (call/cc (lambda (break16)
 (letrec ((loop15 (lambda ()
 (if (<= k limit)
 (begin (set! y (- 1.0 (* (* 2.0 y)
 x)
)
)
 (set! x (- a (* x x)
)
)
 (set! k (+ k 1)
)
 (loop15)
)
 (quote ()
)
)
)
)
)
 (loop15)
)
)
)
 (set! a (- a (/ x y)
)
)
 (set! j (+ j 1)
)
)
)
)
)
)
)
)
)
 (loop13)
)
 (quote ()
)
)
)
)
)
 (loop13)
)
)
)
 (let ((d (/ (- a1 a2)
 (- a a1)
)
)
)
 (begin (_display (to-str (string-append (string-append (pad2 i)
 "    ")
 (fmt8 d)
)
)
)
 (newline)
 (set! d1 d)
 (set! a2 a1)
 (set! a1 a)
 (set! i (+ i 1)
)
)
)
)
)
)
)
 (loop11)
)
 (quote ()
)
)
)
)
)
 (loop11)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (pow_int base exp)
 (call/cc (lambda (ret17)
 (let ((r 1)
)
 (begin (let ((b base)
)
 (begin (let ((e exp)
)
 (begin (call/cc (lambda (break19)
 (letrec ((loop18 (lambda ()
 (if (> e 0)
 (begin (if (equal? (modulo e 2)
 1)
 (begin (set! r (* r b)
)
)
 (quote ()
)
)
 (set! b (* b b)
)
 (set! e (let ((v20 (quotient e 2)
)
)
 (cond ((string? v20)
 (inexact->exact (floor (string->number v20)
)
)
)
 ((boolean? v20)
 (if v20 1 0)
)
 (else (inexact->exact (floor v20)
)
)
)
)
)
 (loop18)
)
 (quote ()
)
)
)
)
)
 (loop18)
)
)
)
 (ret17 r)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end22 (now)
)
)
 (let ((dur23 (quotient (- end22 start21)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur23)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
