;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start31 (now)
)
)
 (begin (define (pow_int base exp)
 (call/cc (lambda (ret1)
 (let ((result 1)
)
 (begin (let ((b base)
)
 (begin (let ((e exp)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (> e 0)
 (begin (if (equal? (modulo e 2)
 1)
 (begin (set! result (* result b)
)
)
 (quote ()
)
)
 (set! b (* b b)
)
 (set! e (let ((v4 (quotient e 2)
)
)
 (cond ((string? v4)
 (inexact->exact (floor (string->number v4)
)
)
)
 ((boolean? v4)
 (if v4 1 0)
)
 (else (inexact->exact (floor v4)
)
)
)
)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 result)
)
)
)
)
)
)
)
)
)
 (define (pow_big base exp)
 (call/cc (lambda (ret5)
 (let ((result 1)
)
 (begin (let ((b base)
)
 (begin (let ((e exp)
)
 (begin (call/cc (lambda (break7)
 (letrec ((loop6 (lambda ()
 (if (> e 0)
 (begin (if (equal? (modulo e 2)
 1)
 (begin (set! result (* result b)
)
)
 (quote ()
)
)
 (set! b (* b b)
)
 (set! e (let ((v8 (quotient e 2)
)
)
 (cond ((string? v8)
 (inexact->exact (floor (string->number v8)
)
)
)
 ((boolean? v8)
 (if v8 1 0)
)
 (else (inexact->exact (floor v8)
)
)
)
)
)
 (loop6)
)
 (quote ()
)
)
)
)
)
 (loop6)
)
)
)
 (ret5 result)
)
)
)
)
)
)
)
)
)
 (define (parseBigInt str)
 (call/cc (lambda (ret9)
 (let ((i 0)
)
 (begin (let ((neg #f)
)
 (begin (if (and (> (cond ((string? str)
 (string-length str)
)
 ((hash-table? str)
 (hash-table-size str)
)
 (else (length str)
)
)
 0)
 (string=? (substring str 0 1)
 "-")
)
 (begin (set! neg #t)
 (set! i 1)
)
 (quote ()
)
)
 (let ((n 0)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda ()
 (if (< i (cond ((string? str)
 (string-length str)
)
 ((hash-table? str)
 (hash-table-size str)
)
 (else (length str)
)
)
)
 (begin (let ((ch (substring str i (+ i 1)
)
)
)
 (begin (let ((d (let ((v12 ch)
)
 (cond ((string? v12)
 (inexact->exact (floor (string->number v12)
)
)
)
 ((boolean? v12)
 (if v12 1 0)
)
 (else (inexact->exact (floor v12)
)
)
)
)
)
)
 (begin (set! n (_add (* n 10)
 d)
)
 (set! i (+ i 1)
)
)
)
)
)
 (loop10)
)
 (quote ()
)
)
)
)
)
 (loop10)
)
)
)
 (if neg (begin (set! n (- n)
)
)
 (quote ()
)
)
 (ret9 n)
)
)
)
)
)
)
)
)
)
 (define (fermat n)
 (call/cc (lambda (ret13)
 (let ((p (pow_int 2 n)
)
)
 (begin (ret13 (_add (pow_big 2 p)
 1)
)
)
)
)
)
)
 (define (primeFactorsBig n)
 (call/cc (lambda (ret14)
 (let ((factors (_list)
)
)
 (begin (let ((m n)
)
 (begin (let ((d 2)
)
 (begin (call/cc (lambda (break16)
 (letrec ((loop15 (lambda ()
 (if (equal? (fmod m d)
 0)
 (begin (set! factors (append factors (_list d)
)
)
 (set! m (/ m d)
)
 (loop15)
)
 (quote ()
)
)
)
)
)
 (loop15)
)
)
)
 (set! d 3)
 (call/cc (lambda (break18)
 (letrec ((loop17 (lambda ()
 (if (_le (* d d)
 m)
 (begin (call/cc (lambda (break20)
 (letrec ((loop19 (lambda ()
 (if (equal? (fmod m d)
 0)
 (begin (set! factors (append factors (_list d)
)
)
 (set! m (/ m d)
)
 (loop19)
)
 (quote ()
)
)
)
)
)
 (loop19)
)
)
)
 (set! d (+ d 2)
)
 (loop17)
)
 (quote ()
)
)
)
)
)
 (loop17)
)
)
)
 (if (> m 1)
 (begin (set! factors (append factors (_list m)
)
)
)
 (quote ()
)
)
 (ret14 factors)
)
)
)
)
)
)
)
)
)
 (define (show_list xs)
 (call/cc (lambda (ret21)
 (let ((line "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break23)
 (letrec ((loop22 (lambda ()
 (if (< i (cond ((string? xs)
 (string-length xs)
)
 ((hash-table? xs)
 (hash-table-size xs)
)
 (else (length xs)
)
)
)
 (begin (set! line (string-append line (to-str (list-ref xs i)
)
)
)
 (if (_lt i (- (cond ((string? xs)
 (string-length xs)
)
 ((hash-table? xs)
 (hash-table-size xs)
)
 (else (length xs)
)
)
 1)
)
 (begin (set! line (string-append line " ")
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop22)
)
 (quote ()
)
)
)
)
)
 (loop22)
)
)
)
 (ret21 line)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret24)
 (let ((nums (_list)
)
)
 (begin (call/cc (lambda (break26)
 (letrec ((loop25 (lambda (i)
 (if (< i 8)
 (begin (begin (set! nums (append nums (_list (fermat i)
)
)
)
)
 (loop25 (+ i 1)
)
)
 (quote ()
)
)
)
)
)
 (loop25 0)
)
)
)
 (_display (to-str "First 8 Fermat numbers:")
)
 (newline)
 (call/cc (lambda (break28)
 (letrec ((loop27 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((n (car xs)
)
)
 (begin (_display (to-str (to-str n)
)
)
 (newline)
)
)
 (loop27 (cdr xs)
)
)
)
)
)
)
 (loop27 nums)
)
)
)
 (let ((extra (alist->hash-table (_list (cons 6 (_list 274177 67280421310721)
)
 (cons 7 (_list (parseBigInt "59649589127497217")
 (parseBigInt "5704689200685129054721")
)
)
)
)
)
)
 (begin (_display (to-str "\nFactors:")
)
 (newline)
 (let ((i 0)
)
 (begin (call/cc (lambda (break30)
 (letrec ((loop29 (lambda ()
 (if (< i (cond ((string? nums)
 (string-length nums)
)
 ((hash-table? nums)
 (hash-table-size nums)
)
 (else (length nums)
)
)
)
 (begin (let ((facs (_list)
)
)
 (begin (if (<= i 5)
 (begin (set! facs (primeFactorsBig (list-ref nums i)
)
)
)
 (begin (set! facs (hash-table-ref/default extra i (quote ()
)
)
)
)
)
 (_display (to-str (string-append (string-append (string-append "F" (to-str i)
)
 " = ")
 (show_list facs)
)
)
)
 (newline)
 (set! i (+ i 1)
)
)
)
 (loop29)
)
 (quote ()
)
)
)
)
)
 (loop29)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end32 (now)
)
)
 (let ((dur33 (quotient (- end32 start31)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur33)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
