;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start14 (now)
)
)
 (begin (define (endsWith s suf)
 (call/cc (lambda (ret1)
 (begin (if (< (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 (cond ((string? suf)
 (string-length suf)
)
 ((hash-table? suf)
 (hash-table-size suf)
)
 (else (length suf)
)
)
)
 (begin (ret1 #f)
)
 (quote ()
)
)
 (ret1 (string=? (substring s (- (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 (cond ((string? suf)
 (string-length suf)
)
 ((hash-table? suf)
 (hash-table-size suf)
)
 (else (length suf)
)
)
)
 (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 suf)
)
)
)
)
)
 (define (lastIndexOf s sub)
 (call/cc (lambda (ret2)
 (let ((idx (- 0 1)
)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break4)
 (letrec ((loop3 (lambda ()
 (if (_le i (- (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 (cond ((string? sub)
 (string-length sub)
)
 ((hash-table? sub)
 (hash-table-size sub)
)
 (else (length sub)
)
)
)
)
 (begin (if (string=? (substring s i (+ i (cond ((string? sub)
 (string-length sub)
)
 ((hash-table? sub)
 (hash-table-size sub)
)
 (else (length sub)
)
)
)
)
 sub)
 (begin (set! idx i)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop3)
)
 (quote ()
)
)
)
)
)
 (loop3)
)
)
)
 (ret2 idx)
)
)
)
)
)
)
)
 (define extensions (_list "zip" "rar" "7z" "gz" "archive" "A##" "tar.bz2")
)
 (define (fileExtInList filename)
 (call/cc (lambda (ret5)
 (let ((fl (lower filename)
)
)
 (begin (call/cc (lambda (break7)
 (letrec ((loop6 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((ext (car xs)
)
)
 (begin (let ((ext2 (string-append "." (lower ext)
)
)
)
 (begin (if (endsWith fl ext2)
 (begin (ret5 (_list #t ext)
)
)
 (quote ()
)
)
)
)
)
)
 (loop6 (cdr xs)
)
)
)
)
)
)
 (loop6 extensions)
)
)
)
 (let ((idx (lastIndexOf filename ".")
)
)
 (begin (if (not (equal? idx (- 0 1)
)
)
 (begin (let ((t (substring filename (_add idx 1)
 (cond ((string? filename)
 (string-length filename)
)
 ((hash-table? filename)
 (hash-table-size filename)
)
 (else (length filename)
)
)
)
)
)
 (begin (if (not (string=? t "")
)
 (begin (ret5 (_list #f t)
)
)
 (quote ()
)
)
 (ret5 (_list #f "<empty>")
)
)
)
)
 (quote ()
)
)
 (ret5 (_list #f "<none>")
)
)
)
)
)
)
)
)
 (define (pad s w)
 (call/cc (lambda (ret8)
 (let ((t s)
)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if (< (cond ((string? t)
 (string-length t)
)
 ((hash-table? t)
 (hash-table-size t)
)
 (else (length t)
)
)
 w)
 (begin (set! t (string-append t " ")
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
 (ret8 t)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret11)
 (begin (_display (to-str "The listed extensions are:")
)
 (newline)
 (_display (to-str extensions)
)
 (newline)
 (let ((tests (_list "MyData.a##" "MyData.tar.Gz" "MyData.gzip" "MyData.7z.backup" "MyData..." "MyData" "MyData_v1.0.tar.bz2" "MyData_v1.0.bz2")
)
)
 (begin (call/cc (lambda (break13)
 (letrec ((loop12 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((t (car xs)
)
)
 (begin (let ((res (fileExtInList t)
)
)
 (begin (let ((ok (cond ((string? res)
 (substring res 0 (+ 0 1)
)
)
 ((hash-table? res)
 (hash-table-ref res 0)
)
 (else (list-ref res 0)
)
)
)
)
 (begin (let ((ext (to-str (cond ((string? res)
 (substring res 1 (+ 1 1)
)
)
 ((hash-table? res)
 (hash-table-ref res 1)
)
 (else (list-ref res 1)
)
)
)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (pad t 20)
 " => ")
 (to-str ok)
)
 "  (extension = ")
 ext)
 ")
")
)
)
 (newline)
)
)
)
)
)
)
)
)
 (loop12 (cdr xs)
)
)
)
)
)
)
 (loop12 tests)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end15 (now)
)
)
 (let ((dur16 (quotient (- end15 start14)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur16)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
