;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start13 (now)
)
)
 (begin (define (splitPath p)
 (call/cc (lambda (ret1)
 (let ((parts (_list)
)
)
 (begin (let ((cur "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i (cond ((string? p)
 (string-length p)
)
 ((hash-table? p)
 (hash-table-size p)
)
 (else (length p)
)
)
)
 (begin (if (string=? (substring p i (+ i 1)
)
 "/")
 (begin (if (not (string=? cur "")
)
 (begin (set! parts (append parts (_list cur)
)
)
 (set! cur "")
)
 (quote ()
)
)
)
 (begin (set! cur (string-append cur (substring p i (+ i 1)
)
)
)
)
)
 (set! i (+ i 1)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (if (not (string=? cur "")
)
 (begin (set! parts (append parts (_list cur)
)
)
)
 (quote ()
)
)
 (ret1 parts)
)
)
)
)
)
)
)
)
)
 (define (joinPath parts)
 (call/cc (lambda (ret4)
 (let ((s "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i (cond ((string? parts)
 (string-length parts)
)
 ((hash-table? parts)
 (hash-table-size parts)
)
 (else (length parts)
)
)
)
 (begin (set! s (string-append (string-append s "/")
 (list-ref parts i)
)
)
 (set! i (+ i 1)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret4 s)
)
)
)
)
)
)
)
 (define (commonPrefix paths)
 (call/cc (lambda (ret7)
 (begin (if (equal? (cond ((string? paths)
 (string-length paths)
)
 ((hash-table? paths)
 (hash-table-size paths)
)
 (else (length paths)
)
)
 0)
 (begin (ret7 "")
)
 (quote ()
)
)
 (let ((base (splitPath (list-ref paths 0)
)
)
)
 (begin (let ((i 0)
)
 (begin (let ((prefix (_list)
)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (< i (cond ((string? base)
 (string-length base)
)
 ((hash-table? base)
 (hash-table-size base)
)
 (else (length base)
)
)
)
 (begin (let ((comp (cond ((string? base)
 (substring base i (+ i 1)
)
)
 ((hash-table? base)
 (hash-table-ref base i)
)
 (else (list-ref base i)
)
)
)
)
 (begin (let ((ok #t)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((p (car xs)
)
)
 (begin (let ((parts (splitPath p)
)
)
 (begin (if (or (>= i (cond ((string? parts)
 (string-length parts)
)
 ((hash-table? parts)
 (hash-table-size parts)
)
 (else (length parts)
)
)
)
 (not (equal? (cond ((string? parts)
 (substring parts i (+ i 1)
)
)
 ((hash-table? parts)
 (hash-table-ref parts i)
)
 (else (list-ref parts i)
)
)
 comp)
)
)
 (begin (set! ok #f)
 (break11 (quote ()
)
)
)
 (quote ()
)
)
)
)
)
)
 (loop10 (cdr xs)
)
)
)
)
)
)
 (loop10 paths)
)
)
)
 (if ok (begin (set! prefix (append prefix (_list comp)
)
)
)
 (begin (break9 (quote ()
)
)
)
)
 (set! i (+ i 1)
)
)
)
)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
 (ret7 (joinPath prefix)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret12)
 (let ((paths (_list "/home/user1/tmp/coverage/test" "/home/user1/tmp/covert/operator" "/home/user1/tmp/coven/members" "/home//user1/tmp/coventry" "/home/user1/././tmp/covertly/foo" "/home/bob/../user1/tmp/coved/bar")
)
)
 (begin (let ((c (commonPrefix paths)
)
)
 (begin (if (string=? c "")
 (begin (_display (to-str "No common path")
)
 (newline)
)
 (begin (_display (to-str (string-append "Common path: " c)
)
)
 (newline)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end14 (now)
)
)
 (let ((dur15 (quotient (- end14 start13)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur15)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
