;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start7 (now)
)
)
 (begin (define (add a b)
 (call/cc (lambda (ret1)
 (ret1 (alist->hash-table (_list (cons "x" (+ (hash-table-ref a "x")
 (hash-table-ref b "x")
)
)
 (cons "y" (+ (hash-table-ref a "y")
 (hash-table-ref b "y")
)
)
 (cons "z" (+ (hash-table-ref a "z")
 (hash-table-ref b "z")
)
)
)
)
)
)
)
)
 (define (sub a b)
 (call/cc (lambda (ret2)
 (ret2 (alist->hash-table (_list (cons "x" (- (hash-table-ref a "x")
 (hash-table-ref b "x")
)
)
 (cons "y" (- (hash-table-ref a "y")
 (hash-table-ref b "y")
)
)
 (cons "z" (- (hash-table-ref a "z")
 (hash-table-ref b "z")
)
)
)
)
)
)
)
)
 (define (mul v s)
 (call/cc (lambda (ret3)
 (ret3 (alist->hash-table (_list (cons "x" (* (hash-table-ref v "x")
 s)
)
 (cons "y" (* (hash-table-ref v "y")
 s)
)
 (cons "z" (* (hash-table-ref v "z")
 s)
)
)
)
)
)
)
)
 (define (dot a b)
 (call/cc (lambda (ret4)
 (ret4 (_add (_add (* (hash-table-ref a "x")
 (hash-table-ref b "x")
)
 (* (hash-table-ref a "y")
 (hash-table-ref b "y")
)
)
 (* (hash-table-ref a "z")
 (hash-table-ref b "z")
)
)
)
)
)
)
 (define (intersectPoint rv rp pn pp)
 (call/cc (lambda (ret5)
 (let ((diff (sub rp pp)
)
)
 (begin (let ((prod1 (dot diff pn)
)
)
 (begin (let ((prod2 (dot rv pn)
)
)
 (begin (let ((prod3 (/ prod1 prod2)
)
)
 (begin (ret5 (sub rp (mul rv prod3)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret6)
 (let ((rv (alist->hash-table (_list (cons "x" 0.0)
 (cons "y" (- 1.0)
)
 (cons "z" (- 1.0)
)
)
)
)
)
 (begin (let ((rp (alist->hash-table (_list (cons "x" 0.0)
 (cons "y" 0.0)
 (cons "z" 10.0)
)
)
)
)
 (begin (let ((pn (alist->hash-table (_list (cons "x" 0.0)
 (cons "y" 0.0)
 (cons "z" 1.0)
)
)
)
)
 (begin (let ((pp (alist->hash-table (_list (cons "x" 0.0)
 (cons "y" 0.0)
 (cons "z" 5.0)
)
)
)
)
 (begin (let ((ip (intersectPoint rv rp pn pp)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append (string-append "The ray intersects the plane at (" (to-str (hash-table-ref ip "x")
)
)
 ", ")
 (to-str (hash-table-ref ip "y")
)
)
 ", ")
 (to-str (hash-table-ref ip "z")
)
)
 ")
")
)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end8 (now)
)
)
 (let ((dur9 (quotient (- end8 start7)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur9)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
