;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start22 (now)
)
)
 (begin (define glyphs "♜♞♝♛♚♖♘♗♕♔")
 (define g2lMap (alist->hash-table (_list (cons "♜" "R")
 (cons "♞" "N")
 (cons "♝" "B")
 (cons "♛" "Q")
 (cons "♚" "K")
 (cons "♖" "R")
 (cons "♘" "N")
 (cons "♗" "B")
 (cons "♕" "Q")
 (cons "♔" "K")
)
)
)
 (define names (alist->hash-table (_list (cons "R" "rook")
 (cons "N" "knight")
 (cons "B" "bishop")
 (cons "Q" "queen")
 (cons "K" "king")
)
)
)
 (define ntable (alist->hash-table (_list (cons "01" 0)
 (cons "02" 1)
 (cons "03" 2)
 (cons "04" 3)
 (cons "12" 4)
 (cons "13" 5)
 (cons "14" 6)
 (cons "23" 7)
 (cons "24" 8)
 (cons "34" 9)
)
)
)
 (define (indexOf s sub)
 (call/cc (lambda (ret1)
 (let ((i 0)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (_le i (- (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 (cond ((string? sub)
 (string-length sub)
)
 ((hash-table? sub)
 (hash-table-size sub)
)
 (else (length sub)
)
)
)
)
 (begin (if (string=? (substring s i (+ i (cond ((string? sub)
 (string-length sub)
)
 ((hash-table? sub)
 (hash-table-size sub)
)
 (else (length sub)
)
)
)
)
 sub)
 (begin (ret1 i)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 (- 1)
)
)
)
)
)
)
 (define (strReplace s old new)
 (call/cc (lambda (ret4)
 (let ((res "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (< i (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (if (and (and (> (cond ((string? old)
 (string-length old)
)
 ((hash-table? old)
 (hash-table-size old)
)
 (else (length old)
)
)
 0)
 (_le (+ i (cond ((string? old)
 (string-length old)
)
 ((hash-table? old)
 (hash-table-size old)
)
 (else (length old)
)
)
)
 (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
)
 (string=? (substring s i (+ i (cond ((string? old)
 (string-length old)
)
 ((hash-table? old)
 (hash-table-size old)
)
 (else (length old)
)
)
)
)
 old)
)
 (begin (set! res (string-append res new)
)
 (set! i (+ i (cond ((string? old)
 (string-length old)
)
 ((hash-table? old)
 (hash-table-size old)
)
 (else (length old)
)
)
)
)
)
 (begin (set! res (string-append res (substring s i (+ i 1)
)
)
)
 (set! i (+ i 1)
)
)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (ret4 res)
)
)
)
)
)
)
)
 (define (g2l pieces)
 (call/cc (lambda (ret7)
 (let ((lets "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if (< i (cond ((string? pieces)
 (string-length pieces)
)
 ((hash-table? pieces)
 (hash-table-size pieces)
)
 (else (length pieces)
)
)
)
 (begin (let ((ch (substring pieces i (+ i 1)
)
)
)
 (begin (set! lets (string-append lets (hash-table-ref/default g2lMap ch (quote ()
)
)
)
)
 (set! i (+ i 1)
)
)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
 (ret7 lets)
)
)
)
)
)
)
)
 (define (spid pieces)
 (call/cc (lambda (ret10)
 (begin (set! pieces (g2l pieces)
)
 (if (not (equal? (cond ((string? pieces)
 (string-length pieces)
)
 ((hash-table? pieces)
 (hash-table-size pieces)
)
 (else (length pieces)
)
)
 8)
)
 (begin (ret10 (- 1)
)
)
 (quote ()
)
)
 (call/cc (lambda (break12)
 (letrec ((loop11 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((one (car xs)
)
)
 (begin (let ((count 0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break14)
 (letrec ((loop13 (lambda ()
 (if (< i (cond ((string? pieces)
 (string-length pieces)
)
 ((hash-table? pieces)
 (hash-table-size pieces)
)
 (else (length pieces)
)
)
)
 (begin (if (string=? (substring pieces i (+ i 1)
)
 one)
 (begin (set! count (+ count 1)
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop13)
)
 (quote ()
)
)
)
)
)
 (loop13)
)
)
)
 (if (not (equal? count 1)
)
 (begin (ret10 (- 1)
)
)
 (quote ()
)
)
)
)
)
)
)
)
 (loop11 (cdr xs)
)
)
)
)
)
)
 (loop11 (_list "K" "Q")
)
)
)
)
 (call/cc (lambda (break16)
 (letrec ((loop15 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((two (car xs)
)
)
 (begin (let ((count 0)
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break18)
 (letrec ((loop17 (lambda ()
 (if (< i (cond ((string? pieces)
 (string-length pieces)
)
 ((hash-table? pieces)
 (hash-table-size pieces)
)
 (else (length pieces)
)
)
)
 (begin (if (string=? (substring pieces i (+ i 1)
)
 two)
 (begin (set! count (+ count 1)
)
)
 (quote ()
)
)
 (set! i (+ i 1)
)
 (loop17)
)
 (quote ()
)
)
)
)
)
 (loop17)
)
)
)
 (if (not (equal? count 2)
)
 (begin (ret10 (- 1)
)
)
 (quote ()
)
)
)
)
)
)
)
)
 (loop15 (cdr xs)
)
)
)
)
)
)
 (loop15 (_list "R" "N" "B")
)
)
)
)
 (let ((r1 (indexOf pieces "R")
)
)
 (begin (let ((r2 (_add (_add (indexOf (substring pieces (_add r1 1)
 (cond ((string? pieces)
 (string-length pieces)
)
 ((hash-table? pieces)
 (hash-table-size pieces)
)
 (else (length pieces)
)
)
)
 "R")
 r1)
 1)
)
)
 (begin (let ((k (indexOf pieces "K")
)
)
 (begin (if (or (_lt k r1)
 (_gt k r2)
)
 (begin (ret10 (- 1)
)
)
 (quote ()
)
)
 (let ((b1 (indexOf pieces "B")
)
)
 (begin (let ((b2 (_add (_add (indexOf (substring pieces (_add b1 1)
 (cond ((string? pieces)
 (string-length pieces)
)
 ((hash-table? pieces)
 (hash-table-size pieces)
)
 (else (length pieces)
)
)
)
 "B")
 b1)
 1)
)
)
 (begin (if (equal? (fmod (- b2 b1)
 2)
 0)
 (begin (ret10 (- 1)
)
)
 (quote ()
)
)
 (let ((piecesN (strReplace pieces "Q" "")
)
)
 (begin (set! piecesN (strReplace piecesN "B" "")
)
 (let ((n1 (indexOf piecesN "N")
)
)
 (begin (let ((n2 (_add (_add (indexOf (substring piecesN (_add n1 1)
 (cond ((string? piecesN)
 (string-length piecesN)
)
 ((hash-table? piecesN)
 (hash-table-size piecesN)
)
 (else (length piecesN)
)
)
)
 "N")
 n1)
 1)
)
)
 (begin (let ((np (string-append (to-str n1)
 (to-str n2)
)
)
)
 (begin (let ((N (hash-table-ref/default ntable np (quote ()
)
)
)
)
 (begin (let ((piecesQ (strReplace pieces "B" "")
)
)
 (begin (let ((Q (indexOf piecesQ "Q")
)
)
 (begin (let ((D (indexOf "0246" (to-str b1)
)
)
)
 (begin (let ((L (indexOf "1357" (to-str b2)
)
)
)
 (begin (if (equal? D (- 0 1)
)
 (begin (set! D (indexOf "0246" (to-str b2)
)
)
 (set! L (indexOf "1357" (to-str b1)
)
)
)
 (quote ()
)
)
 (ret10 (_add (_add (_add (* 96 N)
 (* 16 Q)
)
 (* 4 D)
)
 L)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret19)
 (call/cc (lambda (break21)
 (letrec ((loop20 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((pieces (car xs)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append pieces " or ")
 (g2l pieces)
)
 " has SP-ID of ")
 (to-str (spid pieces)
)
)
)
)
 (newline)
)
)
 (loop20 (cdr xs)
)
)
)
)
)
)
 (loop20 (_list "♕♘♖♗♗♘♔♖" "♖♘♗♕♔♗♘♖" "♖♕♘♗♗♔♖♘" "♖♘♕♗♗♔♖♘")
)
)
)
)
)
)
)
 (main)
 (let ((end23 (now)
)
)
 (let ((dur24 (quotient (- end23 start22)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur24)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
