;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start13 (now)
)
)
 (begin (define (commatize n)
 (call/cc (lambda (ret1)
 (let ((s (to-str n)
)
)
 (begin (let ((i (modulo (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 3)
)
)
 (begin (if (equal? i 0)
 (begin (set! i 3)
)
 (quote ()
)
)
 (let ((out (substring s 0 i)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< i (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
)
 (begin (set! out (string-append (string-append out ",")
 (substring s i (+ i 3)
)
)
)
 (set! i (+ i 3)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 out)
)
)
)
)
)
)
)
)
)
 (define (p L n)
 (call/cc (lambda (ret4)
 (let ((Ls (to-str L)
)
)
 (begin (let ((digits 1)
)
 (begin (let ((d 1)
)
 (begin (call/cc (lambda (break6)
 (letrec ((loop5 (lambda ()
 (if (_le d (- 18 (cond ((string? Ls)
 (string-length Ls)
)
 ((hash-table? Ls)
 (hash-table-size Ls)
)
 (else (length Ls)
)
)
)
)
 (begin (set! digits (* digits 10)
)
 (set! d (+ d 1)
)
 (loop5)
)
 (quote ()
)
)
)
)
)
 (loop5)
)
)
)
 (let ((ten18 1000000000000000000)
)
 (begin (let ((count 0)
)
 (begin (let ((i 0)
)
 (begin (let ((probe 1)
)
 (begin (call/cc (lambda (break8)
 (letrec ((loop7 (lambda ()
 (if #t (begin (set! probe (* probe 2)
)
 (set! i (+ i 1)
)
 (if (>= probe ten18)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda ()
 (if #t (begin (if (>= probe ten18)
 (begin (set! probe (quotient probe 10)
)
)
 (quote ()
)
)
 (if (equal? (quotient probe digits)
 L)
 (begin (set! count (+ count 1)
)
 (if (>= count n)
 (begin (set! count (- count 1)
)
 (break10 (quote ()
)
)
)
 (quote ()
)
)
)
 (quote ()
)
)
 (set! probe (* probe 2)
)
 (set! i (+ i 1)
)
 (loop9)
)
 (quote ()
)
)
)
)
)
 (loop9)
)
)
)
)
 (quote ()
)
)
 (let ((ps (to-str probe)
)
)
 (begin (let ((le (cond ((string? Ls)
 (string-length Ls)
)
 ((hash-table? Ls)
 (hash-table-size Ls)
)
 (else (length Ls)
)
)
)
)
 (begin (if (> le (cond ((string? ps)
 (string-length ps)
)
 ((hash-table? ps)
 (hash-table-size ps)
)
 (else (length ps)
)
)
)
 (begin (set! le (cond ((string? ps)
 (string-length ps)
)
 ((hash-table? ps)
 (hash-table-size ps)
)
 (else (length ps)
)
)
)
)
 (quote ()
)
)
 (if (string=? (substring ps 0 le)
 Ls)
 (begin (set! count (+ count 1)
)
 (if (>= count n)
 (begin (break8 (quote ()
)
)
)
 (quote ()
)
)
)
 (quote ()
)
)
)
)
)
)
 (loop7)
)
 (quote ()
)
)
)
)
)
 (loop7)
)
)
)
 (ret4 i)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define params (_list (_list 12 1)
 (_list 12 2)
 (_list 123 45)
)
)
 (define idx 0)
 (call/cc (lambda (break12)
 (letrec ((loop11 (lambda ()
 (if (< idx (cond ((string? params)
 (string-length params)
)
 ((hash-table? params)
 (hash-table-size params)
)
 (else (length params)
)
)
)
 (begin (let ((L (cond ((string? (list-ref params idx)
)
 (substring (list-ref params idx)
 0 (+ 0 1)
)
)
 ((hash-table? (list-ref params idx)
)
 (hash-table-ref (list-ref params idx)
 0)
)
 (else (list-ref (list-ref params idx)
 0)
)
)
)
)
 (begin (let ((m (cond ((string? (list-ref params idx)
)
 (substring (list-ref params idx)
 1 (+ 1 1)
)
)
 ((hash-table? (list-ref params idx)
)
 (hash-table-ref (list-ref params idx)
 1)
)
 (else (list-ref (list-ref params idx)
 1)
)
)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append "p(" (to-str L)
)
 ", ")
 (to-str m)
)
 ")
 = ")
 (commatize (p L m)
)
)
)
)
 (newline)
 (set! idx (+ idx 1)
)
)
)
)
)
 (loop11)
)
 (quote ()
)
)
)
)
)
 (loop11)
)
)
)
 (let ((end14 (now)
)
)
 (let ((dur15 (quotient (- end14 start13)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur15)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
