;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start16 (now)
)
)
 (begin (define jobs 12)
 (define (pad n)
 (call/cc (lambda (ret1)
 (let ((s (to-str n)
)
)
 (begin (call/cc (lambda (break3)
 (letrec ((loop2 (lambda ()
 (if (< (cond ((string? s)
 (string-length s)
)
 ((hash-table? s)
 (hash-table-size s)
)
 (else (length s)
)
)
 4)
 (begin (set! s (string-append " " s)
)
 (loop2)
)
 (quote ()
)
)
)
)
)
 (loop2)
)
)
)
 (ret1 s)
)
)
)
)
)
 (define (hail seq cnt)
 (call/cc (lambda (ret4)
 (let ((out (pad seq)
)
)
 (begin (if (not (equal? seq 1)
)
 (begin (set! cnt (+ cnt 1)
)
 (if (not (equal? (modulo seq 2)
 0)
)
 (begin (set! seq (_add (* 3 seq)
 1)
)
)
 (begin (set! seq (quotient seq 2)
)
)
)
)
 (quote ()
)
)
 (ret4 (alist->hash-table (_list (cons "seq" seq)
 (cons "cnt" cnt)
 (cons "out" out)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret5)
 (let ((seqs (_list)
)
)
 (begin (let ((cnts (_list)
)
)
 (begin (call/cc (lambda (break7)
 (letrec ((loop6 (lambda (i)
 (if (< i jobs)
 (begin (begin (set! seqs (append seqs (_list (_add i 1)
)
)
)
 (set! cnts (append cnts (_list 0)
)
)
)
 (loop6 (+ i 1)
)
)
 (quote ()
)
)
)
)
)
 (loop6 0)
)
)
)
 (call/cc (lambda (break9)
 (letrec ((loop8 (lambda ()
 (if #t (begin (let ((line "")
)
 (begin (let ((i 0)
)
 (begin (call/cc (lambda (break11)
 (letrec ((loop10 (lambda ()
 (if (< i jobs)
 (begin (let ((res (hail (list-ref seqs i)
 (list-ref cnts i)
)
)
)
 (begin (list-set! seqs i (hash-table-ref res "seq")
)
 (list-set! cnts i (hash-table-ref res "cnt")
)
 (set! line (string-append line (hash-table-ref res "out")
)
)
 (set! i (+ i 1)
)
)
)
 (loop10)
)
 (quote ()
)
)
)
)
)
 (loop10)
)
)
)
 (_display (to-str line)
)
 (newline)
 (let ((done #t)
)
 (begin (let ((j 0)
)
 (begin (call/cc (lambda (break13)
 (letrec ((loop12 (lambda ()
 (if (< j jobs)
 (begin (if (not (equal? (list-ref seqs j)
 1)
)
 (begin (set! done #f)
)
 (quote ()
)
)
 (set! j (+ j 1)
)
 (loop12)
)
 (quote ()
)
)
)
)
)
 (loop12)
)
)
)
 (if done (begin (break9 (quote ()
)
)
)
 (quote ()
)
)
)
)
)
)
)
)
)
)
 (loop8)
)
 (quote ()
)
)
)
)
)
 (loop8)
)
)
)
 (_display (to-str "")
)
 (newline)
 (_display (to-str "COUNTS:")
)
 (newline)
 (let ((counts "")
)
 (begin (let ((k 0)
)
 (begin (call/cc (lambda (break15)
 (letrec ((loop14 (lambda ()
 (if (< k jobs)
 (begin (set! counts (string-append counts (pad (list-ref cnts k)
)
)
)
 (set! k (+ k 1)
)
 (loop14)
)
 (quote ()
)
)
)
)
)
 (loop14)
)
)
)
 (_display (to-str counts)
)
 (newline)
 (_display (to-str "")
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end17 (now)
)
)
 (let ((dur18 (quotient (- end17 start16)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur18)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
