;; Generated on 2025-07-30 21:05 +0700
(import (only (scheme base) call/cc when list-ref list-set!))
(import (rename (scheme base) (list _list)))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (scheme write))
(import (srfi 69))
(import (chibi time) (srfi 98))
(define _now_seeded #f)
(define _now_seed 0)
(define (now)
  (when (not _now_seeded)
    (let ((s (get-environment-variable "MOCHI_NOW_SEED")))
      (when (and s (string->number s))
        (set! _now_seed (string->number s))
        (set! _now_seeded #t))))
  (if _now_seeded
      (begin
        (set! _now_seed (modulo (+ (* _now_seed 1664525) 1013904223) 2147483647))
        _now_seed)
      (exact (floor (* (current-second) 1000000000))))
)
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((idx (string-contains r del)))
            (if idx
                (loop (substring r (+ idx (string-length del)))
                      (cons (substring r 0 idx) acc))
                (reverse (cons r acc)))))))))
(let ((start17 (now)
)
)
 (begin (define (weekday y m d)
 (call/cc (lambda (ret1)
 (let ((yy y)
)
 (begin (let ((mm m)
)
 (begin (if (< mm 3)
 (begin (set! mm (+ mm 12)
)
 (set! yy (- yy 1)
)
)
 (quote ()
)
)
 (let ((k (modulo yy 100)
)
)
 (begin (let ((j (let ((v2 (quotient yy 100)
)
)
 (cond ((string? v2)
 (inexact->exact (floor (string->number v2)
)
)
)
 ((boolean? v2)
 (if v2 1 0)
)
 (else (inexact->exact (floor v2)
)
)
)
)
)
)
 (begin (let ((a (let ((v3 (quotient (* 13 (+ mm 1)
)
 5)
)
)
 (cond ((string? v3)
 (inexact->exact (floor (string->number v3)
)
)
)
 ((boolean? v3)
 (if v3 1 0)
)
 (else (inexact->exact (floor v3)
)
)
)
)
)
)
 (begin (let ((b (let ((v4 (quotient k 4)
)
)
 (cond ((string? v4)
 (inexact->exact (floor (string->number v4)
)
)
)
 ((boolean? v4)
 (if v4 1 0)
)
 (else (inexact->exact (floor v4)
)
)
)
)
)
)
 (begin (let ((c (let ((v5 (quotient j 4)
)
)
 (cond ((string? v5)
 (inexact->exact (floor (string->number v5)
)
)
)
 ((boolean? v5)
 (if v5 1 0)
)
 (else (inexact->exact (floor v5)
)
)
)
)
)
)
 (begin (ret1 (modulo (_add (_add (_add (_add (+ d a)
 k)
 b)
 c)
 (* 5 j)
)
 7)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (define (main)
 (call/cc (lambda (ret6)
 (let ((months31 (_list 1 3 5 7 8 10 12)
)
)
 (begin (let ((names (_list "January" "February" "March" "April" "May" "June" "July" "August" "September" "October" "November" "December")
)
)
 (begin (let ((count 0)
)
 (begin (let ((firstY 0)
)
 (begin (let ((firstM 0)
)
 (begin (let ((lastY 0)
)
 (begin (let ((lastM 0)
)
 (begin (let ((haveNone (_list)
)
)
 (begin (_display (to-str "Months with five weekends:")
)
 (newline)
 (call/cc (lambda (break8)
 (letrec ((loop7 (lambda (year)
 (if (< year 2101)
 (begin (begin (let ((hasOne #f)
)
 (begin (call/cc (lambda (break10)
 (letrec ((loop9 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((m (car xs)
)
)
 (begin (if (equal? (weekday year m 1)
 6)
 (begin (_display (to-str (string-append (string-append (string-append "  " (to-str year)
)
 " ")
 (list-ref names (- m 1)
)
)
)
)
 (newline)
 (set! count (+ count 1)
)
 (set! hasOne #t)
 (set! lastY year)
 (set! lastM m)
 (if (equal? firstY 0)
 (begin (set! firstY year)
 (set! firstM m)
)
 (quote ()
)
)
)
 (quote ()
)
)
)
)
 (loop9 (cdr xs)
)
)
)
)
)
)
 (loop9 months31)
)
)
)
 (if (not hasOne)
 (begin (set! haveNone (append haveNone (_list year)
)
)
)
 (quote ()
)
)
)
)
)
 (loop7 (+ year 1)
)
)
 (quote ()
)
)
)
)
)
 (loop7 1900)
)
)
)
 (_display (to-str (string-append (to-str count)
 " total")
)
)
 (newline)
 (_display (to-str "")
)
 (newline)
 (_display (to-str "First five dates of weekends:")
)
 (newline)
 (call/cc (lambda (break12)
 (letrec ((loop11 (lambda (i)
 (if (< i 5)
 (begin (begin (let ((day (_add 1 (* 7 i)
)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append "  Friday, " (list-ref names (- firstM 1)
)
)
 " ")
 (to-str day)
)
 ", ")
 (to-str firstY)
)
)
)
 (newline)
)
)
)
 (loop11 (+ i 1)
)
)
 (quote ()
)
)
)
)
)
 (loop11 0)
)
)
)
 (_display (to-str "Last five dates of weekends:")
)
 (newline)
 (call/cc (lambda (break14)
 (letrec ((loop13 (lambda (i)
 (if (< i 5)
 (begin (begin (let ((day (_add 1 (* 7 i)
)
)
)
 (begin (_display (to-str (string-append (string-append (string-append (string-append (string-append "  Friday, " (list-ref names (- lastM 1)
)
)
 " ")
 (to-str day)
)
 ", ")
 (to-str lastY)
)
)
)
 (newline)
)
)
)
 (loop13 (+ i 1)
)
)
 (quote ()
)
)
)
)
)
 (loop13 0)
)
)
)
 (_display (to-str "")
)
 (newline)
 (_display (to-str "Years with no months with five weekends:")
)
 (newline)
 (call/cc (lambda (break16)
 (letrec ((loop15 (lambda (xs)
 (if (null? xs)
 (quote ()
)
 (begin (let ((y (car xs)
)
)
 (begin (_display (to-str (string-append "  " (to-str y)
)
)
)
 (newline)
)
)
 (loop15 (cdr xs)
)
)
)
)
)
)
 (loop15 haveNone)
)
)
)
 (_display (to-str (string-append (to-str (cond ((string? haveNone)
 (string-length haveNone)
)
 ((hash-table? haveNone)
 (hash-table-size haveNone)
)
 (else (length haveNone)
)
)
)
 " total")
)
)
 (newline)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
 (main)
 (let ((end18 (now)
)
)
 (let ((dur19 (quotient (- end18 start17)
 1000)
)
)
 (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur19)
 ",\n  \"memory_bytes\": " (number->string (_mem)
)
 ",\n  \"name\": \"main\"\n}")
)
 (newline)
)
)
)
)
)
