;; Generated on 2025-08-04 22:39 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(let ((start9 (current-jiffy)) (jps12 (jiffies-per-second))) (begin (define (step n program) (call/cc (lambda (ret1) (let ((i 0)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (< i (_len program)) (begin (let ((num (cond ((string? (list-ref program i)) (_substring (list-ref program i) 0 (+ 0 1))) ((hash-table? (list-ref program i)) (hash-table-ref (list-ref program i) 0)) (else (list-ref (list-ref program i) 0))))) (begin (let ((den (cond ((string? (list-ref program i)) (_substring (list-ref program i) 1 (+ 1 1))) ((hash-table? (list-ref program i)) (hash-table-ref (list-ref program i) 1)) (else (list-ref (list-ref program i) 1))))) (begin (if (equal? (fmod n den) 0) (begin (set! n (* (/ n den) num)) (ret1 (alist->hash-table (_list (cons "n" n) (cons "ok" #t))))) (quote ())) (set! i (+ i 1)))))) (loop2)) (quote ()))))) (loop2)))) (ret1 (alist->hash-table (_list (cons "n" n) (cons "ok" #f))))))))) (define (main) (call/cc (lambda (ret4) (let ((program (_list (_list 17 91) (_list 78 85) (_list 19 51) (_list 23 38) (_list 29 33) (_list 77 29) (_list 95 23) (_list 77 19) (_list 1 17) (_list 11 13) (_list 13 11) (_list 15 14) (_list 15 2) (_list 55 1)))) (begin (let ((n 2)) (begin (let ((primes 0)) (begin (let ((count 0)) (begin (let ((limit 1000000)) (begin (let ((two 2)) (begin (let ((line "")) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (and (< primes 20) (< count limit)) (begin (let ((res (step n program))) (begin (set! n (hash-table-ref res "n")) (if (not (hash-table-ref res "ok")) (begin (break6 (quote ()))) (quote ())) (let ((m n)) (begin (let ((pow 0)) (begin (call/cc (lambda (break8) (letrec ((loop7 (lambda () (if (equal? (fmod m two) 0) (begin (set! m (/ m two)) (set! pow (+ pow 1)) (loop7)) (quote ()))))) (loop7)))) (if (and (equal? m 1) (> pow 1)) (begin (set! line (string-append (string-append line (to-str pow)) " ")) (set! primes (+ primes 1))) (quote ())) (set! count (+ count 1)))))))) (loop5)) (quote ()))))) (loop5)))) (if (> (_len line) 0) (begin (_display (to-str (_substring line 0 (- (_len line) 1)))) (newline)) (begin (_display (to-str "")) (newline)))))))))))))))))))) (main) (let ((end10 (current-jiffy))) (let ((dur11 (quotient (* (- end10 start9) 1000000) jps12))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur11) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
