;; Generated on 2025-08-04 22:39 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(define (isPrime n) (call/cc (lambda (ret1) (begin (if (< n 2) (begin (ret1 #f)) (quote ())) (if (equal? (modulo n 2) 0) (begin (ret1 (equal? n 2))) (quote ())) (if (equal? (modulo n 3) 0) (begin (ret1 (equal? n 3))) (quote ())) (let ((d 5)) (begin (call/cc (lambda (break3) (letrec ((loop2 (lambda () (if (<= (* d d) n) (begin (if (equal? (modulo n d) 0) (begin (ret1 #f)) (quote ())) (set! d (+ d 2)) (if (equal? (modulo n d) 0) (begin (ret1 #f)) (quote ())) (set! d (+ d 4)) (loop2)) (quote ()))))) (loop2)))) (ret1 #t)))))))
(define (commatize n) (call/cc (lambda (ret4) (let ((s (to-str n))) (begin (let ((i (- (_len s) 3))) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (>= i 1) (begin (set! s (string-append (string-append (_substring s 0 i) ",") (_substring s i (_len s)))) (set! i (- i 3)) (loop5)) (quote ()))))) (loop5)))) (ret4 s))))))))
(define (padLeft s w) (call/cc (lambda (ret7) (let ((out s)) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (< (_len out) w) (begin (set! out (string-append " " out)) (loop8)) (quote ()))))) (loop8)))) (ret7 out))))))
(define (padRight s w) (call/cc (lambda (ret10) (let ((out s)) (begin (call/cc (lambda (break12) (letrec ((loop11 (lambda () (if (< (_len out) w) (begin (set! out (string-append out " ")) (loop11)) (quote ()))))) (loop11)))) (ret10 out))))))
(let ((limit 42)) (begin (define (main) (call/cc (lambda (ret13) (let ((i limit)) (begin (let ((n 0)) (begin (call/cc (lambda (break15) (letrec ((loop14 (lambda () (if (< n limit) (begin (if (isPrime i) (begin (set! n (+ n 1)) (let ((nStr (padRight (to-str n) 2))) (begin (let ((pStr (padLeft (commatize i) 19))) (begin (_display (to-str (string-append (string-append (string-append "n = " nStr) "  ") pStr))) (newline) (set! i (- (+ i i) 1))))))) (quote ())) (set! i (+ i 1)) (loop14)) (quote ()))))) (loop14))))))))))) (main)))
