;; Generated on 2025-08-04 22:39 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi crypto md5))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(define testpkg (make-hash-table))
(hash-table-set! testpkg "MD5Hex" (lambda (s) (md5 s)))
(call/cc (lambda (break2) (letrec ((loop1 (lambda (xs) (if (null? xs) (quote ()) (begin (let ((pair (car xs))) (begin (let ((sum ((hash-table-ref testpkg "MD5Hex") (cond ((string? pair) (_substring pair 1 (+ 1 1))) ((hash-table? pair) (hash-table-ref pair 1)) (else (list-ref pair 1)))))) (begin (if (not (equal? sum (cond ((string? pair) (_substring pair 0 (+ 0 1))) ((hash-table? pair) (hash-table-ref pair 0)) (else (list-ref pair 0))))) (begin (_display (to-str "MD5 fail")) (newline) (_display (to-str "  for string,")) (_display " ") (_display (to-str (cond ((string? pair) (_substring pair 1 (+ 1 1))) ((hash-table? pair) (hash-table-ref pair 1)) (else (list-ref pair 1))))) (newline) (_display (to-str "  expected:  ")) (_display " ") (_display (to-str (cond ((string? pair) (_substring pair 0 (+ 0 1))) ((hash-table? pair) (hash-table-ref pair 0)) (else (list-ref pair 0))))) (newline) (_display (to-str "  got:       ")) (_display " ") (_display (to-str sum)) (newline)) (quote ())))))) (loop1 (cdr xs))))))) (loop1 (_list (_list "d41d8cd98f00b204e9800998ecf8427e" "") (_list "0cc175b9c0f1b6a831c399e269772661" "a") (_list "900150983cd24fb0d6963f7d28e17f72" "abc") (_list "f96b697d7cb7938d525a2f31aaf161d0" "message digest") (_list "c3fcd3d76192e4007dfb496cca67e13b" "abcdefghijklmnopqrstuvwxyz") (_list "d174ab98d277d9f5a5611c2c9f419d9f" "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789") (_list "57edf4a22be3c955ac49da2e2107b67a" "12345678901234567890123456789012345678901234567890123456789012345678901234567890") (_list "e38ca1d920c4b8b8d3946b2c72f01680" "The quick brown fox jumped over the lazy dog's back"))))))
