;; Generated on 2025-08-04 22:39 +0700
(import (scheme base))
(import (scheme time))
(import (chibi string))
(import (only (scheme char) string-upcase string-downcase))
(import (srfi 69))
(import (srfi 1))
(define _list list)
(import (chibi time))
(define (_mem) (* 1024 (resource-usage-max-rss (get-resource-usage resource-usage/self))))
(import (chibi json))
(define (to-str x)
  (cond ((pair? x)
         (string-append "[" (string-join (map to-str x) ", ") "]"))
        ((hash-table? x)
         (let* ((ks (hash-table-keys x))
                (pairs (map (lambda (k)
                              (string-append (to-str k) ":" (to-str (hash-table-ref x k))))
                            ks)))
           (string-append "{" (string-join pairs ", ") "}")))
        ((null? x) "")
        ((string? x) x)
        ((boolean? x) (if x "1" "0"))
        (else (number->string x))))
(define (upper s) (string-upcase s))
(define (lower s) (string-downcase s))
(define (fmod a b) (- a (* (floor (/ a b)) b)))
(define (_gt a b) (cond ((and (number? a) (number? b)) (> a b)) ((and (string? a) (string? b)) (string>? a b)) (else (> a b))))
(define (_lt a b) (cond ((and (number? a) (number? b)) (< a b)) ((and (string? a) (string? b)) (string<? a b)) (else (< a b))))
(define (_ge a b) (cond ((and (number? a) (number? b)) (>= a b)) ((and (string? a) (string? b)) (string>=? a b)) (else (>= a b))))
(define (_le a b) (cond ((and (number? a) (number? b)) (<= a b)) ((and (string? a) (string? b)) (string<=? a b)) (else (<= a b))))
(define (_add a b)
  (cond ((and (number? a) (number? b)) (+ a b))
        ((string? a) (string-append a (to-str b)))
        ((string? b) (string-append (to-str a) b))
        ((and (list? a) (list? b)) (append a b))
        (else (+ a b))))
(define (indexOf s sub) (let ((cur (string-contains s sub)))   (if cur (string-cursor->index s cur) -1)))
(define (_display . args) (apply display args))
(define (padStart s width pad)
  (let loop ((out s))
    (if (< (string-length out) width)
        (loop (string-append pad out))
        out)))
(define (_substring s start end)
  (let* ((len (string-length s))
         (s0 (max 0 (min len start)))
         (e0 (max s0 (min len end))))
    (substring s s0 e0)))
(define (_repeat s n)
  (let loop ((i 0) (out ""))
    (if (< i n)
        (loop (+ i 1) (string-append out s))
        out)))
(define (slice seq start end)
  (let* ((len (if (string? seq) (string-length seq) (length seq)))
         (s (if (< start 0) (+ len start) start))
         (e (if (< end 0) (+ len end) end)))
    (set! s (max 0 (min len s)))
    (set! e (max 0 (min len e)))
    (when (< e s) (set! e s))
    (if (string? seq)
        (_substring seq s e)
        (take (drop seq s) (- e s)))))
(define (_parseIntStr s base)
  (let* ((b (if (number? base) base 10))
         (n (string->number (if (list? s) (list->string s) s) b)))
    (if n (inexact->exact (truncate n)) 0)))
(define (_split s sep)
  (let* ((str (if (string? s) s (list->string s)))
         (del (cond ((char? sep) sep)
                     ((string? sep) (if (= (string-length sep) 1)
                                       (string-ref sep 0)
                                       sep))
                     (else sep))))
    (cond
     ((and (string? del) (string=? del ""))
      (map string (string->list str)))
     ((char? del)
      (string-split str del))
     (else
        (let loop ((r str) (acc '()))
          (let ((cur (string-contains r del)))
            (if cur
                (let ((idx (string-cursor->index r cur)))
                  (loop (_substring r (+ idx (string-length del)) (string-length r))
                        (cons (_substring r 0 idx) acc)))
                (reverse (cons r acc)))))))))
(define (_len x)
  (cond ((string? x) (string-length x))
        ((hash-table? x) (hash-table-size x))
        (else (length x))))
(let ((start17 (current-jiffy)) (jps20 (jiffies-per-second))) (begin (let ((PI 3.141592653589793)) (begin (define (floorf x) (call/cc (lambda (ret1) (let ((i (let ((v2 x)) (cond ((string? v2) (inexact->exact (floor (string->number v2)))) ((boolean? v2) (if v2 1 0)) (else (inexact->exact (floor v2))))))) (begin (if (> (+ 0.0 i) x) (begin (set! i (- i 1))) (quote ())) (ret1 (+ 0.0 i))))))) (define (frac x) (call/cc (lambda (ret3) (ret3 (- x (floorf x)))))) (define (sinApprox x) (call/cc (lambda (ret4) (let ((term x)) (begin (let ((sum x)) (begin (let ((n 1)) (begin (call/cc (lambda (break6) (letrec ((loop5 (lambda () (if (<= n 10) (begin (let ((denom (+ 0.0 (* (* 2 n) (+ (* 2 n) 1))))) (begin (set! term (/ (* (* (- term) x) x) denom)) (set! sum (+ sum term)) (set! n (+ n 1)))) (loop5)) (quote ()))))) (loop5)))) (ret4 sum)))))))))) (define (sqrtApprox x) (call/cc (lambda (ret7) (begin (if (<= x 0) (begin (ret7 0.0)) (quote ())) (let ((guess x)) (begin (let ((i 0)) (begin (call/cc (lambda (break9) (letrec ((loop8 (lambda () (if (< i 10) (begin (set! guess (/ (_add guess (/ x guess)) 2.0)) (set! i (+ i 1)) (loop8)) (quote ()))))) (loop8)))) (ret7 guess))))))))) (let ((nframes 10)) (begin (let ((w 32)) (begin (let ((h 32)) (begin (let ((total 0)) (begin (let ((f 1)) (begin (call/cc (lambda (break11) (letrec ((loop10 (lambda () (if (<= f nframes) (begin (let ((y 0)) (begin (call/cc (lambda (break13) (letrec ((loop12 (lambda () (if (< y h) (begin (let ((x 0)) (begin (call/cc (lambda (break15) (letrec ((loop14 (lambda () (if (< x w) (begin (let ((fx (+ 0.0 x))) (begin (let ((fy (+ 0.0 y))) (begin (let ((value (sinApprox (/ fx 16.0)))) (begin (set! value (_add value (sinApprox (/ fy 8.0)))) (set! value (_add value (sinApprox (/ (+ fx fy) 16.0)))) (set! value (_add value (sinApprox (/ (sqrtApprox (_add (* fx fx) (* fy fy))) 8.0)))) (set! value (_add value 4.0)) (set! value (/ value 8.0)) (let ((rem (frac (_add value (/ (+ 0.0 f) (+ 0.0 nframes)))))) (begin (let ((ci (+ (let ((v16 (* (+ 0.0 nframes) rem))) (cond ((string? v16) (inexact->exact (floor (string->number v16)))) ((boolean? v16) (if v16 1 0)) (else (inexact->exact (floor v16))))) 1))) (begin (set! total (+ total ci)) (set! x (+ x 1)))))))))))) (loop14)) (quote ()))))) (loop14)))) (set! y (+ y 1)))) (loop12)) (quote ()))))) (loop12)))) (set! f (+ f 1)))) (loop10)) (quote ()))))) (loop10)))) (_display (to-str total)) (newline))))))))))))) (let ((end18 (current-jiffy))) (let ((dur19 (quotient (* (- end18 start17) 1000000) jps20))) (begin (_display (string-append "{\n  \"duration_us\": " (number->string dur19) ",\n  \"memory_bytes\": " (number->string (_mem)) ",\n  \"name\": \"main\"\n}")) (newline))))))
